// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import (
	gin "github.com/gin-gonic/gin"
	entities "gitlab.com/interview-simulation/interview-backend-server/internal/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCookies is an autogenerated mock type for the Cookies type
type MockCookies struct {
	mock.Mock
}

type MockCookies_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookies) EXPECT() *MockCookies_Expecter {
	return &MockCookies_Expecter{mock: &_m.Mock}
}

// SetCookie provides a mock function with given fields: ctx, req
func (_m *MockCookies) SetCookie(ctx *gin.Context, req *entities.SignInUserByEmailAndPasswordResponse) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetCookie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *entities.SignInUserByEmailAndPasswordResponse) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCookies_SetCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCookie'
type MockCookies_SetCookie_Call struct {
	*mock.Call
}

// SetCookie is a helper method to define mock.On call
//   - ctx *gin.Context
//   - req *entities.SignInUserByEmailAndPasswordResponse
func (_e *MockCookies_Expecter) SetCookie(ctx interface{}, req interface{}) *MockCookies_SetCookie_Call {
	return &MockCookies_SetCookie_Call{Call: _e.mock.On("SetCookie", ctx, req)}
}

func (_c *MockCookies_SetCookie_Call) Run(run func(ctx *gin.Context, req *entities.SignInUserByEmailAndPasswordResponse)) *MockCookies_SetCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(*entities.SignInUserByEmailAndPasswordResponse))
	})
	return _c
}

func (_c *MockCookies_SetCookie_Call) Return(_a0 error) *MockCookies_SetCookie_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCookies_SetCookie_Call) RunAndReturn(run func(*gin.Context, *entities.SignInUserByEmailAndPasswordResponse) error) *MockCookies_SetCookie_Call {
	_c.Call.Return(run)
	return _c
}

// SetRefreshTokenCookie provides a mock function with given fields: c, token, duration, domain, isRejectHTTP
func (_m *MockCookies) SetRefreshTokenCookie(c *gin.Context, token string, duration time.Duration, domain string, isRejectHTTP bool) {
	_m.Called(c, token, duration, domain, isRejectHTTP)
}

// MockCookies_SetRefreshTokenCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRefreshTokenCookie'
type MockCookies_SetRefreshTokenCookie_Call struct {
	*mock.Call
}

// SetRefreshTokenCookie is a helper method to define mock.On call
//   - c *gin.Context
//   - token string
//   - duration time.Duration
//   - domain string
//   - isRejectHTTP bool
func (_e *MockCookies_Expecter) SetRefreshTokenCookie(c interface{}, token interface{}, duration interface{}, domain interface{}, isRejectHTTP interface{}) *MockCookies_SetRefreshTokenCookie_Call {
	return &MockCookies_SetRefreshTokenCookie_Call{Call: _e.mock.On("SetRefreshTokenCookie", c, token, duration, domain, isRejectHTTP)}
}

func (_c *MockCookies_SetRefreshTokenCookie_Call) Run(run func(c *gin.Context, token string, duration time.Duration, domain string, isRejectHTTP bool)) *MockCookies_SetRefreshTokenCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(string), args[2].(time.Duration), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockCookies_SetRefreshTokenCookie_Call) Return() *MockCookies_SetRefreshTokenCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookies_SetRefreshTokenCookie_Call) RunAndReturn(run func(*gin.Context, string, time.Duration, string, bool)) *MockCookies_SetRefreshTokenCookie_Call {
	_c.Run(run)
	return _c
}

// NewMockCookies creates a new instance of MockCookies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookies(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookies {
	mock := &MockCookies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
