// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// GenerateRandomString provides a mock function with given fields: ctx, length
func (_m *MockGenerator) GenerateRandomString(ctx context.Context, length int) string {
	ret := _m.Called(ctx, length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGenerator_GenerateRandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRandomString'
type MockGenerator_GenerateRandomString_Call struct {
	*mock.Call
}

// GenerateRandomString is a helper method to define mock.On call
//   - ctx context.Context
//   - length int
func (_e *MockGenerator_Expecter) GenerateRandomString(ctx interface{}, length interface{}) *MockGenerator_GenerateRandomString_Call {
	return &MockGenerator_GenerateRandomString_Call{Call: _e.mock.On("GenerateRandomString", ctx, length)}
}

func (_c *MockGenerator_GenerateRandomString_Call) Run(run func(ctx context.Context, length int)) *MockGenerator_GenerateRandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockGenerator_GenerateRandomString_Call) Return(_a0 string) *MockGenerator_GenerateRandomString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenerator_GenerateRandomString_Call) RunAndReturn(run func(context.Context, int) string) *MockGenerator_GenerateRandomString_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUUID provides a mock function with given fields: ctx
func (_m *MockGenerator) GenerateUUID(ctx context.Context) uuid.UUID {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUUID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockGenerator_GenerateUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUUID'
type MockGenerator_GenerateUUID_Call struct {
	*mock.Call
}

// GenerateUUID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGenerator_Expecter) GenerateUUID(ctx interface{}) *MockGenerator_GenerateUUID_Call {
	return &MockGenerator_GenerateUUID_Call{Call: _e.mock.On("GenerateUUID", ctx)}
}

func (_c *MockGenerator_GenerateUUID_Call) Run(run func(ctx context.Context)) *MockGenerator_GenerateUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGenerator_GenerateUUID_Call) Return(_a0 uuid.UUID) *MockGenerator_GenerateUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenerator_GenerateUUID_Call) RunAndReturn(run func(context.Context) uuid.UUID) *MockGenerator_GenerateUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
