// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	entities "gitlab.com/interview-simulation/interview-backend-server/internal/entities"

	jwt "github.com/dgrijalva/jwt-go"

	mock "github.com/stretchr/testify/mock"

	utils "gitlab.com/interview-simulation/interview-backend-server/internal/utils"
)

// MockJwtToken is an autogenerated mock type for the JwtToken type
type MockJwtToken struct {
	mock.Mock
}

type MockJwtToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtToken) EXPECT() *MockJwtToken_Expecter {
	return &MockJwtToken_Expecter{mock: &_m.Mock}
}

// CreateJWTToken provides a mock function with given fields: ctx, claims
func (_m *MockJwtToken) CreateJWTToken(ctx context.Context, claims jwt.Claims) (string, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for CreateJWTToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) (string, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) string); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, jwt.Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtToken_CreateJWTToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJWTToken'
type MockJwtToken_CreateJWTToken_Call struct {
	*mock.Call
}

// CreateJWTToken is a helper method to define mock.On call
//   - ctx context.Context
//   - claims jwt.Claims
func (_e *MockJwtToken_Expecter) CreateJWTToken(ctx interface{}, claims interface{}) *MockJwtToken_CreateJWTToken_Call {
	return &MockJwtToken_CreateJWTToken_Call{Call: _e.mock.On("CreateJWTToken", ctx, claims)}
}

func (_c *MockJwtToken_CreateJWTToken_Call) Run(run func(ctx context.Context, claims jwt.Claims)) *MockJwtToken_CreateJWTToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jwt.Claims))
	})
	return _c
}

func (_c *MockJwtToken_CreateJWTToken_Call) Return(_a0 string, _a1 error) *MockJwtToken_CreateJWTToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtToken_CreateJWTToken_Call) RunAndReturn(run func(context.Context, jwt.Claims) (string, error)) *MockJwtToken_CreateJWTToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function with given fields: ctx, req
func (_m *MockJwtToken) CreateToken(ctx context.Context, req *entities.TokenRequest) (string, *utils.SignInTokenPayload, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 *utils.SignInTokenPayload
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.TokenRequest) (string, *utils.SignInTokenPayload, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.TokenRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.TokenRequest) *utils.SignInTokenPayload); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.SignInTokenPayload)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *entities.TokenRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJwtToken_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockJwtToken_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.TokenRequest
func (_e *MockJwtToken_Expecter) CreateToken(ctx interface{}, req interface{}) *MockJwtToken_CreateToken_Call {
	return &MockJwtToken_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, req)}
}

func (_c *MockJwtToken_CreateToken_Call) Run(run func(ctx context.Context, req *entities.TokenRequest)) *MockJwtToken_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.TokenRequest))
	})
	return _c
}

func (_c *MockJwtToken_CreateToken_Call) Return(_a0 string, _a1 *utils.SignInTokenPayload, _a2 error) *MockJwtToken_CreateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJwtToken_CreateToken_Call) RunAndReturn(run func(context.Context, *entities.TokenRequest) (string, *utils.SignInTokenPayload, error)) *MockJwtToken_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerifyEmailToken provides a mock function with given fields: ctx, req
func (_m *MockJwtToken) CreateVerifyEmailToken(ctx context.Context, req *entities.VerifyEmailTokenRequest) (string, *utils.VerifyEmailTokenPayload, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerifyEmailToken")
	}

	var r0 string
	var r1 *utils.VerifyEmailTokenPayload
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.VerifyEmailTokenRequest) (string, *utils.VerifyEmailTokenPayload, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.VerifyEmailTokenRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.VerifyEmailTokenRequest) *utils.VerifyEmailTokenPayload); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.VerifyEmailTokenPayload)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *entities.VerifyEmailTokenRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJwtToken_CreateVerifyEmailToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerifyEmailToken'
type MockJwtToken_CreateVerifyEmailToken_Call struct {
	*mock.Call
}

// CreateVerifyEmailToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.VerifyEmailTokenRequest
func (_e *MockJwtToken_Expecter) CreateVerifyEmailToken(ctx interface{}, req interface{}) *MockJwtToken_CreateVerifyEmailToken_Call {
	return &MockJwtToken_CreateVerifyEmailToken_Call{Call: _e.mock.On("CreateVerifyEmailToken", ctx, req)}
}

func (_c *MockJwtToken_CreateVerifyEmailToken_Call) Run(run func(ctx context.Context, req *entities.VerifyEmailTokenRequest)) *MockJwtToken_CreateVerifyEmailToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.VerifyEmailTokenRequest))
	})
	return _c
}

func (_c *MockJwtToken_CreateVerifyEmailToken_Call) Return(_a0 string, _a1 *utils.VerifyEmailTokenPayload, _a2 error) *MockJwtToken_CreateVerifyEmailToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJwtToken_CreateVerifyEmailToken_Call) RunAndReturn(run func(context.Context, *entities.VerifyEmailTokenRequest) (string, *utils.VerifyEmailTokenPayload, error)) *MockJwtToken_CreateVerifyEmailToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebSocketSessionToken provides a mock function with given fields: ctx, req
func (_m *MockJwtToken) CreateWebSocketSessionToken(ctx context.Context, req *entities.WebSocketSessionReq) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebSocketSessionToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.WebSocketSessionReq) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.WebSocketSessionReq) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.WebSocketSessionReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtToken_CreateWebSocketSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebSocketSessionToken'
type MockJwtToken_CreateWebSocketSessionToken_Call struct {
	*mock.Call
}

// CreateWebSocketSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.WebSocketSessionReq
func (_e *MockJwtToken_Expecter) CreateWebSocketSessionToken(ctx interface{}, req interface{}) *MockJwtToken_CreateWebSocketSessionToken_Call {
	return &MockJwtToken_CreateWebSocketSessionToken_Call{Call: _e.mock.On("CreateWebSocketSessionToken", ctx, req)}
}

func (_c *MockJwtToken_CreateWebSocketSessionToken_Call) Run(run func(ctx context.Context, req *entities.WebSocketSessionReq)) *MockJwtToken_CreateWebSocketSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.WebSocketSessionReq))
	})
	return _c
}

func (_c *MockJwtToken_CreateWebSocketSessionToken_Call) Return(_a0 string, _a1 error) *MockJwtToken_CreateWebSocketSessionToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtToken_CreateWebSocketSessionToken_Call) RunAndReturn(run func(context.Context, *entities.WebSocketSessionReq) (string, error)) *MockJwtToken_CreateWebSocketSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashTokenSHA256 provides a mock function with given fields: ctx, token
func (_m *MockJwtToken) HashTokenSHA256(ctx context.Context, token string) string {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for HashTokenSHA256")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockJwtToken_HashTokenSHA256_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashTokenSHA256'
type MockJwtToken_HashTokenSHA256_Call struct {
	*mock.Call
}

// HashTokenSHA256 is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockJwtToken_Expecter) HashTokenSHA256(ctx interface{}, token interface{}) *MockJwtToken_HashTokenSHA256_Call {
	return &MockJwtToken_HashTokenSHA256_Call{Call: _e.mock.On("HashTokenSHA256", ctx, token)}
}

func (_c *MockJwtToken_HashTokenSHA256_Call) Run(run func(ctx context.Context, token string)) *MockJwtToken_HashTokenSHA256_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJwtToken_HashTokenSHA256_Call) Return(_a0 string) *MockJwtToken_HashTokenSHA256_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJwtToken_HashTokenSHA256_Call) RunAndReturn(run func(context.Context, string) string) *MockJwtToken_HashTokenSHA256_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenMatch provides a mock function with given fields: ctx, providedToken, storedTokenHash
func (_m *MockJwtToken) IsTokenMatch(ctx context.Context, providedToken string, storedTokenHash string) bool {
	ret := _m.Called(ctx, providedToken, storedTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenMatch")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, providedToken, storedTokenHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockJwtToken_IsTokenMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenMatch'
type MockJwtToken_IsTokenMatch_Call struct {
	*mock.Call
}

// IsTokenMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - providedToken string
//   - storedTokenHash string
func (_e *MockJwtToken_Expecter) IsTokenMatch(ctx interface{}, providedToken interface{}, storedTokenHash interface{}) *MockJwtToken_IsTokenMatch_Call {
	return &MockJwtToken_IsTokenMatch_Call{Call: _e.mock.On("IsTokenMatch", ctx, providedToken, storedTokenHash)}
}

func (_c *MockJwtToken_IsTokenMatch_Call) Run(run func(ctx context.Context, providedToken string, storedTokenHash string)) *MockJwtToken_IsTokenMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockJwtToken_IsTokenMatch_Call) Return(_a0 bool) *MockJwtToken_IsTokenMatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJwtToken_IsTokenMatch_Call) RunAndReturn(run func(context.Context, string, string) bool) *MockJwtToken_IsTokenMatch_Call {
	_c.Call.Return(run)
	return _c
}

// RenewAccessToken provides a mock function with given fields: ctx, token
func (_m *MockJwtToken) RenewAccessToken(ctx *gin.Context, token string) (string, *utils.SignInTokenPayload, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RenewAccessToken")
	}

	var r0 string
	var r1 *utils.SignInTokenPayload
	var r2 error
	if rf, ok := ret.Get(0).(func(*gin.Context, string) (string, *utils.SignInTokenPayload, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, string) *utils.SignInTokenPayload); ok {
		r1 = rf(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.SignInTokenPayload)
		}
	}

	if rf, ok := ret.Get(2).(func(*gin.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJwtToken_RenewAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewAccessToken'
type MockJwtToken_RenewAccessToken_Call struct {
	*mock.Call
}

// RenewAccessToken is a helper method to define mock.On call
//   - ctx *gin.Context
//   - token string
func (_e *MockJwtToken_Expecter) RenewAccessToken(ctx interface{}, token interface{}) *MockJwtToken_RenewAccessToken_Call {
	return &MockJwtToken_RenewAccessToken_Call{Call: _e.mock.On("RenewAccessToken", ctx, token)}
}

func (_c *MockJwtToken_RenewAccessToken_Call) Run(run func(ctx *gin.Context, token string)) *MockJwtToken_RenewAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJwtToken_RenewAccessToken_Call) Return(_a0 string, _a1 *utils.SignInTokenPayload, _a2 error) *MockJwtToken_RenewAccessToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJwtToken_RenewAccessToken_Call) RunAndReturn(run func(*gin.Context, string) (string, *utils.SignInTokenPayload, error)) *MockJwtToken_RenewAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RenewVerifyEmailToken provides a mock function with given fields: ctx, oldToken
func (_m *MockJwtToken) RenewVerifyEmailToken(ctx context.Context, oldToken string) (string, *utils.VerifyEmailTokenPayload, error) {
	ret := _m.Called(ctx, oldToken)

	if len(ret) == 0 {
		panic("no return value specified for RenewVerifyEmailToken")
	}

	var r0 string
	var r1 *utils.VerifyEmailTokenPayload
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, *utils.VerifyEmailTokenPayload, error)); ok {
		return rf(ctx, oldToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, oldToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *utils.VerifyEmailTokenPayload); ok {
		r1 = rf(ctx, oldToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.VerifyEmailTokenPayload)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, oldToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJwtToken_RenewVerifyEmailToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewVerifyEmailToken'
type MockJwtToken_RenewVerifyEmailToken_Call struct {
	*mock.Call
}

// RenewVerifyEmailToken is a helper method to define mock.On call
//   - ctx context.Context
//   - oldToken string
func (_e *MockJwtToken_Expecter) RenewVerifyEmailToken(ctx interface{}, oldToken interface{}) *MockJwtToken_RenewVerifyEmailToken_Call {
	return &MockJwtToken_RenewVerifyEmailToken_Call{Call: _e.mock.On("RenewVerifyEmailToken", ctx, oldToken)}
}

func (_c *MockJwtToken_RenewVerifyEmailToken_Call) Run(run func(ctx context.Context, oldToken string)) *MockJwtToken_RenewVerifyEmailToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJwtToken_RenewVerifyEmailToken_Call) Return(_a0 string, _a1 *utils.VerifyEmailTokenPayload, _a2 error) *MockJwtToken_RenewVerifyEmailToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJwtToken_RenewVerifyEmailToken_Call) RunAndReturn(run func(context.Context, string) (string, *utils.VerifyEmailTokenPayload, error)) *MockJwtToken_RenewVerifyEmailToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *MockJwtToken) VerifyToken(ctx context.Context, token string) (*utils.SignInTokenPayload, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *utils.SignInTokenPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*utils.SignInTokenPayload, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *utils.SignInTokenPayload); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.SignInTokenPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtToken_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockJwtToken_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockJwtToken_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockJwtToken_VerifyToken_Call {
	return &MockJwtToken_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockJwtToken_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockJwtToken_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJwtToken_VerifyToken_Call) Return(_a0 *utils.SignInTokenPayload, _a1 error) *MockJwtToken_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtToken_VerifyToken_Call) RunAndReturn(run func(context.Context, string) (*utils.SignInTokenPayload, error)) *MockJwtToken_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyVerifyEmailToken provides a mock function with given fields: ctx, token
func (_m *MockJwtToken) VerifyVerifyEmailToken(ctx context.Context, token string) (*utils.VerifyEmailTokenPayload, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyVerifyEmailToken")
	}

	var r0 *utils.VerifyEmailTokenPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*utils.VerifyEmailTokenPayload, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *utils.VerifyEmailTokenPayload); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.VerifyEmailTokenPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtToken_VerifyVerifyEmailToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyVerifyEmailToken'
type MockJwtToken_VerifyVerifyEmailToken_Call struct {
	*mock.Call
}

// VerifyVerifyEmailToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockJwtToken_Expecter) VerifyVerifyEmailToken(ctx interface{}, token interface{}) *MockJwtToken_VerifyVerifyEmailToken_Call {
	return &MockJwtToken_VerifyVerifyEmailToken_Call{Call: _e.mock.On("VerifyVerifyEmailToken", ctx, token)}
}

func (_c *MockJwtToken_VerifyVerifyEmailToken_Call) Run(run func(ctx context.Context, token string)) *MockJwtToken_VerifyVerifyEmailToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJwtToken_VerifyVerifyEmailToken_Call) Return(_a0 *utils.VerifyEmailTokenPayload, _a1 error) *MockJwtToken_VerifyVerifyEmailToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtToken_VerifyVerifyEmailToken_Call) RunAndReturn(run func(context.Context, string) (*utils.VerifyEmailTokenPayload, error)) *MockJwtToken_VerifyVerifyEmailToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtToken creates a new instance of MockJwtToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtToken {
	mock := &MockJwtToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
