// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	validator "github.com/go-playground/validator/v10"
)

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// GetValidate provides a mock function with no fields
func (_m *MockValidator) GetValidate() *validator.Validate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValidate")
	}

	var r0 *validator.Validate
	if rf, ok := ret.Get(0).(func() *validator.Validate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validator.Validate)
		}
	}

	return r0
}

// MockValidator_GetValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidate'
type MockValidator_GetValidate_Call struct {
	*mock.Call
}

// GetValidate is a helper method to define mock.On call
func (_e *MockValidator_Expecter) GetValidate() *MockValidator_GetValidate_Call {
	return &MockValidator_GetValidate_Call{Call: _e.mock.On("GetValidate")}
}

func (_c *MockValidator_GetValidate_Call) Run(run func()) *MockValidator_GetValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_GetValidate_Call) Return(_a0 *validator.Validate) *MockValidator_GetValidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_GetValidate_Call) RunAndReturn(run func() *validator.Validate) *MockValidator_GetValidate_Call {
	_c.Call.Return(run)
	return _c
}

// IsAllowedResumeContentType provides a mock function with given fields: ctx, fileHeader
func (_m *MockValidator) IsAllowedResumeContentType(ctx context.Context, fileHeader *multipart.FileHeader) bool {
	ret := _m.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedResumeContentType")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) bool); ok {
		r0 = rf(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValidator_IsAllowedResumeContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowedResumeContentType'
type MockValidator_IsAllowedResumeContentType_Call struct {
	*mock.Call
}

// IsAllowedResumeContentType is a helper method to define mock.On call
//   - ctx context.Context
//   - fileHeader *multipart.FileHeader
func (_e *MockValidator_Expecter) IsAllowedResumeContentType(ctx interface{}, fileHeader interface{}) *MockValidator_IsAllowedResumeContentType_Call {
	return &MockValidator_IsAllowedResumeContentType_Call{Call: _e.mock.On("IsAllowedResumeContentType", ctx, fileHeader)}
}

func (_c *MockValidator_IsAllowedResumeContentType_Call) Run(run func(ctx context.Context, fileHeader *multipart.FileHeader)) *MockValidator_IsAllowedResumeContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*multipart.FileHeader))
	})
	return _c
}

func (_c *MockValidator_IsAllowedResumeContentType_Call) Return(_a0 bool) *MockValidator_IsAllowedResumeContentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_IsAllowedResumeContentType_Call) RunAndReturn(run func(context.Context, *multipart.FileHeader) bool) *MockValidator_IsAllowedResumeContentType_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAndBind provides a mock function with given fields: c, req, handlerName
func (_m *MockValidator) ValidateAndBind(c *gin.Context, req interface{}, handlerName string) error {
	ret := _m.Called(c, req, handlerName)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndBind")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}, string) error); ok {
		r0 = rf(c, req, handlerName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_ValidateAndBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAndBind'
type MockValidator_ValidateAndBind_Call struct {
	*mock.Call
}

// ValidateAndBind is a helper method to define mock.On call
//   - c *gin.Context
//   - req interface{}
//   - handlerName string
func (_e *MockValidator_Expecter) ValidateAndBind(c interface{}, req interface{}, handlerName interface{}) *MockValidator_ValidateAndBind_Call {
	return &MockValidator_ValidateAndBind_Call{Call: _e.mock.On("ValidateAndBind", c, req, handlerName)}
}

func (_c *MockValidator_ValidateAndBind_Call) Run(run func(c *gin.Context, req interface{}, handlerName string)) *MockValidator_ValidateAndBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockValidator_ValidateAndBind_Call) Return(_a0 error) *MockValidator_ValidateAndBind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_ValidateAndBind_Call) RunAndReturn(run func(*gin.Context, interface{}, string) error) *MockValidator_ValidateAndBind_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
