version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    container_name: onyx-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onyx
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - onyx-network

  redis:
    image: redis:alpine
    container_name: onyx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - onyx-network

  onyx-backend-server:
    container_name: onyx-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    networks:
      - onyx-network
    depends_on:
      - postgres
      - redis
    environment:
      ENV: dev
      DB_SOURCE: postgresql://user:password@postgres:5432/onyx?sslmode=disable
    entrypoint: ["/app/migration.sh", "postgres:5432", "--"]
    command: ["/app/main"]

networks:
  onyx-network:
    external: true


