package app_error

var ErrorCodeToHttpCode = map[ErrorCode]ErrorHttpCode{
	// General
	ErrCodeGeneralServerUnavailable:   ErrHttpCodeInternalServerError,
	ErrCodeGeneralRequestTimeout:      ErrHttpCodeInternalServerError,
	ErrCodeGeneralResourceNotFound:    ErrHttpCodeNotFound,
	ErrCodeGeneralDatabaseConnection:  ErrHttpCodeInternalServerError,
	ErrCodeGeneralConstraintViolation: ErrHttpCodeBadRequest,
	ErrCodeGeneralInvalidUUID:         ErrHttpCodeBadRequest,

	// Auth
	ErrCodeAuthInvalidToken:            ErrHttpCodeUnauthorized,
	ErrCodeAuthExpiredToken:            ErrHttpCodeUnauthorized,
	ErrCodeAuthInvalidRefreshToken:     ErrHttpCodeUnauthorized,
	ErrCodeAuthExpiredRefreshToken:     ErrHttpCodeUnauthorized,
	ErrCodeAuthInvalidPassword:         ErrHttpCodeBadRequest,
	ErrCodeAuthUserNotFound:            ErrHttpCodeNotFound,
	ErrCodeAuthUserAlreadyExists:       ErrHttpCodeBadRequest,
	ErrCodeAuthResetTokenNotFound:      ErrHttpCodeNotFound,
	ErrCodeAuthResetTokenExpired:       ErrHttpCodeNotFound,
	ErrCodeAuthResetTokenUsed:          ErrHttpCodeNotFound,
	ErrCodeAuthPasswordSameAsOld:       ErrHttpCodeBadRequest,
	ErrCodeAuthInvalidHeader:           ErrHttpCodeUnauthorized,
	ErrCodeAuthInvalidRequest:          ErrHttpCodeBadRequest,
	ErrCodeAuthInvalidVerifyEmailCode:  ErrHttpCodeBadRequest,
	ErrCodeAuthInvalidVerifyEmailToken: ErrHttpCodeBadRequest,
	ErrCodeAuthMaxAttemptVerifyEmail:   ErrHttpCodeBadRequest,
	ErrCodeAuthSessionNotFound:         ErrHttpCodeNotFound,
	ErrCodeAuthEmailNotVerified:        ErrHttpCodeBadRequest,

	// Resume
	ErrCodeResumeInvalidFileSize:        ErrHttpCodeBadRequest,
	ErrCodeResumeInvalidFileContentType: ErrHttpCodeBadRequest,
	ErrCodeResumeUploadFailed:           ErrHttpCodeInternalServerError,
	ErrCodeResumeAlreadyExists:          ErrHttpCodeBadRequest,
	ErrCodeResumeNotFound:               ErrHttpCodeNotFound,
	ErrCodeResumeInvalidID:              ErrHttpCodeBadRequest,
	ErrCodeResumeInvalidRequest:         ErrHttpCodeBadRequest,

	// Session
	ErrCodeSessionInvalidToken:                   ErrHttpCodeBadRequest,
	ErrCodeSessionNotFound:                       ErrHttpCodeNotFound,
	ErrCodeWebSocketInvalidHello:                 ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidSegmentStart:          ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidSegmentEnd:            ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidStopTTS:               ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidDBAck:                 ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidError:                 ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidPing:                  ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidMessage:               ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidUserPartialTranscript: ErrHttpCodeBadRequest,
	ErrCodeWebSocketInvalidUserFullTranscript:    ErrHttpCodeBadRequest,
	ErrCodeInterviewSessionStartEndTimeNotFound:  ErrHttpCodeNotFound,
	ErrCodeInterviewSessionStartTimeNotFound:     ErrHttpCodeNotFound,
	ErrCodeInterviewSessionEndTimeNotFound:       ErrHttpCodeNotFound,
}

var ErrorCodeToMessage = map[ErrorCode]ErrorMessage{
	// General
	ErrCodeGeneralServerUnavailable:   ErrMessageGeneralServerUnavailable,
	ErrCodeGeneralRequestTimeout:      ErrMessageGeneralRequestTimeout,
	ErrCodeGeneralResourceNotFound:    ErrMessageGeneralResourceNotFound,
	ErrCodeGeneralDatabaseConnection:  ErrMessageGeneralDatabaseConnection,
	ErrCodeGeneralConstraintViolation: ErrMessageGeneralConstraintViolation,
	ErrCodeGeneralInvalidUUID:         ErrMessageGeneralInvalidUUID,

	// Auth
	ErrCodeAuthInvalidToken:            ErrMessageAuthInvalidToken,
	ErrCodeAuthExpiredToken:            ErrMessageAuthExpiredToken,
	ErrCodeAuthInvalidRefreshToken:     ErrMessageAuthInvalidRefreshToken,
	ErrCodeAuthExpiredRefreshToken:     ErrMessageAuthExpiredRefreshToken,
	ErrCodeAuthInvalidPassword:         ErrMessageAuthInvalidPassword,
	ErrCodeAuthUserNotFound:            ErrMessageAuthUserNotFound,
	ErrCodeAuthUserAlreadyExists:       ErrMessageAuthUserAlreadyExists,
	ErrCodeAuthResetTokenNotFound:      ErrMessageAuthResetTokenNotFound,
	ErrCodeAuthResetTokenExpired:       ErrMessageAuthResetTokenExpired,
	ErrCodeAuthResetTokenUsed:          ErrMessageAuthResetTokenUsed,
	ErrCodeAuthPasswordSameAsOld:       ErrMessageAuthPasswordSameAsOld,
	ErrCodeAuthInvalidHeader:           ErrMessageAuthInvalidHeader,
	ErrCodeAuthInvalidRequest:          ErrMessageAuthInvalidRequest,
	ErrCodeAuthInvalidVerifyEmailCode:  ErrMessageAuthInvalidVerifyEmailCode,
	ErrCodeAuthInvalidVerifyEmailToken: ErrMessageAuthInvalidVerifyEmailToken,
	ErrCodeAuthMaxAttemptVerifyEmail:   ErrMessageAuthMaxAttemptVerifyEmail,
	ErrCodeAuthSessionNotFound:         ErrMessageAuthSessionNotFound,
	ErrCodeAuthEmailNotVerified:        ErrMessageAuthEmailNotVerified,

	// Resume
	ErrCodeResumeInvalidFileSize:        ErrMessageResumeInvalidFileSize,
	ErrCodeResumeInvalidFileContentType: ErrMessageResumeInvalidFileContentType,
	ErrCodeResumeUploadFailed:           ErrMessageResumeUploadFailed,
	ErrCodeResumeAlreadyExists:          ErrMessageResumeAlreadyExists,
	ErrCodeResumeNotFound:               ErrMessageResumeNotFound,
	ErrCodeResumeInvalidID:              ErrMessageResumeInvalidID,
	ErrCodeResumeInvalidRequest:         ErrMessageResumeInvalidRequest,

	// Session
	ErrCodeSessionInvalidToken:                   ErrMessageSessionInvalidToken,
	ErrCodeSessionNotFound:                       ErrMessageSessionNotFound,
	ErrCodeWebSocketInvalidHello:                 ErrMessageWebSocketInvalidHello,
	ErrCodeWebSocketInvalidSegmentStart:          ErrMessageWebSocketInvalidSegmentStart,
	ErrCodeWebSocketInvalidSegmentEnd:            ErrMessageWebSocketInvalidSegmentEnd,
	ErrCodeWebSocketInvalidStopTTS:               ErrMessageWebSocketInvalidStopTTS,
	ErrCodeWebSocketInvalidDBAck:                 ErrMessageWebSocketInvalidDBAck,
	ErrCodeWebSocketInvalidError:                 ErrMessageWebSocketInvalidError,
	ErrCodeWebSocketInvalidPing:                  ErrMessageWebSocketInvalidPing,
	ErrCodeWebSocketInvalidMessage:               ErrMessageWebSocketInvalidMessage,
	ErrCodeWebSocketInvalidUserPartialTranscript: ErrMessageWebSocketInvalidUserPartialTranscript,
	ErrCodeWebSocketInvalidUserFullTranscript:    ErrMessageWebSocketInvalidUserFullTranscript,
	ErrCodeInterviewSessionStartEndTimeNotFound:  ErrMessageInterviewSessionStartEndTimeNotFound,
	ErrCodeInterviewSessionStartTimeNotFound:     ErrMessageInterviewSessionStartTimeNotFound,
	ErrCodeInterviewSessionEndTimeNotFound:       ErrMessageInterviewSessionEndTimeNotFound,
}
