// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: evaluations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvaluation = `-- name: CreateEvaluation :exec
INSERT INTO evaluations (
    id,
    session_id,
    turn_id,
    rubric_id,
    evaluator_user_id,
    current_state,
    overall_score,
    summary_md,
    
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateEvaluationParams struct {
	ID              uuid.UUID    `json:"id"`
	SessionID       uuid.UUID    `json:"session_id"`
	TurnID          uuid.UUID    `json:"turn_id"`
	RubricID        uuid.UUID    `json:"rubric_id"`
	EvaluatorUserID uuid.UUID    `json:"evaluator_user_id"`
	CurrentState    string       `json:"current_state"`
	OverallScore    string       `json:"overall_score"`
	SummaryMd       string       `json:"summary_md"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) error {
	_, err := q.db.ExecContext(ctx, createEvaluation,
		arg.ID,
		arg.SessionID,
		arg.TurnID,
		arg.RubricID,
		arg.EvaluatorUserID,
		arg.CurrentState,
		arg.OverallScore,
		arg.SummaryMd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAllEvaluationsBySessionID = `-- name: GetAllEvaluationsBySessionID :many
SELECT overall_score, summary_md
FROM evaluations
WHERE session_id = $1 and soft_delete = false
`

type GetAllEvaluationsBySessionIDRow struct {
	OverallScore string `json:"overall_score"`
	SummaryMd    string `json:"summary_md"`
}

func (q *Queries) GetAllEvaluationsBySessionID(ctx context.Context, sessionID uuid.UUID) ([]GetAllEvaluationsBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvaluationsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllEvaluationsBySessionIDRow{}
	for rows.Next() {
		var i GetAllEvaluationsBySessionIDRow
		if err := rows.Scan(&i.OverallScore, &i.SummaryMd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
