// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_state.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInterviewState = `-- name: CreateInterviewState :exec
INSERT INTO interview_states (
    id,
    session_id,
    phrase_type,
    started_at
) VALUES (
    $1, $2, $3, $4
)
`

type CreateInterviewStateParams struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	PhraseType string    `json:"phrase_type"`
	StartedAt  time.Time `json:"started_at"`
}

func (q *Queries) CreateInterviewState(ctx context.Context, arg CreateInterviewStateParams) error {
	_, err := q.db.ExecContext(ctx, createInterviewState,
		arg.ID,
		arg.SessionID,
		arg.PhraseType,
		arg.StartedAt,
	)
	return err
}

const getLastTurnIDInterviewStateByID = `-- name: GetLastTurnIDInterviewStateByID :one
SELECT last_turn_id
FROM interview_states
WHERE id = $1
`

func (q *Queries) GetLastTurnIDInterviewStateByID(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRowContext(ctx, getLastTurnIDInterviewStateByID, id)
	var last_turn_id uuid.NullUUID
	err := row.Scan(&last_turn_id)
	return last_turn_id, err
}

const updateEndedAtInterviewStateByID = `-- name: UpdateEndedAtInterviewStateByID :execrows
UPDATE interview_states
SET ended_at = $2, last_turn_id = $3
WHERE id = $1
`

type UpdateEndedAtInterviewStateByIDParams struct {
	ID         uuid.UUID     `json:"id"`
	EndedAt    sql.NullTime  `json:"ended_at"`
	LastTurnID uuid.NullUUID `json:"last_turn_id"`
}

func (q *Queries) UpdateEndedAtInterviewStateByID(ctx context.Context, arg UpdateEndedAtInterviewStateByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEndedAtInterviewStateByID, arg.ID, arg.EndedAt, arg.LastTurnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateIsEvaluatedInterviewStateByID = `-- name: UpdateIsEvaluatedInterviewStateByID :execrows
UPDATE interview_states
SET is_evaluated = $2
WHERE id = $1
`

type UpdateIsEvaluatedInterviewStateByIDParams struct {
	ID          uuid.UUID    `json:"id"`
	IsEvaluated sql.NullBool `json:"is_evaluated"`
}

func (q *Queries) UpdateIsEvaluatedInterviewStateByID(ctx context.Context, arg UpdateIsEvaluatedInterviewStateByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIsEvaluatedInterviewStateByID, arg.ID, arg.IsEvaluated)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLastTurnIDInterviewStateByID = `-- name: UpdateLastTurnIDInterviewStateByID :execrows
UPDATE interview_states
SET last_turn_id = $2
WHERE id = $1
`

type UpdateLastTurnIDInterviewStateByIDParams struct {
	ID         uuid.UUID     `json:"id"`
	LastTurnID uuid.NullUUID `json:"last_turn_id"`
}

func (q *Queries) UpdateLastTurnIDInterviewStateByID(ctx context.Context, arg UpdateLastTurnIDInterviewStateByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLastTurnIDInterviewStateByID, arg.ID, arg.LastTurnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
