// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_session.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkInterviewSessionExists = `-- name: CheckInterviewSessionExists :one
SELECT EXISTS (
    SELECT 1
    FROM interview_sessions
    WHERE id = $1
)
`

func (q *Queries) CheckInterviewSessionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkInterviewSessionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createInterviewSession = `-- name: CreateInterviewSession :exec
INSERT INTO interview_sessions (
    id,
    user_id,
    resume_id,
    position,
    modality,
    status,
    is_consent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateInterviewSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ResumeID  uuid.UUID `json:"resume_id"`
	Position  string    `json:"position"`
	Modality  string    `json:"modality"`
	Status    string    `json:"status"`
	IsConsent bool      `json:"is_consent"`
}

func (q *Queries) CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) error {
	_, err := q.db.ExecContext(ctx, createInterviewSession,
		arg.ID,
		arg.UserID,
		arg.ResumeID,
		arg.Position,
		arg.Modality,
		arg.Status,
		arg.IsConsent,
	)
	return err
}

const endInterviewSession = `-- name: EndInterviewSession :execrows
UPDATE interview_sessions
SET status = $2,
    ended_at = $3,
    overall_score = $4,
    summary_md = $5
WHERE id = $1
`

type EndInterviewSessionParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	EndedAt      sql.NullTime   `json:"ended_at"`
	OverallScore sql.NullString `json:"overall_score"`
	SummaryMd    sql.NullString `json:"summary_md"`
}

func (q *Queries) EndInterviewSession(ctx context.Context, arg EndInterviewSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endInterviewSession,
		arg.ID,
		arg.Status,
		arg.EndedAt,
		arg.OverallScore,
		arg.SummaryMd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInterviewSessionStatus = `-- name: UpdateInterviewSessionStatus :execrows
UPDATE interview_sessions
SET status = $2::VARCHAR(20),
    started_at = CASE WHEN $2 = 'on_going' AND started_at IS NULL THEN now() ELSE started_at END,
    ended_at   = CASE WHEN $2 IN ('aborted','cancelled','timed_out') THEN now() ELSE ended_at END
WHERE id = $1
`

type UpdateInterviewSessionStatusParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) UpdateInterviewSessionStatus(ctx context.Context, arg UpdateInterviewSessionStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInterviewSessionStatus, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
