// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: interview_turns.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createInterviewTurn = `-- name: CreateInterviewTurn :exec
INSERT INTO interview_turns (
    id,
    session_id,
    turn_no,
    actor,
    transcript_text,
    start_at,
    end_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateInterviewTurnParams struct {
	ID             uuid.UUID      `json:"id"`
	SessionID      uuid.UUID      `json:"session_id"`
	TurnNo         int32          `json:"turn_no"`
	Actor          string         `json:"actor"`
	TranscriptText sql.NullString `json:"transcript_text"`
	StartAt        string         `json:"start_at"`
	EndAt          string         `json:"end_at"`
}

func (q *Queries) CreateInterviewTurn(ctx context.Context, arg CreateInterviewTurnParams) error {
	_, err := q.db.ExecContext(ctx, createInterviewTurn,
		arg.ID,
		arg.SessionID,
		arg.TurnNo,
		arg.Actor,
		arg.TranscriptText,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const getMaxTurnNoBySessionID = `-- name: GetMaxTurnNoBySessionID :one
SELECT COALESCE(MAX(turn_no), 0) AS max_turn_no
FROM interview_turns
WHERE session_id = $1
`

func (q *Queries) GetMaxTurnNoBySessionID(ctx context.Context, sessionID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxTurnNoBySessionID, sessionID)
	var max_turn_no interface{}
	err := row.Scan(&max_turn_no)
	return max_turn_no, err
}
