// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_state.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInterviewState = `-- name: CreateInterviewState :exec
INSERT INTO interview_states (
    id,
    session_id,
    phrase_type,
    started_at
) VALUES (
    $1, $2, $3, $4
)
`

type CreateInterviewStateParams struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	PhraseType string    `json:"phrase_type"`
	StartedAt  time.Time `json:"started_at"`
}

func (q *Queries) CreateInterviewState(ctx context.Context, arg CreateInterviewStateParams) error {
	_, err := q.db.ExecContext(ctx, createInterviewState,
		arg.ID,
		arg.SessionID,
		arg.PhraseType,
		arg.StartedAt,
	)
	return err
}

const updateEndedAtInterviewStateByID = `-- name: UpdateEndedAtInterviewStateByID :execrows
UPDATE interview_states
SET phrase_type = $2,
    ended_at = $3
WHERE id = $1
`

type UpdateEndedAtInterviewStateByIDParams struct {
	ID         uuid.UUID    `json:"id"`
	PhraseType string       `json:"phrase_type"`
	EndedAt    sql.NullTime `json:"ended_at"`
}

func (q *Queries) UpdateEndedAtInterviewStateByID(ctx context.Context, arg UpdateEndedAtInterviewStateByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEndedAtInterviewStateByID, arg.ID, arg.PhraseType, arg.EndedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateIsEvaluatedInterviewStateByID = `-- name: UpdateIsEvaluatedInterviewStateByID :execrows
UPDATE interview_states
SET is_evaluated = $2
WHERE id = $1
`

type UpdateIsEvaluatedInterviewStateByIDParams struct {
	ID          uuid.UUID    `json:"id"`
	IsEvaluated sql.NullBool `json:"is_evaluated"`
}

func (q *Queries) UpdateIsEvaluatedInterviewStateByID(ctx context.Context, arg UpdateIsEvaluatedInterviewStateByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIsEvaluatedInterviewStateByID, arg.ID, arg.IsEvaluated)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
