// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phrase_rubric_scores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAllPhraseRubricScores = `-- name: CreateAllPhraseRubricScores :exec
INSERT INTO phrase_rubric_scores (
    id,
    phrase_evaluation_id,
    criterion_id,
    criterion_name,
    score,
    comment_md
)
SELECT 
    unnest($1::uuid[]) as id,
    unnest($2::uuid[]) as phrase_evaluation_id,
    unnest($3::uuid[]) as criterion_id,
    unnest($4::text[]) as criterion_name,
    unnest($5::float[]) as score,
    unnest($6::text[]) as comment_md
`

type CreateAllPhraseRubricScoresParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
	Column3 []uuid.UUID `json:"column_3"`
	Column4 []string    `json:"column_4"`
	Column5 []float64   `json:"column_5"`
	Column6 []string    `json:"column_6"`
}

func (q *Queries) CreateAllPhraseRubricScores(ctx context.Context, arg CreateAllPhraseRubricScoresParams) error {
	_, err := q.db.ExecContext(ctx, createAllPhraseRubricScores,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
		pq.Array(arg.Column6),
	)
	return err
}
