// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phrase_evaluations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPhraseEvaluation = `-- name: CreatePhraseEvaluation :exec
INSERT INTO phrase_evaluations (
    id,
    session_id,
    state_id,
    state_name,
    overall_score
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreatePhraseEvaluationParams struct {
	ID           uuid.UUID `json:"id"`
	SessionID    uuid.UUID `json:"session_id"`
	StateID      uuid.UUID `json:"state_id"`
	StateName    string    `json:"state_name"`
	OverallScore float64   `json:"overall_score"`
}

func (q *Queries) CreatePhraseEvaluation(ctx context.Context, arg CreatePhraseEvaluationParams) error {
	_, err := q.db.ExecContext(ctx, createPhraseEvaluation,
		arg.ID,
		arg.SessionID,
		arg.StateID,
		arg.StateName,
		arg.OverallScore,
	)
	return err
}
