// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	CheckInterviewSessionExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckIsDefaultResumeExistsByUserID(ctx context.Context, userID uuid.UUID) (bool, error)
	CheckUserExistsByProviderID(ctx context.Context, arg CheckUserExistsByProviderIDParams) (bool, error)
	CountInterviewSessionsByUserID(ctx context.Context, arg CountInterviewSessionsByUserIDParams) (int64, error)
	CreateAdminIssueCategory(ctx context.Context, arg CreateAdminIssueCategoryParams) error
	CreateAllPhraseRubricScores(ctx context.Context, arg CreateAllPhraseRubricScoresParams) error
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) error
	CreateEvaluationCriterion(ctx context.Context, arg CreateEvaluationCriterionParams) error
	CreateEvaluationScore(ctx context.Context, arg CreateEvaluationScoreParams) error
	CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) error
	CreateInterviewState(ctx context.Context, arg CreateInterviewStateParams) error
	CreateInterviewTurn(ctx context.Context, arg CreateInterviewTurnParams) error
	CreatePhraseEvaluation(ctx context.Context, arg CreatePhraseEvaluationParams) error
	CreateResume(ctx context.Context, arg CreateResumeParams) error
	CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) (int64, error)
	CreateUserIssueReport(ctx context.Context, arg CreateUserIssueReportParams) (CreateUserIssueReportRow, error)
	CreateUserTurnImprovement(ctx context.Context, arg CreateUserTurnImprovementParams) error
	CreateUserWithProvider(ctx context.Context, arg CreateUserWithProviderParams) error
	DeleteUserInterviewSessionByID(ctx context.Context, arg DeleteUserInterviewSessionByIDParams) (int64, error)
	EndInterviewSession(ctx context.Context, arg EndInterviewSessionParams) (int64, error)
	FlagIsScoreEvaluated(ctx context.Context, id uuid.UUID) (int64, error)
	GetAllEvaluationsBySessionID(ctx context.Context, sessionID uuid.UUID) ([]GetAllEvaluationsBySessionIDRow, error)
	GetAuthSessionByID(ctx context.Context, id uuid.UUID) (AuthSessions, error)
	GetChatHistoryBySessionID(ctx context.Context, arg GetChatHistoryBySessionIDParams) ([]GetChatHistoryBySessionIDRow, error)
	GetChatHistoryBySessionIDWithCursor(ctx context.Context, arg GetChatHistoryBySessionIDWithCursorParams) ([]GetChatHistoryBySessionIDWithCursorRow, error)
	GetChatHistoryBySessionIDWithEvaluation(ctx context.Context, arg GetChatHistoryBySessionIDWithEvaluationParams) ([]GetChatHistoryBySessionIDWithEvaluationRow, error)
	GetDefaultResumeByUserID(ctx context.Context, userID uuid.UUID) (Resumes, error)
	GetEvaluationSummaryJsonBySessionAndState(ctx context.Context, arg GetEvaluationSummaryJsonBySessionAndStateParams) (json.RawMessage, error)
	GetInterviewSessionInformationByID(ctx context.Context, id uuid.UUID) (GetInterviewSessionInformationByIDRow, error)
	GetInterviewSessionStatusByID(ctx context.Context, id uuid.UUID) (string, error)
	GetInterviewerLastMessage(ctx context.Context, sessionID uuid.UUID) (GetInterviewerLastMessageRow, error)
	GetIssueCategoryIfExists(ctx context.Context, id uuid.UUID) (GetIssueCategoryIfExistsRow, error)
	GetLastTurnIDInterviewStateByID(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error)
	GetLastUserTurnIDBySessionIDAndCurrentState(ctx context.Context, arg GetLastUserTurnIDBySessionIDAndCurrentStateParams) (uuid.UUID, error)
	GetMaxTurnNoBySessionID(ctx context.Context, sessionID uuid.UUID) (interface{}, error)
	GetPhraseEvaluationsWithCriteriaBySessionID(ctx context.Context, sessionID uuid.UUID) ([]GetPhraseEvaluationsWithCriteriaBySessionIDRow, error)
	GetResumeByID(ctx context.Context, id uuid.UUID) (Resumes, error)
	GetRubricWithCriteriaByName(ctx context.Context, arg GetRubricWithCriteriaByNameParams) ([]GetRubricWithCriteriaByNameRow, error)
	GetSessionState(ctx context.Context, id uuid.UUID) (GetSessionStateRow, error)
	GetUnprocessedInterviewStatesBySessionID(ctx context.Context, sessionID uuid.UUID) ([]GetUnprocessedInterviewStatesBySessionIDRow, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (Users, error)
	GetUserIssueReportUserIDAndStatusByID(ctx context.Context, id uuid.UUID) (GetUserIssueReportUserIDAndStatusByIDRow, error)
	IsLastUserStateTurnScored(ctx context.Context, arg IsLastUserStateTurnScoredParams) (sql.NullBool, error)
	ListAllResumesFileNameByUserID(ctx context.Context, userID uuid.UUID) ([]string, error)
	ListAllRubricsAndCriteria(ctx context.Context, versionLabel string) ([]ListAllRubricsAndCriteriaRow, error)
	ListFinalizingInterviewSessionByUserID(ctx context.Context, userID uuid.UUID) ([]ListFinalizingInterviewSessionByUserIDRow, error)
	ListInterviewSessionsByUserIDFirstPage(ctx context.Context, arg ListInterviewSessionsByUserIDFirstPageParams) ([]ListInterviewSessionsByUserIDFirstPageRow, error)
	ListInterviewSessionsByUserIDWithCursor(ctx context.Context, arg ListInterviewSessionsByUserIDWithCursorParams) ([]ListInterviewSessionsByUserIDWithCursorRow, error)
	ListInterviewSessionsByUserIDWithJumpPagination(ctx context.Context, arg ListInterviewSessionsByUserIDWithJumpPaginationParams) ([]ListInterviewSessionsByUserIDWithJumpPaginationRow, error)
	ListIssueCategories(ctx context.Context) ([]ListIssueCategoriesRow, error)
	ListResumeByUserIDFirstPage(ctx context.Context, userID uuid.UUID) ([]Resumes, error)
	ListResumeByUserIDPaginated(ctx context.Context, arg ListResumeByUserIDPaginatedParams) ([]Resumes, error)
	RevokeAuthSessionByID(ctx context.Context, id uuid.UUID) error
	SetDefaultResume(ctx context.Context, id uuid.UUID) error
	UnsetDefaultResume(ctx context.Context, id uuid.UUID) error
	UpdateCurrentStateAndIDInterviewSessionByID(ctx context.Context, arg UpdateCurrentStateAndIDInterviewSessionByIDParams) (int64, error)
	UpdateEndedAtInterviewStateByID(ctx context.Context, arg UpdateEndedAtInterviewStateByIDParams) (int64, error)
	UpdateFinalizeStatusInterviewSessionByID(ctx context.Context, arg UpdateFinalizeStatusInterviewSessionByIDParams) (int64, error)
	UpdateInterviewSessionStatus(ctx context.Context, arg UpdateInterviewSessionStatusParams) (int64, error)
	UpdateIsEvaluatedInterviewStateByID(ctx context.Context, arg UpdateIsEvaluatedInterviewStateByIDParams) (int64, error)
	UpdateIsStartedConversationSession(ctx context.Context, arg UpdateIsStartedConversationSessionParams) (int64, error)
	UpdateLastTurnIDInterviewStateByID(ctx context.Context, arg UpdateLastTurnIDInterviewStateByIDParams) (int64, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (int64, error)
	UpdateStartedAtInterviewSession(ctx context.Context, arg UpdateStartedAtInterviewSessionParams) (int64, error)
	UpdateUserLoginInfo(ctx context.Context, arg UpdateUserLoginInfoParams) error
}

var _ Querier = (*Queries)(nil)
