// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    last_active,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateSessionParams struct {
	ID               uuid.UUID    `json:"id"`
	UserID           uuid.UUID    `json:"user_id"`
	RefreshTokenHash string       `json:"refresh_token_hash"`
	UserAgent        string       `json:"user_agent"`
	IpAddress        string       `json:"ip_address"`
	LastActive       sql.NullTime `json:"last_active"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.LastActive,
		arg.ExpiresAt,
	)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, login_time, last_active, expires_at, is_revoked, created_at, updated_at FROM sessions
WHERE id = $1 AND is_revoked = false
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Sessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.LoginTime,
		&i.LastActive,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET is_revoked = true
WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByID, id)
	return err
}
