// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkUserExistsByProviderID = `-- name: CheckUserExistsByProviderID :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE provider_id = $1 AND provider = $2
)
`

type CheckUserExistsByProviderIDParams struct {
	ProviderID sql.NullString `json:"provider_id"`
	Provider   string         `json:"provider"`
}

func (q *Queries) CheckUserExistsByProviderID(ctx context.Context, arg CheckUserExistsByProviderIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserExistsByProviderID, arg.ProviderID, arg.Provider)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserWithProvider = `-- name: CreateUserWithProvider :exec
INSERT INTO users (
    id,
    email,
    full_name,
    profile_image,
    provider,
    provider_id,
    is_admin,
    is_suspended,
    last_login_at,
    last_login_ip,
    last_login_user_agent,
    locale
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type CreateUserWithProviderParams struct {
	ID                 uuid.UUID      `json:"id"`
	Email              string         `json:"email"`
	FullName           string         `json:"full_name"`
	ProfileImage       sql.NullString `json:"profile_image"`
	Provider           string         `json:"provider"`
	ProviderID         sql.NullString `json:"provider_id"`
	IsAdmin            sql.NullBool   `json:"is_admin"`
	IsSuspended        sql.NullBool   `json:"is_suspended"`
	LastLoginAt        sql.NullTime   `json:"last_login_at"`
	LastLoginIp        sql.NullString `json:"last_login_ip"`
	LastLoginUserAgent sql.NullString `json:"last_login_user_agent"`
	Locale             sql.NullString `json:"locale"`
}

func (q *Queries) CreateUserWithProvider(ctx context.Context, arg CreateUserWithProviderParams) error {
	_, err := q.db.ExecContext(ctx, createUserWithProvider,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.ProfileImage,
		arg.Provider,
		arg.ProviderID,
		arg.IsAdmin,
		arg.IsSuspended,
		arg.LastLoginAt,
		arg.LastLoginIp,
		arg.LastLoginUserAgent,
		arg.Locale,
	)
	return err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, email, full_name, is_admin, last_login_at, is_suspended, last_login_ip, last_login_user_agent, created_at, updated_at, provider, provider_id, profile_image, locale FROM users
WHERE provider_id = $1 AND provider = $2
LIMIT 1
`

type GetUserByProviderIDParams struct {
	ProviderID sql.NullString `json:"provider_id"`
	Provider   string         `json:"provider"`
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderID, arg.ProviderID, arg.Provider)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.IsSuspended,
		&i.LastLoginIp,
		&i.LastLoginUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.ProfileImage,
		&i.Locale,
	)
	return i, err
}

const updateUserLoginInfo = `-- name: UpdateUserLoginInfo :exec
UPDATE users
SET last_login_at = NOW(),
    last_login_ip = $2,
    last_login_user_agent = $3,
    locale = $4
WHERE id = $1
`

type UpdateUserLoginInfoParams struct {
	ID                 uuid.UUID      `json:"id"`
	LastLoginIp        sql.NullString `json:"last_login_ip"`
	LastLoginUserAgent sql.NullString `json:"last_login_user_agent"`
	Locale             sql.NullString `json:"locale"`
}

func (q *Queries) UpdateUserLoginInfo(ctx context.Context, arg UpdateUserLoginInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLoginInfo,
		arg.ID,
		arg.LastLoginIp,
		arg.LastLoginUserAgent,
		arg.Locale,
	)
	return err
}
