// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_turn_improvements.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserTurnImprovement = `-- name: CreateUserTurnImprovement :exec
INSERT INTO user_turn_improvements (
    id,
    interview_turn_id,
    corrected_sentence,
    model_version,
    created_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateUserTurnImprovementParams struct {
	ID                uuid.UUID `json:"id"`
	InterviewTurnID   uuid.UUID `json:"interview_turn_id"`
	CorrectedSentence string    `json:"corrected_sentence"`
	ModelVersion      string    `json:"model_version"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateUserTurnImprovement(ctx context.Context, arg CreateUserTurnImprovementParams) error {
	_, err := q.db.ExecContext(ctx, createUserTurnImprovement,
		arg.ID,
		arg.InterviewTurnID,
		arg.CorrectedSentence,
		arg.ModelVersion,
		arg.CreatedAt,
	)
	return err
}
