// Code generated by mockery v2.53.3. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "gitlab.com/interview-simulation/interview-backend-server/internal/infras/database"

	time "time"
)

// MockRedisClient is an autogenerated mock type for the RedisClient type
type MockRedisClient struct {
	mock.Mock
}

type MockRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisClient) EXPECT() *MockRedisClient_Expecter {
	return &MockRedisClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, keys
func (_m *MockRedisClient) Delete(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRedisClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockRedisClient_Expecter) Delete(ctx interface{}, keys ...interface{}) *MockRedisClient_Delete_Call {
	return &MockRedisClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockRedisClient_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockRedisClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockRedisClient_Delete_Call) Return(_a0 error) *MockRedisClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Delete_Call) RunAndReturn(run func(context.Context, ...string) error) *MockRedisClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockRedisClient) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisClient_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRedisClient_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Exists(ctx interface{}, key interface{}) *MockRedisClient_Exists_Call {
	return &MockRedisClient_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockRedisClient_Exists_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisClient_Exists_Call) Return(_a0 bool, _a1 error) *MockRedisClient_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisClient_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRedisClient_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Expire provides a mock function with given fields: ctx, key, duration
func (_m *MockRedisClient) Expire(ctx context.Context, key string, duration time.Duration) error {
	ret := _m.Called(ctx, key, duration)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, key, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type MockRedisClient_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - duration time.Duration
func (_e *MockRedisClient_Expecter) Expire(ctx interface{}, key interface{}, duration interface{}) *MockRedisClient_Expire_Call {
	return &MockRedisClient_Expire_Call{Call: _e.mock.On("Expire", ctx, key, duration)}
}

func (_c *MockRedisClient_Expire_Call) Run(run func(ctx context.Context, key string, duration time.Duration)) *MockRedisClient_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockRedisClient_Expire_Call) Return(_a0 error) *MockRedisClient_Expire_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Expire_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockRedisClient_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockRedisClient) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Get(ctx interface{}, key interface{}) *MockRedisClient_Get_Call {
	return &MockRedisClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRedisClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisClient_Get_Call) Return(_a0 string, _a1 error) *MockRedisClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisClient_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRedisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HDel provides a mock function with given fields: ctx, key, fields
func (_m *MockRedisClient) HDel(ctx context.Context, key string, fields ...string) error {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HDel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = rf(ctx, key, fields...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_HDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HDel'
type MockRedisClient_HDel_Call struct {
	*mock.Call
}

// HDel is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fields ...string
func (_e *MockRedisClient_Expecter) HDel(ctx interface{}, key interface{}, fields ...interface{}) *MockRedisClient_HDel_Call {
	return &MockRedisClient_HDel_Call{Call: _e.mock.On("HDel",
		append([]interface{}{ctx, key}, fields...)...)}
}

func (_c *MockRedisClient_HDel_Call) Run(run func(ctx context.Context, key string, fields ...string)) *MockRedisClient_HDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockRedisClient_HDel_Call) Return(_a0 error) *MockRedisClient_HDel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_HDel_Call) RunAndReturn(run func(context.Context, string, ...string) error) *MockRedisClient_HDel_Call {
	_c.Call.Return(run)
	return _c
}

// HGet provides a mock function with given fields: ctx, key, field
func (_m *MockRedisClient) HGet(ctx context.Context, key string, field string) (string, error) {
	ret := _m.Called(ctx, key, field)

	if len(ret) == 0 {
		panic("no return value specified for HGet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, key, field)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, key, field)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisClient_HGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HGet'
type MockRedisClient_HGet_Call struct {
	*mock.Call
}

// HGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - field string
func (_e *MockRedisClient_Expecter) HGet(ctx interface{}, key interface{}, field interface{}) *MockRedisClient_HGet_Call {
	return &MockRedisClient_HGet_Call{Call: _e.mock.On("HGet", ctx, key, field)}
}

func (_c *MockRedisClient_HGet_Call) Run(run func(ctx context.Context, key string, field string)) *MockRedisClient_HGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRedisClient_HGet_Call) Return(_a0 string, _a1 error) *MockRedisClient_HGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisClient_HGet_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockRedisClient_HGet_Call {
	_c.Call.Return(run)
	return _c
}

// HGetAll provides a mock function with given fields: ctx, key
func (_m *MockRedisClient) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for HGetAll")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisClient_HGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HGetAll'
type MockRedisClient_HGetAll_Call struct {
	*mock.Call
}

// HGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) HGetAll(ctx interface{}, key interface{}) *MockRedisClient_HGetAll_Call {
	return &MockRedisClient_HGetAll_Call{Call: _e.mock.On("HGetAll", ctx, key)}
}

func (_c *MockRedisClient_HGetAll_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_HGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisClient_HGetAll_Call) Return(_a0 map[string]string, _a1 error) *MockRedisClient_HGetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisClient_HGetAll_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *MockRedisClient_HGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// HSet provides a mock function with given fields: ctx, key, values
func (_m *MockRedisClient) HSet(ctx context.Context, key string, values ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, values...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, key, values...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_HSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HSet'
type MockRedisClient_HSet_Call struct {
	*mock.Call
}

// HSet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - values ...interface{}
func (_e *MockRedisClient_Expecter) HSet(ctx interface{}, key interface{}, values ...interface{}) *MockRedisClient_HSet_Call {
	return &MockRedisClient_HSet_Call{Call: _e.mock.On("HSet",
		append([]interface{}{ctx, key}, values...)...)}
}

func (_c *MockRedisClient_HSet_Call) Run(run func(ctx context.Context, key string, values ...interface{})) *MockRedisClient_HSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockRedisClient_HSet_Call) Return(_a0 error) *MockRedisClient_HSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_HSet_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *MockRedisClient_HSet_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, payload
func (_m *MockRedisClient) Set(ctx context.Context, payload database.RedisPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.RedisPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - payload database.RedisPayload
func (_e *MockRedisClient_Expecter) Set(ctx interface{}, payload interface{}) *MockRedisClient_Set_Call {
	return &MockRedisClient_Set_Call{Call: _e.mock.On("Set", ctx, payload)}
}

func (_c *MockRedisClient_Set_Call) Run(run func(ctx context.Context, payload database.RedisPayload)) *MockRedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.RedisPayload))
	})
	return _c
}

func (_c *MockRedisClient_Set_Call) Return(_a0 error) *MockRedisClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Set_Call) RunAndReturn(run func(context.Context, database.RedisPayload) error) *MockRedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisClient creates a new instance of MockRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisClient {
	mock := &MockRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
