// Code generated by mockery v2.53.3. DO NOT EDIT.

package middleware

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
	middleware "gitlab.com/interview-simulation/interview-backend-server/internal/middleware"
)

// MockAuthContext is an autogenerated mock type for the AuthContext type
type MockAuthContext struct {
	mock.Mock
}

type MockAuthContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthContext) EXPECT() *MockAuthContext_Expecter {
	return &MockAuthContext_Expecter{mock: &_m.Mock}
}

// ExtractAuthContext provides a mock function with given fields: ctx
func (_m *MockAuthContext) ExtractAuthContext(ctx *gin.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExtractAuthContext")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthContext_ExtractAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractAuthContext'
type MockAuthContext_ExtractAuthContext_Call struct {
	*mock.Call
}

// ExtractAuthContext is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockAuthContext_Expecter) ExtractAuthContext(ctx interface{}) *MockAuthContext_ExtractAuthContext_Call {
	return &MockAuthContext_ExtractAuthContext_Call{Call: _e.mock.On("ExtractAuthContext", ctx)}
}

func (_c *MockAuthContext_ExtractAuthContext_Call) Run(run func(ctx *gin.Context)) *MockAuthContext_ExtractAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockAuthContext_ExtractAuthContext_Call) Return(_a0 context.Context, _a1 error) *MockAuthContext_ExtractAuthContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthContext_ExtractAuthContext_Call) RunAndReturn(run func(*gin.Context) (context.Context, error)) *MockAuthContext_ExtractAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthContext provides a mock function with given fields: ctx
func (_m *MockAuthContext) GetAuthContext(ctx context.Context) (*middleware.AuthPayload, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthContext")
	}

	var r0 *middleware.AuthPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*middleware.AuthPayload, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *middleware.AuthPayload); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*middleware.AuthPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthContext_GetAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthContext'
type MockAuthContext_GetAuthContext_Call struct {
	*mock.Call
}

// GetAuthContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthContext_Expecter) GetAuthContext(ctx interface{}) *MockAuthContext_GetAuthContext_Call {
	return &MockAuthContext_GetAuthContext_Call{Call: _e.mock.On("GetAuthContext", ctx)}
}

func (_c *MockAuthContext_GetAuthContext_Call) Run(run func(ctx context.Context)) *MockAuthContext_GetAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthContext_GetAuthContext_Call) Return(_a0 *middleware.AuthPayload, _a1 error) *MockAuthContext_GetAuthContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthContext_GetAuthContext_Call) RunAndReturn(run func(context.Context) (*middleware.AuthPayload, error)) *MockAuthContext_GetAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthContext creates a new instance of MockAuthContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthContext {
	mock := &MockAuthContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
