// Code generated by mockery v2.53.3. DO NOT EDIT.

package websocket

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	websocket "gitlab.com/interview-simulation/interview-backend-server/internal/infras/websocket"
)

// MockWebSocketClientCallbacks is an autogenerated mock type for the WebSocketClientCallbacks type
type MockWebSocketClientCallbacks struct {
	mock.Mock
}

type MockWebSocketClientCallbacks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebSocketClientCallbacks) EXPECT() *MockWebSocketClientCallbacks_Expecter {
	return &MockWebSocketClientCallbacks_Expecter{mock: &_m.Mock}
}

// OnConnectionEstablished provides a mock function with given fields: ctx, sessionID
func (_m *MockWebSocketClientCallbacks) OnConnectionEstablished(ctx context.Context, sessionID string) {
	_m.Called(ctx, sessionID)
}

// MockWebSocketClientCallbacks_OnConnectionEstablished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionEstablished'
type MockWebSocketClientCallbacks_OnConnectionEstablished_Call struct {
	*mock.Call
}

// OnConnectionEstablished is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockWebSocketClientCallbacks_Expecter) OnConnectionEstablished(ctx interface{}, sessionID interface{}) *MockWebSocketClientCallbacks_OnConnectionEstablished_Call {
	return &MockWebSocketClientCallbacks_OnConnectionEstablished_Call{Call: _e.mock.On("OnConnectionEstablished", ctx, sessionID)}
}

func (_c *MockWebSocketClientCallbacks_OnConnectionEstablished_Call) Run(run func(ctx context.Context, sessionID string)) *MockWebSocketClientCallbacks_OnConnectionEstablished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnConnectionEstablished_Call) Return() *MockWebSocketClientCallbacks_OnConnectionEstablished_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnConnectionEstablished_Call) RunAndReturn(run func(context.Context, string)) *MockWebSocketClientCallbacks_OnConnectionEstablished_Call {
	_c.Run(run)
	return _c
}

// OnDisconnect provides a mock function with given fields: ctx, sessionID
func (_m *MockWebSocketClientCallbacks) OnDisconnect(ctx context.Context, sessionID string) {
	_m.Called(ctx, sessionID)
}

// MockWebSocketClientCallbacks_OnDisconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDisconnect'
type MockWebSocketClientCallbacks_OnDisconnect_Call struct {
	*mock.Call
}

// OnDisconnect is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockWebSocketClientCallbacks_Expecter) OnDisconnect(ctx interface{}, sessionID interface{}) *MockWebSocketClientCallbacks_OnDisconnect_Call {
	return &MockWebSocketClientCallbacks_OnDisconnect_Call{Call: _e.mock.On("OnDisconnect", ctx, sessionID)}
}

func (_c *MockWebSocketClientCallbacks_OnDisconnect_Call) Run(run func(ctx context.Context, sessionID string)) *MockWebSocketClientCallbacks_OnDisconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnDisconnect_Call) Return() *MockWebSocketClientCallbacks_OnDisconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnDisconnect_Call) RunAndReturn(run func(context.Context, string)) *MockWebSocketClientCallbacks_OnDisconnect_Call {
	_c.Run(run)
	return _c
}

// OnInterviewCompleted provides a mock function with given fields: ctx, req
func (_m *MockWebSocketClientCallbacks) OnInterviewCompleted(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID) {
	_m.Called(ctx, req)
}

// MockWebSocketClientCallbacks_OnInterviewCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInterviewCompleted'
type MockWebSocketClientCallbacks_OnInterviewCompleted_Call struct {
	*mock.Call
}

// OnInterviewCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - req websocket.MsgInterviewTypeAndSessionID
func (_e *MockWebSocketClientCallbacks_Expecter) OnInterviewCompleted(ctx interface{}, req interface{}) *MockWebSocketClientCallbacks_OnInterviewCompleted_Call {
	return &MockWebSocketClientCallbacks_OnInterviewCompleted_Call{Call: _e.mock.On("OnInterviewCompleted", ctx, req)}
}

func (_c *MockWebSocketClientCallbacks_OnInterviewCompleted_Call) Run(run func(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(websocket.MsgInterviewTypeAndSessionID))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewCompleted_Call) Return() *MockWebSocketClientCallbacks_OnInterviewCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewCompleted_Call) RunAndReturn(run func(context.Context, websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewCompleted_Call {
	_c.Run(run)
	return _c
}

// OnInterviewTurnEnd provides a mock function with given fields: ctx, req
func (_m *MockWebSocketClientCallbacks) OnInterviewTurnEnd(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID) {
	_m.Called(ctx, req)
}

// MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInterviewTurnEnd'
type MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call struct {
	*mock.Call
}

// OnInterviewTurnEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - req websocket.MsgInterviewTypeAndSessionID
func (_e *MockWebSocketClientCallbacks_Expecter) OnInterviewTurnEnd(ctx interface{}, req interface{}) *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call {
	return &MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call{Call: _e.mock.On("OnInterviewTurnEnd", ctx, req)}
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call) Run(run func(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(websocket.MsgInterviewTypeAndSessionID))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call) Return() *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call) RunAndReturn(run func(context.Context, websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewTurnEnd_Call {
	_c.Run(run)
	return _c
}

// OnInterviewTurnStart provides a mock function with given fields: ctx, req
func (_m *MockWebSocketClientCallbacks) OnInterviewTurnStart(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID) {
	_m.Called(ctx, req)
}

// MockWebSocketClientCallbacks_OnInterviewTurnStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInterviewTurnStart'
type MockWebSocketClientCallbacks_OnInterviewTurnStart_Call struct {
	*mock.Call
}

// OnInterviewTurnStart is a helper method to define mock.On call
//   - ctx context.Context
//   - req websocket.MsgInterviewTypeAndSessionID
func (_e *MockWebSocketClientCallbacks_Expecter) OnInterviewTurnStart(ctx interface{}, req interface{}) *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call {
	return &MockWebSocketClientCallbacks_OnInterviewTurnStart_Call{Call: _e.mock.On("OnInterviewTurnStart", ctx, req)}
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call) Run(run func(ctx context.Context, req websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(websocket.MsgInterviewTypeAndSessionID))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call) Return() *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call) RunAndReturn(run func(context.Context, websocket.MsgInterviewTypeAndSessionID)) *MockWebSocketClientCallbacks_OnInterviewTurnStart_Call {
	_c.Run(run)
	return _c
}

// OnInterviewerAudioChunk provides a mock function with given fields: ctx, data
func (_m *MockWebSocketClientCallbacks) OnInterviewerAudioChunk(ctx context.Context, data []byte) {
	_m.Called(ctx, data)
}

// MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInterviewerAudioChunk'
type MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call struct {
	*mock.Call
}

// OnInterviewerAudioChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockWebSocketClientCallbacks_Expecter) OnInterviewerAudioChunk(ctx interface{}, data interface{}) *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call {
	return &MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call{Call: _e.mock.On("OnInterviewerAudioChunk", ctx, data)}
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call) Run(run func(ctx context.Context, data []byte)) *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call) Return() *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call) RunAndReturn(run func(context.Context, []byte)) *MockWebSocketClientCallbacks_OnInterviewerAudioChunk_Call {
	_c.Run(run)
	return _c
}

// OnInterviewerResp provides a mock function with given fields: ctx, req
func (_m *MockWebSocketClientCallbacks) OnInterviewerResp(ctx context.Context, req websocket.MsgInterviewerResp) {
	_m.Called(ctx, req)
}

// MockWebSocketClientCallbacks_OnInterviewerResp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInterviewerResp'
type MockWebSocketClientCallbacks_OnInterviewerResp_Call struct {
	*mock.Call
}

// OnInterviewerResp is a helper method to define mock.On call
//   - ctx context.Context
//   - req websocket.MsgInterviewerResp
func (_e *MockWebSocketClientCallbacks_Expecter) OnInterviewerResp(ctx interface{}, req interface{}) *MockWebSocketClientCallbacks_OnInterviewerResp_Call {
	return &MockWebSocketClientCallbacks_OnInterviewerResp_Call{Call: _e.mock.On("OnInterviewerResp", ctx, req)}
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerResp_Call) Run(run func(ctx context.Context, req websocket.MsgInterviewerResp)) *MockWebSocketClientCallbacks_OnInterviewerResp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(websocket.MsgInterviewerResp))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerResp_Call) Return() *MockWebSocketClientCallbacks_OnInterviewerResp_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnInterviewerResp_Call) RunAndReturn(run func(context.Context, websocket.MsgInterviewerResp)) *MockWebSocketClientCallbacks_OnInterviewerResp_Call {
	_c.Run(run)
	return _c
}

// OnUserFullTranscript provides a mock function with given fields: ctx, req
func (_m *MockWebSocketClientCallbacks) OnUserFullTranscript(ctx context.Context, req websocket.MsgUserFullTranscript) {
	_m.Called(ctx, req)
}

// MockWebSocketClientCallbacks_OnUserFullTranscript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnUserFullTranscript'
type MockWebSocketClientCallbacks_OnUserFullTranscript_Call struct {
	*mock.Call
}

// OnUserFullTranscript is a helper method to define mock.On call
//   - ctx context.Context
//   - req websocket.MsgUserFullTranscript
func (_e *MockWebSocketClientCallbacks_Expecter) OnUserFullTranscript(ctx interface{}, req interface{}) *MockWebSocketClientCallbacks_OnUserFullTranscript_Call {
	return &MockWebSocketClientCallbacks_OnUserFullTranscript_Call{Call: _e.mock.On("OnUserFullTranscript", ctx, req)}
}

func (_c *MockWebSocketClientCallbacks_OnUserFullTranscript_Call) Run(run func(ctx context.Context, req websocket.MsgUserFullTranscript)) *MockWebSocketClientCallbacks_OnUserFullTranscript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(websocket.MsgUserFullTranscript))
	})
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnUserFullTranscript_Call) Return() *MockWebSocketClientCallbacks_OnUserFullTranscript_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketClientCallbacks_OnUserFullTranscript_Call) RunAndReturn(run func(context.Context, websocket.MsgUserFullTranscript)) *MockWebSocketClientCallbacks_OnUserFullTranscript_Call {
	_c.Run(run)
	return _c
}

// NewMockWebSocketClientCallbacks creates a new instance of MockWebSocketClientCallbacks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebSocketClientCallbacks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebSocketClientCallbacks {
	mock := &MockWebSocketClientCallbacks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
