// Code generated by mockery v2.53.3. DO NOT EDIT.

package websocket

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	websocket "gitlab.com/interview-simulation/interview-backend-server/internal/infras/websocket"
)

// MockWebSocketServerCallbacks is an autogenerated mock type for the WebSocketServerCallbacks type
type MockWebSocketServerCallbacks struct {
	mock.Mock
}

type MockWebSocketServerCallbacks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebSocketServerCallbacks) EXPECT() *MockWebSocketServerCallbacks_Expecter {
	return &MockWebSocketServerCallbacks_Expecter{mock: &_m.Mock}
}

// handleAudioBinaryMessage provides a mock function with given fields: ctx, client, payload
func (_m *MockWebSocketServerCallbacks) handleAudioBinaryMessage(ctx context.Context, client *websocket.Client, payload []byte) {
	_m.Called(ctx, client, payload)
}

// MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handleAudioBinaryMessage'
type MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call struct {
	*mock.Call
}

// handleAudioBinaryMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - client *websocket.Client
//   - payload []byte
func (_e *MockWebSocketServerCallbacks_Expecter) handleAudioBinaryMessage(ctx interface{}, client interface{}, payload interface{}) *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call {
	return &MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call{Call: _e.mock.On("handleAudioBinaryMessage", ctx, client, payload)}
}

func (_c *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call) Run(run func(ctx context.Context, client *websocket.Client, payload []byte)) *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*websocket.Client), args[2].([]byte))
	})
	return _c
}

func (_c *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call) Return() *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call) RunAndReturn(run func(context.Context, *websocket.Client, []byte)) *MockWebSocketServerCallbacks_handleAudioBinaryMessage_Call {
	_c.Run(run)
	return _c
}

// sendMessageTypeError provides a mock function with given fields: ctx, client, payload
func (_m *MockWebSocketServerCallbacks) sendMessageTypeError(ctx context.Context, client *websocket.Client, payload []byte) {
	_m.Called(ctx, client, payload)
}

// MockWebSocketServerCallbacks_sendMessageTypeError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'sendMessageTypeError'
type MockWebSocketServerCallbacks_sendMessageTypeError_Call struct {
	*mock.Call
}

// sendMessageTypeError is a helper method to define mock.On call
//   - ctx context.Context
//   - client *websocket.Client
//   - payload []byte
func (_e *MockWebSocketServerCallbacks_Expecter) sendMessageTypeError(ctx interface{}, client interface{}, payload interface{}) *MockWebSocketServerCallbacks_sendMessageTypeError_Call {
	return &MockWebSocketServerCallbacks_sendMessageTypeError_Call{Call: _e.mock.On("sendMessageTypeError", ctx, client, payload)}
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeError_Call) Run(run func(ctx context.Context, client *websocket.Client, payload []byte)) *MockWebSocketServerCallbacks_sendMessageTypeError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*websocket.Client), args[2].([]byte))
	})
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeError_Call) Return() *MockWebSocketServerCallbacks_sendMessageTypeError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeError_Call) RunAndReturn(run func(context.Context, *websocket.Client, []byte)) *MockWebSocketServerCallbacks_sendMessageTypeError_Call {
	_c.Run(run)
	return _c
}

// sendMessageTypeSegmentEnd provides a mock function with given fields: ctx, client, payload
func (_m *MockWebSocketServerCallbacks) sendMessageTypeSegmentEnd(ctx context.Context, client *websocket.Client, payload []byte) {
	_m.Called(ctx, client, payload)
}

// MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'sendMessageTypeSegmentEnd'
type MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call struct {
	*mock.Call
}

// sendMessageTypeSegmentEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - client *websocket.Client
//   - payload []byte
func (_e *MockWebSocketServerCallbacks_Expecter) sendMessageTypeSegmentEnd(ctx interface{}, client interface{}, payload interface{}) *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call {
	return &MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call{Call: _e.mock.On("sendMessageTypeSegmentEnd", ctx, client, payload)}
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call) Run(run func(ctx context.Context, client *websocket.Client, payload []byte)) *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*websocket.Client), args[2].([]byte))
	})
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call) Return() *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call) RunAndReturn(run func(context.Context, *websocket.Client, []byte)) *MockWebSocketServerCallbacks_sendMessageTypeSegmentEnd_Call {
	_c.Run(run)
	return _c
}

// sendMessageTypeSegmentStart provides a mock function with given fields: ctx, client, payload
func (_m *MockWebSocketServerCallbacks) sendMessageTypeSegmentStart(ctx context.Context, client *websocket.Client, payload []byte) {
	_m.Called(ctx, client, payload)
}

// MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'sendMessageTypeSegmentStart'
type MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call struct {
	*mock.Call
}

// sendMessageTypeSegmentStart is a helper method to define mock.On call
//   - ctx context.Context
//   - client *websocket.Client
//   - payload []byte
func (_e *MockWebSocketServerCallbacks_Expecter) sendMessageTypeSegmentStart(ctx interface{}, client interface{}, payload interface{}) *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call {
	return &MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call{Call: _e.mock.On("sendMessageTypeSegmentStart", ctx, client, payload)}
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call) Run(run func(ctx context.Context, client *websocket.Client, payload []byte)) *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*websocket.Client), args[2].([]byte))
	})
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call) Return() *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call) RunAndReturn(run func(context.Context, *websocket.Client, []byte)) *MockWebSocketServerCallbacks_sendMessageTypeSegmentStart_Call {
	_c.Run(run)
	return _c
}

// NewMockWebSocketServerCallbacks creates a new instance of MockWebSocketServerCallbacks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebSocketServerCallbacks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebSocketServerCallbacks {
	mock := &MockWebSocketServerCallbacks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
