AppConfig:
  APP_PORT: 8080
  APP_ENV: uat
  API_HOST: localhost:8080
  CORS_ORIGINS:
    - https://interviewsai.org
    - https://www.interviewsai.org

DatabaseConfig:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: interview

RedisConfig:
  REDIS_HOST: redis_server
  REDIS_PORT: 6379
  REDIS_PASSWORD: password
  REDIS_DB_TEMP: 0
  REDIS_DB_QUEUE: 1

AuthConfig:
  ENCRYPTION_SECRET_KEY: 89fbb4ab29053d6b7c80077a57d55e05
  ACCESS_TOKEN_DURATION: 1m
  REFRESH_TOKEN_DURATION: 500m
  RESET_PASSWORD_TOKEN_DURATION: 15m
  TOKEN_GRACE_WINDOW: 1m
  COOKIE_DOMAIN: ""
  COOKIE_REJECT_HTTP: true

EmailConfig:
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 587
  EMAIL_USERNAME: chanagun.vir@gmail.com
  EMAIL_PASSWORD: lurv mvgp dqol yksu
  EMAIL_FROM: Interview Simulation <no-reply@interview-simulation.com>
  RESET_PASSWORD_URL: https://interviewsai.org/reset-password
  VERIFY_EMAIL_TOKEN_DURATION: 15m
  ENCRYPTION_SECRET_KEY: TD1FlWrtz1HsZSO5BMCZOIREhDsDK58p

AWSConfig:
  AWS_REGION: ap-southeast-1
  AWS_S3_BUCKET: interview-resume-sim
  AWS_S3_ACCESS_KEY: AKIA5JMSUNIPK43NUQNT
  AWS_S3_SECRET_ACCESS_KEY: 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
  AWS_S3_PRESIGNED_URL_EXPIRY: 5m

InterviewSessionConfig:
  INTERVIEW_AGENT_URL: http://agent-server:8000
  INTERVIEW_WEBSOCKET_PATH: ws://agent-server:8000/api/v1/ws/connect
  INTERVIEW_SESSION_TOKEN_TTL: 24h
  INTERVIEW_SESSION_DURATION: 24h
  ENCRYPTION_SECRET_KEY: IoZr3AnVFKukhezyzgILWSdxU477c6SL

OAuthConfig:
  OAUTH_GOOGLE_CLIENT_ID: 1029052407355-nkof2ieochg52i2kr16q11umesgeser3.apps.googleusercontent.com
  OAUTH_GOOGLE_CLIENT_SECRET: 1000000000000000000000000000000000000000
  OAUTH_GOOGLE_REDIRECT_URI: https://www.interviewsai.org/auth/google/callback
  OAUTH_FACEBOOK_CLIENT_ID: your_facebook_app_id
  OAUTH_FACEBOOK_CLIENT_SECRET: your_facebook_app_secret
  OAUTH_FACEBOOK_REDIRECT_URI: https://www.interviewsai.org/auth/facebook/callback