// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	uuid "github.com/google/uuid"
)

// MockAuthSessionRepository is an autogenerated mock type for the AuthSessionRepository type
type MockAuthSessionRepository struct {
	mock.Mock
}

type MockAuthSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthSessionRepository) EXPECT() *MockAuthSessionRepository_Expecter {
	return &MockAuthSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateAuthSession provides a mock function with given fields: ctx, req
func (_m *MockAuthSessionRepository) CreateAuthSession(ctx context.Context, req *db.CreateAuthSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateAuthSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthSessionRepository_CreateAuthSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthSession'
type MockAuthSessionRepository_CreateAuthSession_Call struct {
	*mock.Call
}

// CreateAuthSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateAuthSessionParams
func (_e *MockAuthSessionRepository_Expecter) CreateAuthSession(ctx interface{}, req interface{}) *MockAuthSessionRepository_CreateAuthSession_Call {
	return &MockAuthSessionRepository_CreateAuthSession_Call{Call: _e.mock.On("CreateAuthSession", ctx, req)}
}

func (_c *MockAuthSessionRepository_CreateAuthSession_Call) Run(run func(ctx context.Context, req *db.CreateAuthSessionParams)) *MockAuthSessionRepository_CreateAuthSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateAuthSessionParams))
	})
	return _c
}

func (_c *MockAuthSessionRepository_CreateAuthSession_Call) Return(_a0 error) *MockAuthSessionRepository_CreateAuthSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthSessionRepository_CreateAuthSession_Call) RunAndReturn(run func(context.Context, *db.CreateAuthSessionParams) error) *MockAuthSessionRepository_CreateAuthSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthSessionByID provides a mock function with given fields: ctx, id
func (_m *MockAuthSessionRepository) GetAuthSessionByID(ctx context.Context, id uuid.UUID) (*db.AuthSessions, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthSessionByID")
	}

	var r0 *db.AuthSessions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*db.AuthSessions, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *db.AuthSessions); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.AuthSessions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthSessionRepository_GetAuthSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthSessionByID'
type MockAuthSessionRepository_GetAuthSessionByID_Call struct {
	*mock.Call
}

// GetAuthSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthSessionRepository_Expecter) GetAuthSessionByID(ctx interface{}, id interface{}) *MockAuthSessionRepository_GetAuthSessionByID_Call {
	return &MockAuthSessionRepository_GetAuthSessionByID_Call{Call: _e.mock.On("GetAuthSessionByID", ctx, id)}
}

func (_c *MockAuthSessionRepository_GetAuthSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthSessionRepository_GetAuthSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthSessionRepository_GetAuthSessionByID_Call) Return(_a0 *db.AuthSessions, _a1 error) *MockAuthSessionRepository_GetAuthSessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthSessionRepository_GetAuthSessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*db.AuthSessions, error)) *MockAuthSessionRepository_GetAuthSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAuthSessionByID provides a mock function with given fields: ctx, id
func (_m *MockAuthSessionRepository) RevokeAuthSessionByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAuthSessionByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthSessionRepository_RevokeAuthSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAuthSessionByID'
type MockAuthSessionRepository_RevokeAuthSessionByID_Call struct {
	*mock.Call
}

// RevokeAuthSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthSessionRepository_Expecter) RevokeAuthSessionByID(ctx interface{}, id interface{}) *MockAuthSessionRepository_RevokeAuthSessionByID_Call {
	return &MockAuthSessionRepository_RevokeAuthSessionByID_Call{Call: _e.mock.On("RevokeAuthSessionByID", ctx, id)}
}

func (_c *MockAuthSessionRepository_RevokeAuthSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthSessionRepository_RevokeAuthSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthSessionRepository_RevokeAuthSessionByID_Call) Return(_a0 error) *MockAuthSessionRepository_RevokeAuthSessionByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthSessionRepository_RevokeAuthSessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAuthSessionRepository_RevokeAuthSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthSessionRepository creates a new instance of MockAuthSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthSessionRepository {
	mock := &MockAuthSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
