// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repositories "gitlab.com/interview-simulation/interview-backend-server/internal/repositories"
)

// MockEvaluationScoresRepository is an autogenerated mock type for the EvaluationScoresRepository type
type MockEvaluationScoresRepository struct {
	mock.Mock
}

type MockEvaluationScoresRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluationScoresRepository) EXPECT() *MockEvaluationScoresRepository_Expecter {
	return &MockEvaluationScoresRepository_Expecter{mock: &_m.Mock}
}

// CreateEvaluationWithCriteriaScoreTx provides a mock function with given fields: ctx, req
func (_m *MockEvaluationScoresRepository) CreateEvaluationWithCriteriaScoreTx(ctx context.Context, req *repositories.CreateEvaluationAndScoreTxReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvaluationWithCriteriaScoreTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CreateEvaluationAndScoreTxReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvaluationWithCriteriaScoreTx'
type MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call struct {
	*mock.Call
}

// CreateEvaluationWithCriteriaScoreTx is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CreateEvaluationAndScoreTxReq
func (_e *MockEvaluationScoresRepository_Expecter) CreateEvaluationWithCriteriaScoreTx(ctx interface{}, req interface{}) *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call {
	return &MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call{Call: _e.mock.On("CreateEvaluationWithCriteriaScoreTx", ctx, req)}
}

func (_c *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call) Run(run func(ctx context.Context, req *repositories.CreateEvaluationAndScoreTxReq)) *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.CreateEvaluationAndScoreTxReq))
	})
	return _c
}

func (_c *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call) Return(_a0 error) *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call) RunAndReturn(run func(context.Context, *repositories.CreateEvaluationAndScoreTxReq) error) *MockEvaluationScoresRepository_CreateEvaluationWithCriteriaScoreTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvaluationScoresRepository creates a new instance of MockEvaluationScoresRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluationScoresRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluationScoresRepository {
	mock := &MockEvaluationScoresRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
