// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	repositories "gitlab.com/interview-simulation/interview-backend-server/internal/repositories"

	uuid "github.com/google/uuid"
)

// MockInterviewSessionRepository is an autogenerated mock type for the InterviewSessionRepository type
type MockInterviewSessionRepository struct {
	mock.Mock
}

type MockInterviewSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewSessionRepository) EXPECT() *MockInterviewSessionRepository_Expecter {
	return &MockInterviewSessionRepository_Expecter{mock: &_m.Mock}
}

// CheckInterviewSessionExists provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionRepository) CheckInterviewSessionExists(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CheckInterviewSessionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_CheckInterviewSessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInterviewSessionExists'
type MockInterviewSessionRepository_CheckInterviewSessionExists_Call struct {
	*mock.Call
}

// CheckInterviewSessionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewSessionRepository_Expecter) CheckInterviewSessionExists(ctx interface{}, sessionID interface{}) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	return &MockInterviewSessionRepository_CheckInterviewSessionExists_Call{Call: _e.mock.On("CheckInterviewSessionExists", ctx, sessionID)}
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) Return(_a0 bool, _a1 error) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// CountInterviewSessionsByUserID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CountInterviewSessionsByUserID(ctx context.Context, req *db.CountInterviewSessionsByUserIDParams) (int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountInterviewSessionsByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CountInterviewSessionsByUserIDParams) (int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.CountInterviewSessionsByUserIDParams) int64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.CountInterviewSessionsByUserIDParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountInterviewSessionsByUserID'
type MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call struct {
	*mock.Call
}

// CountInterviewSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CountInterviewSessionsByUserIDParams
func (_e *MockInterviewSessionRepository_Expecter) CountInterviewSessionsByUserID(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call {
	return &MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call{Call: _e.mock.On("CountInterviewSessionsByUserID", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call) Run(run func(ctx context.Context, req *db.CountInterviewSessionsByUserIDParams)) *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CountInterviewSessionsByUserIDParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call) Return(_a0 int64, _a1 error) *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call) RunAndReturn(run func(context.Context, *db.CountInterviewSessionsByUserIDParams) (int64, error)) *MockInterviewSessionRepository_CountInterviewSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSession(ctx context.Context, req *db.CreateInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSession'
type MockInterviewSessionRepository_CreateInterviewSession_Call struct {
	*mock.Call
}

// CreateInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	return &MockInterviewSessionRepository_CreateInterviewSession_Call{Call: _e.mock.On("CreateInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) Run(run func(ctx context.Context, req *db.CreateInterviewSessionParams)) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) RunAndReturn(run func(context.Context, *db.CreateInterviewSessionParams) error) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithNewResumeTx provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSessionWithNewResumeTx(ctx context.Context, req *repositories.CreateInterviewSessionTxReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithNewResumeTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CreateInterviewSessionTxReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithNewResumeTx'
type MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithNewResumeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CreateInterviewSessionTxReq
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSessionWithNewResumeTx(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	return &MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call{Call: _e.mock.On("CreateInterviewSessionWithNewResumeTx", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Run(run func(ctx context.Context, req *repositories.CreateInterviewSessionTxReq)) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.CreateInterviewSessionTxReq))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) RunAndReturn(run func(context.Context, *repositories.CreateInterviewSessionTxReq) error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(run)
	return _c
}

// EndInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) EndInterviewSession(ctx context.Context, req *db.EndInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EndInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.EndInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_EndInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndInterviewSession'
type MockInterviewSessionRepository_EndInterviewSession_Call struct {
	*mock.Call
}

// EndInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.EndInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) EndInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_EndInterviewSession_Call {
	return &MockInterviewSessionRepository_EndInterviewSession_Call{Call: _e.mock.On("EndInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) Run(run func(ctx context.Context, req *db.EndInterviewSessionParams)) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.EndInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) RunAndReturn(run func(context.Context, *db.EndInterviewSessionParams) error) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewSessionInformation provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionRepository) GetInterviewSessionInformation(ctx context.Context, sessionID uuid.UUID) (*db.GetInterviewSessionInformationRow, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewSessionInformation")
	}

	var r0 *db.GetInterviewSessionInformationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*db.GetInterviewSessionInformationRow, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *db.GetInterviewSessionInformationRow); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.GetInterviewSessionInformationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_GetInterviewSessionInformation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewSessionInformation'
type MockInterviewSessionRepository_GetInterviewSessionInformation_Call struct {
	*mock.Call
}

// GetInterviewSessionInformation is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewSessionRepository_Expecter) GetInterviewSessionInformation(ctx interface{}, sessionID interface{}) *MockInterviewSessionRepository_GetInterviewSessionInformation_Call {
	return &MockInterviewSessionRepository_GetInterviewSessionInformation_Call{Call: _e.mock.On("GetInterviewSessionInformation", ctx, sessionID)}
}

func (_c *MockInterviewSessionRepository_GetInterviewSessionInformation_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewSessionRepository_GetInterviewSessionInformation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_GetInterviewSessionInformation_Call) Return(_a0 *db.GetInterviewSessionInformationRow, _a1 error) *MockInterviewSessionRepository_GetInterviewSessionInformation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_GetInterviewSessionInformation_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*db.GetInterviewSessionInformationRow, error)) *MockInterviewSessionRepository_GetInterviewSessionInformation_Call {
	_c.Call.Return(run)
	return _c
}

// GetStartedAndIsStartedConversationSession provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionRepository) GetStartedAndIsStartedConversationSession(ctx context.Context, sessionID uuid.UUID) (*db.GetStartedAndIsStartedConversationSessionRow, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetStartedAndIsStartedConversationSession")
	}

	var r0 *db.GetStartedAndIsStartedConversationSessionRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*db.GetStartedAndIsStartedConversationSessionRow, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *db.GetStartedAndIsStartedConversationSessionRow); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.GetStartedAndIsStartedConversationSessionRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStartedAndIsStartedConversationSession'
type MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call struct {
	*mock.Call
}

// GetStartedAndIsStartedConversationSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewSessionRepository_Expecter) GetStartedAndIsStartedConversationSession(ctx interface{}, sessionID interface{}) *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call {
	return &MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call{Call: _e.mock.On("GetStartedAndIsStartedConversationSession", ctx, sessionID)}
}

func (_c *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call) Return(_a0 *db.GetStartedAndIsStartedConversationSessionRow, _a1 error) *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*db.GetStartedAndIsStartedConversationSessionRow, error)) *MockInterviewSessionRepository_GetStartedAndIsStartedConversationSession_Call {
	_c.Call.Return(run)
	return _c
}

// InterviewFeedbackAndScore provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) InterviewFeedbackAndScore(ctx context.Context, req *repositories.InterviewFeedbackAndScoreReq) (*repositories.InterviewFeedbackAndScoreResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InterviewFeedbackAndScore")
	}

	var r0 *repositories.InterviewFeedbackAndScoreResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.InterviewFeedbackAndScoreReq) (*repositories.InterviewFeedbackAndScoreResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.InterviewFeedbackAndScoreReq) *repositories.InterviewFeedbackAndScoreResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.InterviewFeedbackAndScoreResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repositories.InterviewFeedbackAndScoreReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_InterviewFeedbackAndScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterviewFeedbackAndScore'
type MockInterviewSessionRepository_InterviewFeedbackAndScore_Call struct {
	*mock.Call
}

// InterviewFeedbackAndScore is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.InterviewFeedbackAndScoreReq
func (_e *MockInterviewSessionRepository_Expecter) InterviewFeedbackAndScore(ctx interface{}, req interface{}) *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call {
	return &MockInterviewSessionRepository_InterviewFeedbackAndScore_Call{Call: _e.mock.On("InterviewFeedbackAndScore", ctx, req)}
}

func (_c *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call) Run(run func(ctx context.Context, req *repositories.InterviewFeedbackAndScoreReq)) *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.InterviewFeedbackAndScoreReq))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call) Return(_a0 *repositories.InterviewFeedbackAndScoreResp, _a1 error) *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call) RunAndReturn(run func(context.Context, *repositories.InterviewFeedbackAndScoreReq) (*repositories.InterviewFeedbackAndScoreResp, error)) *MockInterviewSessionRepository_InterviewFeedbackAndScore_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewSessionsByUserIDWithCursor provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) ListInterviewSessionsByUserIDWithCursor(ctx context.Context, req *db.ListInterviewSessionsByUserIDWithCursorParams) ([]db.ListInterviewSessionsByUserIDWithCursorRow, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewSessionsByUserIDWithCursor")
	}

	var r0 []db.ListInterviewSessionsByUserIDWithCursorRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.ListInterviewSessionsByUserIDWithCursorParams) ([]db.ListInterviewSessionsByUserIDWithCursorRow, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.ListInterviewSessionsByUserIDWithCursorParams) []db.ListInterviewSessionsByUserIDWithCursorRow); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListInterviewSessionsByUserIDWithCursorRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.ListInterviewSessionsByUserIDWithCursorParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewSessionsByUserIDWithCursor'
type MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call struct {
	*mock.Call
}

// ListInterviewSessionsByUserIDWithCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.ListInterviewSessionsByUserIDWithCursorParams
func (_e *MockInterviewSessionRepository_Expecter) ListInterviewSessionsByUserIDWithCursor(ctx interface{}, req interface{}) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call {
	return &MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call{Call: _e.mock.On("ListInterviewSessionsByUserIDWithCursor", ctx, req)}
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call) Run(run func(ctx context.Context, req *db.ListInterviewSessionsByUserIDWithCursorParams)) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.ListInterviewSessionsByUserIDWithCursorParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call) Return(_a0 []db.ListInterviewSessionsByUserIDWithCursorRow, _a1 error) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call) RunAndReturn(run func(context.Context, *db.ListInterviewSessionsByUserIDWithCursorParams) ([]db.ListInterviewSessionsByUserIDWithCursorRow, error)) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewSessionsByUserIDWithJumpPagination provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) ListInterviewSessionsByUserIDWithJumpPagination(ctx context.Context, req *db.ListInterviewSessionsByUserIDWithJumpPaginationParams) ([]db.ListInterviewSessionsByUserIDWithJumpPaginationRow, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewSessionsByUserIDWithJumpPagination")
	}

	var r0 []db.ListInterviewSessionsByUserIDWithJumpPaginationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.ListInterviewSessionsByUserIDWithJumpPaginationParams) ([]db.ListInterviewSessionsByUserIDWithJumpPaginationRow, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.ListInterviewSessionsByUserIDWithJumpPaginationParams) []db.ListInterviewSessionsByUserIDWithJumpPaginationRow); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListInterviewSessionsByUserIDWithJumpPaginationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.ListInterviewSessionsByUserIDWithJumpPaginationParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewSessionsByUserIDWithJumpPagination'
type MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call struct {
	*mock.Call
}

// ListInterviewSessionsByUserIDWithJumpPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.ListInterviewSessionsByUserIDWithJumpPaginationParams
func (_e *MockInterviewSessionRepository_Expecter) ListInterviewSessionsByUserIDWithJumpPagination(ctx interface{}, req interface{}) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	return &MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call{Call: _e.mock.On("ListInterviewSessionsByUserIDWithJumpPagination", ctx, req)}
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call) Run(run func(ctx context.Context, req *db.ListInterviewSessionsByUserIDWithJumpPaginationParams)) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.ListInterviewSessionsByUserIDWithJumpPaginationParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call) Return(_a0 []db.ListInterviewSessionsByUserIDWithJumpPaginationRow, _a1 error) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call) RunAndReturn(run func(context.Context, *db.ListInterviewSessionsByUserIDWithJumpPaginationParams) ([]db.ListInterviewSessionsByUserIDWithJumpPaginationRow, error)) *MockInterviewSessionRepository_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterviewSessionStatus provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) UpdateInterviewSessionStatus(ctx context.Context, req *db.UpdateInterviewSessionStatusParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterviewSessionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.UpdateInterviewSessionStatusParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterviewSessionStatus'
type MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call struct {
	*mock.Call
}

// UpdateInterviewSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.UpdateInterviewSessionStatusParams
func (_e *MockInterviewSessionRepository_Expecter) UpdateInterviewSessionStatus(ctx interface{}, req interface{}) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	return &MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call{Call: _e.mock.On("UpdateInterviewSessionStatus", ctx, req)}
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) Run(run func(ctx context.Context, req *db.UpdateInterviewSessionStatusParams)) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.UpdateInterviewSessionStatusParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) Return(_a0 error) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) RunAndReturn(run func(context.Context, *db.UpdateInterviewSessionStatusParams) error) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIsStartedConversationSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) UpdateIsStartedConversationSession(ctx context.Context, req *db.UpdateIsStartedConversationSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIsStartedConversationSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.UpdateIsStartedConversationSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsStartedConversationSession'
type MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call struct {
	*mock.Call
}

// UpdateIsStartedConversationSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.UpdateIsStartedConversationSessionParams
func (_e *MockInterviewSessionRepository_Expecter) UpdateIsStartedConversationSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call {
	return &MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call{Call: _e.mock.On("UpdateIsStartedConversationSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call) Run(run func(ctx context.Context, req *db.UpdateIsStartedConversationSessionParams)) *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.UpdateIsStartedConversationSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call) Return(_a0 error) *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call) RunAndReturn(run func(context.Context, *db.UpdateIsStartedConversationSessionParams) error) *MockInterviewSessionRepository_UpdateIsStartedConversationSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStartedAtInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) UpdateStartedAtInterviewSession(ctx context.Context, req *db.UpdateStartedAtInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStartedAtInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.UpdateStartedAtInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStartedAtInterviewSession'
type MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call struct {
	*mock.Call
}

// UpdateStartedAtInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.UpdateStartedAtInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) UpdateStartedAtInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call {
	return &MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call{Call: _e.mock.On("UpdateStartedAtInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call) Run(run func(ctx context.Context, req *db.UpdateStartedAtInterviewSessionParams)) *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.UpdateStartedAtInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call) RunAndReturn(run func(context.Context, *db.UpdateStartedAtInterviewSessionParams) error) *MockInterviewSessionRepository_UpdateStartedAtInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewSessionRepository creates a new instance of MockInterviewSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewSessionRepository {
	mock := &MockInterviewSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
