// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	uuid "github.com/google/uuid"
)

// MockInterviewTurnsRepository is an autogenerated mock type for the InterviewTurnsRepository type
type MockInterviewTurnsRepository struct {
	mock.Mock
}

type MockInterviewTurnsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewTurnsRepository) EXPECT() *MockInterviewTurnsRepository_Expecter {
	return &MockInterviewTurnsRepository_Expecter{mock: &_m.Mock}
}

// CreateSessionTurnBySessionID provides a mock function with given fields: ctx, req
func (_m *MockInterviewTurnsRepository) CreateSessionTurnBySessionID(ctx context.Context, req *db.CreateInterviewTurnParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionTurnBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateInterviewTurnParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionTurnBySessionID'
type MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call struct {
	*mock.Call
}

// CreateSessionTurnBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateInterviewTurnParams
func (_e *MockInterviewTurnsRepository_Expecter) CreateSessionTurnBySessionID(ctx interface{}, req interface{}) *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call {
	return &MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call{Call: _e.mock.On("CreateSessionTurnBySessionID", ctx, req)}
}

func (_c *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call) Run(run func(ctx context.Context, req *db.CreateInterviewTurnParams)) *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateInterviewTurnParams))
	})
	return _c
}

func (_c *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call) Return(_a0 error) *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call) RunAndReturn(run func(context.Context, *db.CreateInterviewTurnParams) error) *MockInterviewTurnsRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistoryBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewTurnsRepository) GetChatHistoryBySessionID(ctx context.Context, sessionID uuid.UUID) ([]db.GetChatHistoryBySessionIDRow, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistoryBySessionID")
	}

	var r0 []db.GetChatHistoryBySessionIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.GetChatHistoryBySessionIDRow, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.GetChatHistoryBySessionIDRow); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetChatHistoryBySessionIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistoryBySessionID'
type MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call struct {
	*mock.Call
}

// GetChatHistoryBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewTurnsRepository_Expecter) GetChatHistoryBySessionID(ctx interface{}, sessionID interface{}) *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call {
	return &MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call{Call: _e.mock.On("GetChatHistoryBySessionID", ctx, sessionID)}
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call) Return(_a0 []db.GetChatHistoryBySessionIDRow, _a1 error) *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.GetChatHistoryBySessionIDRow, error)) *MockInterviewTurnsRepository_GetChatHistoryBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistoryBySessionIDWithEvaluation provides a mock function with given fields: ctx, req
func (_m *MockInterviewTurnsRepository) GetChatHistoryBySessionIDWithEvaluation(ctx context.Context, req *db.GetChatHistoryBySessionIDWithEvaluationParams) ([]db.GetChatHistoryBySessionIDWithEvaluationRow, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistoryBySessionIDWithEvaluation")
	}

	var r0 []db.GetChatHistoryBySessionIDWithEvaluationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.GetChatHistoryBySessionIDWithEvaluationParams) ([]db.GetChatHistoryBySessionIDWithEvaluationRow, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.GetChatHistoryBySessionIDWithEvaluationParams) []db.GetChatHistoryBySessionIDWithEvaluationRow); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetChatHistoryBySessionIDWithEvaluationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.GetChatHistoryBySessionIDWithEvaluationParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistoryBySessionIDWithEvaluation'
type MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call struct {
	*mock.Call
}

// GetChatHistoryBySessionIDWithEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.GetChatHistoryBySessionIDWithEvaluationParams
func (_e *MockInterviewTurnsRepository_Expecter) GetChatHistoryBySessionIDWithEvaluation(ctx interface{}, req interface{}) *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call {
	return &MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call{Call: _e.mock.On("GetChatHistoryBySessionIDWithEvaluation", ctx, req)}
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call) Run(run func(ctx context.Context, req *db.GetChatHistoryBySessionIDWithEvaluationParams)) *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.GetChatHistoryBySessionIDWithEvaluationParams))
	})
	return _c
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call) Return(_a0 []db.GetChatHistoryBySessionIDWithEvaluationRow, _a1 error) *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call) RunAndReturn(run func(context.Context, *db.GetChatHistoryBySessionIDWithEvaluationParams) ([]db.GetChatHistoryBySessionIDWithEvaluationRow, error)) *MockInterviewTurnsRepository_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewerLastMessage provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewTurnsRepository) GetInterviewerLastMessage(ctx context.Context, sessionID uuid.UUID) (*db.GetInterviewerLastMessageRow, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewerLastMessage")
	}

	var r0 *db.GetInterviewerLastMessageRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*db.GetInterviewerLastMessageRow, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *db.GetInterviewerLastMessageRow); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.GetInterviewerLastMessageRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewTurnsRepository_GetInterviewerLastMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewerLastMessage'
type MockInterviewTurnsRepository_GetInterviewerLastMessage_Call struct {
	*mock.Call
}

// GetInterviewerLastMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewTurnsRepository_Expecter) GetInterviewerLastMessage(ctx interface{}, sessionID interface{}) *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call {
	return &MockInterviewTurnsRepository_GetInterviewerLastMessage_Call{Call: _e.mock.On("GetInterviewerLastMessage", ctx, sessionID)}
}

func (_c *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call) Return(_a0 *db.GetInterviewerLastMessageRow, _a1 error) *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*db.GetInterviewerLastMessageRow, error)) *MockInterviewTurnsRepository_GetInterviewerLastMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxTurnNoBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewTurnsRepository) GetMaxTurnNoBySessionID(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxTurnNoBySessionID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxTurnNoBySessionID'
type MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call struct {
	*mock.Call
}

// GetMaxTurnNoBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewTurnsRepository_Expecter) GetMaxTurnNoBySessionID(ctx interface{}, sessionID interface{}) *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call {
	return &MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call{Call: _e.mock.On("GetMaxTurnNoBySessionID", ctx, sessionID)}
}

func (_c *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call) Return(_a0 int64, _a1 error) *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockInterviewTurnsRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewTurnsRepository creates a new instance of MockInterviewTurnsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewTurnsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewTurnsRepository {
	mock := &MockInterviewTurnsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
