// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	repositories "gitlab.com/interview-simulation/interview-backend-server/internal/repositories"

	uuid "github.com/google/uuid"
)

// MockInterviewSessionRepository is an autogenerated mock type for the InterviewSessionRepository type
type MockInterviewSessionRepository struct {
	mock.Mock
}

type MockInterviewSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewSessionRepository) EXPECT() *MockInterviewSessionRepository_Expecter {
	return &MockInterviewSessionRepository_Expecter{mock: &_m.Mock}
}

// CheckInterviewSessionExists provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionRepository) CheckInterviewSessionExists(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CheckInterviewSessionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_CheckInterviewSessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInterviewSessionExists'
type MockInterviewSessionRepository_CheckInterviewSessionExists_Call struct {
	*mock.Call
}

// CheckInterviewSessionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewSessionRepository_Expecter) CheckInterviewSessionExists(ctx interface{}, sessionID interface{}) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	return &MockInterviewSessionRepository_CheckInterviewSessionExists_Call{Call: _e.mock.On("CheckInterviewSessionExists", ctx, sessionID)}
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) Return(_a0 bool, _a1 error) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_CheckInterviewSessionExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockInterviewSessionRepository_CheckInterviewSessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSession(ctx context.Context, req *db.CreateInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSession'
type MockInterviewSessionRepository_CreateInterviewSession_Call struct {
	*mock.Call
}

// CreateInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	return &MockInterviewSessionRepository_CreateInterviewSession_Call{Call: _e.mock.On("CreateInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) Run(run func(ctx context.Context, req *db.CreateInterviewSessionParams)) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSession_Call) RunAndReturn(run func(context.Context, *db.CreateInterviewSessionParams) error) *MockInterviewSessionRepository_CreateInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithNewResumeTx provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSessionWithNewResumeTx(ctx context.Context, req *repositories.CreateInterviewSessionTxReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithNewResumeTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CreateInterviewSessionTxReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithNewResumeTx'
type MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithNewResumeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CreateInterviewSessionTxReq
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSessionWithNewResumeTx(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	return &MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call{Call: _e.mock.On("CreateInterviewSessionWithNewResumeTx", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Run(run func(ctx context.Context, req *repositories.CreateInterviewSessionTxReq)) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.CreateInterviewSessionTxReq))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) RunAndReturn(run func(context.Context, *repositories.CreateInterviewSessionTxReq) error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSessionTurnBySessionID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateSessionTurnBySessionID(ctx context.Context, req *db.CreateInterviewTurnParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionTurnBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateInterviewTurnParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionTurnBySessionID'
type MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call struct {
	*mock.Call
}

// CreateSessionTurnBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateInterviewTurnParams
func (_e *MockInterviewSessionRepository_Expecter) CreateSessionTurnBySessionID(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call {
	return &MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call{Call: _e.mock.On("CreateSessionTurnBySessionID", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call) Run(run func(ctx context.Context, req *db.CreateInterviewTurnParams)) *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateInterviewTurnParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call) RunAndReturn(run func(context.Context, *db.CreateInterviewTurnParams) error) *MockInterviewSessionRepository_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// EndInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) EndInterviewSession(ctx context.Context, req *db.EndInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EndInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.EndInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_EndInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndInterviewSession'
type MockInterviewSessionRepository_EndInterviewSession_Call struct {
	*mock.Call
}

// EndInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.EndInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) EndInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_EndInterviewSession_Call {
	return &MockInterviewSessionRepository_EndInterviewSession_Call{Call: _e.mock.On("EndInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) Run(run func(ctx context.Context, req *db.EndInterviewSessionParams)) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.EndInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_EndInterviewSession_Call) RunAndReturn(run func(context.Context, *db.EndInterviewSessionParams) error) *MockInterviewSessionRepository_EndInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxTurnNoBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionRepository) GetMaxTurnNoBySessionID(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxTurnNoBySessionID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxTurnNoBySessionID'
type MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call struct {
	*mock.Call
}

// GetMaxTurnNoBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockInterviewSessionRepository_Expecter) GetMaxTurnNoBySessionID(ctx interface{}, sessionID interface{}) *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call {
	return &MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call{Call: _e.mock.On("GetMaxTurnNoBySessionID", ctx, sessionID)}
}

func (_c *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call) Return(_a0 int64, _a1 error) *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockInterviewSessionRepository_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterviewSessionStatus provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) UpdateInterviewSessionStatus(ctx context.Context, req *db.UpdateInterviewSessionStatusParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterviewSessionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.UpdateInterviewSessionStatusParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterviewSessionStatus'
type MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call struct {
	*mock.Call
}

// UpdateInterviewSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.UpdateInterviewSessionStatusParams
func (_e *MockInterviewSessionRepository_Expecter) UpdateInterviewSessionStatus(ctx interface{}, req interface{}) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	return &MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call{Call: _e.mock.On("UpdateInterviewSessionStatus", ctx, req)}
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) Run(run func(ctx context.Context, req *db.UpdateInterviewSessionStatusParams)) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.UpdateInterviewSessionStatusParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) Return(_a0 error) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call) RunAndReturn(run func(context.Context, *db.UpdateInterviewSessionStatusParams) error) *MockInterviewSessionRepository_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewSessionRepository creates a new instance of MockInterviewSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewSessionRepository {
	mock := &MockInterviewSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
