// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	repositories "gitlab.com/interview-simulation/interview-backend-server/internal/repositories"
)

// MockInterviewSessionRepository is an autogenerated mock type for the InterviewSessionRepository type
type MockInterviewSessionRepository struct {
	mock.Mock
}

type MockInterviewSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewSessionRepository) EXPECT() *MockInterviewSessionRepository_Expecter {
	return &MockInterviewSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateInterviewSessionWithExistingResumeTx provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSessionWithExistingResumeTx(ctx context.Context, req *repositories.CreateInterviewSessionWithExistingResumeTxReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithExistingResumeTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CreateInterviewSessionWithExistingResumeTxReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithExistingResumeTx'
type MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithExistingResumeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CreateInterviewSessionWithExistingResumeTxReq
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSessionWithExistingResumeTx(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call {
	return &MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call{Call: _e.mock.On("CreateInterviewSessionWithExistingResumeTx", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call) Run(run func(ctx context.Context, req *repositories.CreateInterviewSessionWithExistingResumeTxReq)) *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.CreateInterviewSessionWithExistingResumeTxReq))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call) RunAndReturn(run func(context.Context, *repositories.CreateInterviewSessionWithExistingResumeTxReq) error) *MockInterviewSessionRepository_CreateInterviewSessionWithExistingResumeTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithNewResumeTx provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) CreateInterviewSessionWithNewResumeTx(ctx context.Context, req *repositories.CreateInterviewSessionTxReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithNewResumeTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CreateInterviewSessionTxReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithNewResumeTx'
type MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithNewResumeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CreateInterviewSessionTxReq
func (_e *MockInterviewSessionRepository_Expecter) CreateInterviewSessionWithNewResumeTx(ctx interface{}, req interface{}) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	return &MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call{Call: _e.mock.On("CreateInterviewSessionWithNewResumeTx", ctx, req)}
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Run(run func(ctx context.Context, req *repositories.CreateInterviewSessionTxReq)) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repositories.CreateInterviewSessionTxReq))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) Return(_a0 error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call) RunAndReturn(run func(context.Context, *repositories.CreateInterviewSessionTxReq) error) *MockInterviewSessionRepository_CreateInterviewSessionWithNewResumeTx_Call {
	_c.Call.Return(run)
	return _c
}

// StartInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionRepository) StartInterviewSession(ctx context.Context, req *db.StartInterviewSessionParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.StartInterviewSessionParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionRepository_StartInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartInterviewSession'
type MockInterviewSessionRepository_StartInterviewSession_Call struct {
	*mock.Call
}

// StartInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.StartInterviewSessionParams
func (_e *MockInterviewSessionRepository_Expecter) StartInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionRepository_StartInterviewSession_Call {
	return &MockInterviewSessionRepository_StartInterviewSession_Call{Call: _e.mock.On("StartInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionRepository_StartInterviewSession_Call) Run(run func(ctx context.Context, req *db.StartInterviewSessionParams)) *MockInterviewSessionRepository_StartInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.StartInterviewSessionParams))
	})
	return _c
}

func (_c *MockInterviewSessionRepository_StartInterviewSession_Call) Return(_a0 error) *MockInterviewSessionRepository_StartInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionRepository_StartInterviewSession_Call) RunAndReturn(run func(context.Context, *db.StartInterviewSessionParams) error) *MockInterviewSessionRepository_StartInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewSessionRepository creates a new instance of MockInterviewSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewSessionRepository {
	mock := &MockInterviewSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
