// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import mock "github.com/stretchr/testify/mock"

// MockResetTokenRepository is an autogenerated mock type for the ResetTokenRepository type
type MockResetTokenRepository struct {
	mock.Mock
}

type MockResetTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResetTokenRepository) EXPECT() *MockResetTokenRepository_Expecter {
	return &MockResetTokenRepository_Expecter{mock: &_m.Mock}
}

// NewMockResetTokenRepository creates a new instance of MockResetTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResetTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResetTokenRepository {
	mock := &MockResetTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
