// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"
)

// MockReviewCommentRepository is an autogenerated mock type for the ReviewCommentRepository type
type MockReviewCommentRepository struct {
	mock.Mock
}

type MockReviewCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewCommentRepository) EXPECT() *MockReviewCommentRepository_Expecter {
	return &MockReviewCommentRepository_Expecter{mock: &_m.Mock}
}

// CreateReviewComment provides a mock function with given fields: ctx, req
func (_m *MockReviewCommentRepository) CreateReviewComment(ctx context.Context, req *db.CreateReviewCommentParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReviewComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateReviewCommentParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewCommentRepository_CreateReviewComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReviewComment'
type MockReviewCommentRepository_CreateReviewComment_Call struct {
	*mock.Call
}

// CreateReviewComment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateReviewCommentParams
func (_e *MockReviewCommentRepository_Expecter) CreateReviewComment(ctx interface{}, req interface{}) *MockReviewCommentRepository_CreateReviewComment_Call {
	return &MockReviewCommentRepository_CreateReviewComment_Call{Call: _e.mock.On("CreateReviewComment", ctx, req)}
}

func (_c *MockReviewCommentRepository_CreateReviewComment_Call) Run(run func(ctx context.Context, req *db.CreateReviewCommentParams)) *MockReviewCommentRepository_CreateReviewComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateReviewCommentParams))
	})
	return _c
}

func (_c *MockReviewCommentRepository_CreateReviewComment_Call) Return(_a0 error) *MockReviewCommentRepository_CreateReviewComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewCommentRepository_CreateReviewComment_Call) RunAndReturn(run func(context.Context, *db.CreateReviewCommentParams) error) *MockReviewCommentRepository_CreateReviewComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewCommentRepository creates a new instance of MockReviewCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewCommentRepository {
	mock := &MockReviewCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
