// Code generated by mockery v2.53.3. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CheckUserExistsByProviderID provides a mock function with given fields: ctx, req
func (_m *MockUserRepository) CheckUserExistsByProviderID(ctx context.Context, req db.CheckUserExistsByProviderIDParams) (bool, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExistsByProviderID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CheckUserExistsByProviderIDParams) (bool, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CheckUserExistsByProviderIDParams) bool); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CheckUserExistsByProviderIDParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CheckUserExistsByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserExistsByProviderID'
type MockUserRepository_CheckUserExistsByProviderID_Call struct {
	*mock.Call
}

// CheckUserExistsByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - req db.CheckUserExistsByProviderIDParams
func (_e *MockUserRepository_Expecter) CheckUserExistsByProviderID(ctx interface{}, req interface{}) *MockUserRepository_CheckUserExistsByProviderID_Call {
	return &MockUserRepository_CheckUserExistsByProviderID_Call{Call: _e.mock.On("CheckUserExistsByProviderID", ctx, req)}
}

func (_c *MockUserRepository_CheckUserExistsByProviderID_Call) Run(run func(ctx context.Context, req db.CheckUserExistsByProviderIDParams)) *MockUserRepository_CheckUserExistsByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CheckUserExistsByProviderIDParams))
	})
	return _c
}

func (_c *MockUserRepository_CheckUserExistsByProviderID_Call) Return(_a0 bool, _a1 error) *MockUserRepository_CheckUserExistsByProviderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CheckUserExistsByProviderID_Call) RunAndReturn(run func(context.Context, db.CheckUserExistsByProviderIDParams) (bool, error)) *MockUserRepository_CheckUserExistsByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithProvider provides a mock function with given fields: ctx, req
func (_m *MockUserRepository) CreateUserWithProvider(ctx context.Context, req *db.CreateUserWithProviderParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.CreateUserWithProviderParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateUserWithProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithProvider'
type MockUserRepository_CreateUserWithProvider_Call struct {
	*mock.Call
}

// CreateUserWithProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - req *db.CreateUserWithProviderParams
func (_e *MockUserRepository_Expecter) CreateUserWithProvider(ctx interface{}, req interface{}) *MockUserRepository_CreateUserWithProvider_Call {
	return &MockUserRepository_CreateUserWithProvider_Call{Call: _e.mock.On("CreateUserWithProvider", ctx, req)}
}

func (_c *MockUserRepository_CreateUserWithProvider_Call) Run(run func(ctx context.Context, req *db.CreateUserWithProviderParams)) *MockUserRepository_CreateUserWithProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.CreateUserWithProviderParams))
	})
	return _c
}

func (_c *MockUserRepository_CreateUserWithProvider_Call) Return(_a0 error) *MockUserRepository_CreateUserWithProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateUserWithProvider_Call) RunAndReturn(run func(context.Context, *db.CreateUserWithProviderParams) error) *MockUserRepository_CreateUserWithProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByProviderID provides a mock function with given fields: ctx, req
func (_m *MockUserRepository) GetUserByProviderID(ctx context.Context, req db.GetUserByProviderIDParams) (db.Users, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByProviderID")
	}

	var r0 db.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetUserByProviderIDParams) (db.Users, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetUserByProviderIDParams) db.Users); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(db.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetUserByProviderIDParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByProviderID'
type MockUserRepository_GetUserByProviderID_Call struct {
	*mock.Call
}

// GetUserByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - req db.GetUserByProviderIDParams
func (_e *MockUserRepository_Expecter) GetUserByProviderID(ctx interface{}, req interface{}) *MockUserRepository_GetUserByProviderID_Call {
	return &MockUserRepository_GetUserByProviderID_Call{Call: _e.mock.On("GetUserByProviderID", ctx, req)}
}

func (_c *MockUserRepository_GetUserByProviderID_Call) Run(run func(ctx context.Context, req db.GetUserByProviderIDParams)) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetUserByProviderIDParams))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByProviderID_Call) Return(_a0 db.Users, _a1 error) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByProviderID_Call) RunAndReturn(run func(context.Context, db.GetUserByProviderIDParams) (db.Users, error)) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockUserRepository) HealthCheck(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockUserRepository_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) HealthCheck(ctx interface{}) *MockUserRepository_HealthCheck_Call {
	return &MockUserRepository_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockUserRepository_HealthCheck_Call) Run(run func(ctx context.Context)) *MockUserRepository_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRepository_HealthCheck_Call) Return(_a0 string, _a1 error) *MockUserRepository_HealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_HealthCheck_Call) RunAndReturn(run func(context.Context) (string, error)) *MockUserRepository_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserLoginInfo provides a mock function with given fields: ctx, req
func (_m *MockUserRepository) UpdateUserLoginInfo(ctx context.Context, req db.UpdateUserLoginInfoParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserLoginInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserLoginInfoParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateUserLoginInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserLoginInfo'
type MockUserRepository_UpdateUserLoginInfo_Call struct {
	*mock.Call
}

// UpdateUserLoginInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - req db.UpdateUserLoginInfoParams
func (_e *MockUserRepository_Expecter) UpdateUserLoginInfo(ctx interface{}, req interface{}) *MockUserRepository_UpdateUserLoginInfo_Call {
	return &MockUserRepository_UpdateUserLoginInfo_Call{Call: _e.mock.On("UpdateUserLoginInfo", ctx, req)}
}

func (_c *MockUserRepository_UpdateUserLoginInfo_Call) Run(run func(ctx context.Context, req db.UpdateUserLoginInfoParams)) *MockUserRepository_UpdateUserLoginInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserLoginInfoParams))
	})
	return _c
}

func (_c *MockUserRepository_UpdateUserLoginInfo_Call) Return(_a0 error) *MockUserRepository_UpdateUserLoginInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateUserLoginInfo_Call) RunAndReturn(run func(context.Context, db.UpdateUserLoginInfoParams) error) *MockUserRepository_UpdateUserLoginInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
