// Code generated by mockery v2.53.3. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/interview-simulation/interview-backend-server/internal/entities"
)

// MockInterviewSessionService is an autogenerated mock type for the InterviewSessionService type
type MockInterviewSessionService struct {
	mock.Mock
}

type MockInterviewSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewSessionService) EXPECT() *MockInterviewSessionService_Expecter {
	return &MockInterviewSessionService_Expecter{mock: &_m.Mock}
}

// CalculateTurnScore provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CalculateTurnScore(ctx context.Context, req *entities.CalculateTurnScoreReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CalculateTurnScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CalculateTurnScoreReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_CalculateTurnScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateTurnScore'
type MockInterviewSessionService_CalculateTurnScore_Call struct {
	*mock.Call
}

// CalculateTurnScore is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CalculateTurnScoreReq
func (_e *MockInterviewSessionService_Expecter) CalculateTurnScore(ctx interface{}, req interface{}) *MockInterviewSessionService_CalculateTurnScore_Call {
	return &MockInterviewSessionService_CalculateTurnScore_Call{Call: _e.mock.On("CalculateTurnScore", ctx, req)}
}

func (_c *MockInterviewSessionService_CalculateTurnScore_Call) Run(run func(ctx context.Context, req *entities.CalculateTurnScoreReq)) *MockInterviewSessionService_CalculateTurnScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CalculateTurnScoreReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CalculateTurnScore_Call) Return(_a0 error) *MockInterviewSessionService_CalculateTurnScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_CalculateTurnScore_Call) RunAndReturn(run func(context.Context, *entities.CalculateTurnScoreReq) error) *MockInterviewSessionService_CalculateTurnScore_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithExistingResume provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateInterviewSessionWithExistingResume(ctx context.Context, req *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithExistingResume")
	}

	var r0 *entities.CreateInterviewSessionWithExistingResumeResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) *entities.CreateInterviewSessionWithExistingResumeResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CreateInterviewSessionWithExistingResumeResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithExistingResume'
type MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithExistingResume is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateInterviewSessionWithExistingResumeReq
func (_e *MockInterviewSessionService_Expecter) CreateInterviewSessionWithExistingResume(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	return &MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call{Call: _e.mock.On("CreateInterviewSessionWithExistingResume", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) Run(run func(ctx context.Context, req *entities.CreateInterviewSessionWithExistingResumeReq)) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateInterviewSessionWithExistingResumeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) Return(_a0 *entities.CreateInterviewSessionWithExistingResumeResp, _a1 error) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) RunAndReturn(run func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error)) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithNewResume provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateInterviewSessionWithNewResume(ctx context.Context, req *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithNewResume")
	}

	var r0 *entities.CreateInterviewSessionWithNewResumeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) *entities.CreateInterviewSessionWithNewResumeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CreateInterviewSessionWithNewResumeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithNewResume'
type MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithNewResume is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateInterviewSessionWithNewResumeRequest
func (_e *MockInterviewSessionService_Expecter) CreateInterviewSessionWithNewResume(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	return &MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call{Call: _e.mock.On("CreateInterviewSessionWithNewResume", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) Run(run func(ctx context.Context, req *entities.CreateInterviewSessionWithNewResumeRequest)) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateInterviewSessionWithNewResumeRequest))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) Return(_a0 *entities.CreateInterviewSessionWithNewResumeResponse, _a1 error) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) RunAndReturn(run func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error)) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSessionTurnBySessionID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateSessionTurnBySessionID(ctx context.Context, req *entities.CreateSessionTurnBySessionIDReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionTurnBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateSessionTurnBySessionIDReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_CreateSessionTurnBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionTurnBySessionID'
type MockInterviewSessionService_CreateSessionTurnBySessionID_Call struct {
	*mock.Call
}

// CreateSessionTurnBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateSessionTurnBySessionIDReq
func (_e *MockInterviewSessionService_Expecter) CreateSessionTurnBySessionID(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateSessionTurnBySessionID_Call {
	return &MockInterviewSessionService_CreateSessionTurnBySessionID_Call{Call: _e.mock.On("CreateSessionTurnBySessionID", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateSessionTurnBySessionID_Call) Run(run func(ctx context.Context, req *entities.CreateSessionTurnBySessionIDReq)) *MockInterviewSessionService_CreateSessionTurnBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateSessionTurnBySessionIDReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateSessionTurnBySessionID_Call) Return(_a0 error) *MockInterviewSessionService_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_CreateSessionTurnBySessionID_Call) RunAndReturn(run func(context.Context, *entities.CreateSessionTurnBySessionIDReq) error) *MockInterviewSessionService_CreateSessionTurnBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// IsSessionValid provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) IsSessionValid(ctx context.Context, req *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IsSessionValid")
	}

	var r0 *entities.IsSessionValidResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.IsSessionValidReq) *entities.IsSessionValidResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IsSessionValidResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.IsSessionValidReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_IsSessionValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSessionValid'
type MockInterviewSessionService_IsSessionValid_Call struct {
	*mock.Call
}

// IsSessionValid is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.IsSessionValidReq
func (_e *MockInterviewSessionService_Expecter) IsSessionValid(ctx interface{}, req interface{}) *MockInterviewSessionService_IsSessionValid_Call {
	return &MockInterviewSessionService_IsSessionValid_Call{Call: _e.mock.On("IsSessionValid", ctx, req)}
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) Run(run func(ctx context.Context, req *entities.IsSessionValidReq)) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.IsSessionValidReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) Return(_a0 *entities.IsSessionValidResp, _a1 error) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) RunAndReturn(run func(context.Context, *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error)) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionEndTime provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) SetSessionEndTime(ctx context.Context, req *entities.SetSessionEndTimeReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetSessionEndTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SetSessionEndTimeReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_SetSessionEndTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionEndTime'
type MockInterviewSessionService_SetSessionEndTime_Call struct {
	*mock.Call
}

// SetSessionEndTime is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.SetSessionEndTimeReq
func (_e *MockInterviewSessionService_Expecter) SetSessionEndTime(ctx interface{}, req interface{}) *MockInterviewSessionService_SetSessionEndTime_Call {
	return &MockInterviewSessionService_SetSessionEndTime_Call{Call: _e.mock.On("SetSessionEndTime", ctx, req)}
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) Run(run func(ctx context.Context, req *entities.SetSessionEndTimeReq)) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SetSessionEndTimeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) Return(_a0 error) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) RunAndReturn(run func(context.Context, *entities.SetSessionEndTimeReq) error) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionStartTime provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) SetSessionStartTime(ctx context.Context, req *entities.SetSessionStartTimeReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetSessionStartTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SetSessionStartTimeReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_SetSessionStartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionStartTime'
type MockInterviewSessionService_SetSessionStartTime_Call struct {
	*mock.Call
}

// SetSessionStartTime is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.SetSessionStartTimeReq
func (_e *MockInterviewSessionService_Expecter) SetSessionStartTime(ctx interface{}, req interface{}) *MockInterviewSessionService_SetSessionStartTime_Call {
	return &MockInterviewSessionService_SetSessionStartTime_Call{Call: _e.mock.On("SetSessionStartTime", ctx, req)}
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) Run(run func(ctx context.Context, req *entities.SetSessionStartTimeReq)) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SetSessionStartTimeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) Return(_a0 error) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) RunAndReturn(run func(context.Context, *entities.SetSessionStartTimeReq) error) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterviewSessionStatus provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) UpdateInterviewSessionStatus(ctx context.Context, req *entities.UpdateInterviewSessionStatusReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterviewSessionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UpdateInterviewSessionStatusReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_UpdateInterviewSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterviewSessionStatus'
type MockInterviewSessionService_UpdateInterviewSessionStatus_Call struct {
	*mock.Call
}

// UpdateInterviewSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.UpdateInterviewSessionStatusReq
func (_e *MockInterviewSessionService_Expecter) UpdateInterviewSessionStatus(ctx interface{}, req interface{}) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	return &MockInterviewSessionService_UpdateInterviewSessionStatus_Call{Call: _e.mock.On("UpdateInterviewSessionStatus", ctx, req)}
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) Run(run func(ctx context.Context, req *entities.UpdateInterviewSessionStatusReq)) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.UpdateInterviewSessionStatusReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) Return(_a0 error) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) RunAndReturn(run func(context.Context, *entities.UpdateInterviewSessionStatusReq) error) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewSessionService creates a new instance of MockInterviewSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewSessionService {
	mock := &MockInterviewSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
