// Code generated by mockery v2.53.3. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/interview-simulation/interview-backend-server/internal/entities"
)

// MockInterviewSessionService is an autogenerated mock type for the InterviewSessionService type
type MockInterviewSessionService struct {
	mock.Mock
}

type MockInterviewSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterviewSessionService) EXPECT() *MockInterviewSessionService_Expecter {
	return &MockInterviewSessionService_Expecter{mock: &_m.Mock}
}

// CreateInterviewSessionWithExistingResume provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateInterviewSessionWithExistingResume(ctx context.Context, req *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithExistingResume")
	}

	var r0 *entities.CreateInterviewSessionWithExistingResumeResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) *entities.CreateInterviewSessionWithExistingResumeResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CreateInterviewSessionWithExistingResumeResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithExistingResume'
type MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithExistingResume is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateInterviewSessionWithExistingResumeReq
func (_e *MockInterviewSessionService_Expecter) CreateInterviewSessionWithExistingResume(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	return &MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call{Call: _e.mock.On("CreateInterviewSessionWithExistingResume", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) Run(run func(ctx context.Context, req *entities.CreateInterviewSessionWithExistingResumeReq)) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateInterviewSessionWithExistingResumeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) Return(_a0 *entities.CreateInterviewSessionWithExistingResumeResp, _a1 error) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call) RunAndReturn(run func(context.Context, *entities.CreateInterviewSessionWithExistingResumeReq) (*entities.CreateInterviewSessionWithExistingResumeResp, error)) *MockInterviewSessionService_CreateInterviewSessionWithExistingResume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSessionWithNewResume provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateInterviewSessionWithNewResume(ctx context.Context, req *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSessionWithNewResume")
	}

	var r0 *entities.CreateInterviewSessionWithNewResumeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) *entities.CreateInterviewSessionWithNewResumeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CreateInterviewSessionWithNewResumeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSessionWithNewResume'
type MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call struct {
	*mock.Call
}

// CreateInterviewSessionWithNewResume is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateInterviewSessionWithNewResumeRequest
func (_e *MockInterviewSessionService_Expecter) CreateInterviewSessionWithNewResume(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	return &MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call{Call: _e.mock.On("CreateInterviewSessionWithNewResume", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) Run(run func(ctx context.Context, req *entities.CreateInterviewSessionWithNewResumeRequest)) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateInterviewSessionWithNewResumeRequest))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) Return(_a0 *entities.CreateInterviewSessionWithNewResumeResponse, _a1 error) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call) RunAndReturn(run func(context.Context, *entities.CreateInterviewSessionWithNewResumeRequest) (*entities.CreateInterviewSessionWithNewResumeResponse, error)) *MockInterviewSessionService_CreateInterviewSessionWithNewResume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewerSessionTurnBySessionID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateInterviewerSessionTurnBySessionID(ctx context.Context, req *entities.CreateInterviewerSessionTurnBySessionIDReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewerSessionTurnBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateInterviewerSessionTurnBySessionIDReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewerSessionTurnBySessionID'
type MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call struct {
	*mock.Call
}

// CreateInterviewerSessionTurnBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateInterviewerSessionTurnBySessionIDReq
func (_e *MockInterviewSessionService_Expecter) CreateInterviewerSessionTurnBySessionID(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call {
	return &MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call{Call: _e.mock.On("CreateInterviewerSessionTurnBySessionID", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call) Run(run func(ctx context.Context, req *entities.CreateInterviewerSessionTurnBySessionIDReq)) *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateInterviewerSessionTurnBySessionIDReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call) Return(_a0 error) *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call) RunAndReturn(run func(context.Context, *entities.CreateInterviewerSessionTurnBySessionIDReq) error) *MockInterviewSessionService_CreateInterviewerSessionTurnBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserSessionTurnBySessionID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) CreateUserSessionTurnBySessionID(ctx context.Context, req *entities.CreateUserSessionTurnBySessionIDReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSessionTurnBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateUserSessionTurnBySessionIDReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserSessionTurnBySessionID'
type MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call struct {
	*mock.Call
}

// CreateUserSessionTurnBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateUserSessionTurnBySessionIDReq
func (_e *MockInterviewSessionService_Expecter) CreateUserSessionTurnBySessionID(ctx interface{}, req interface{}) *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call {
	return &MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call{Call: _e.mock.On("CreateUserSessionTurnBySessionID", ctx, req)}
}

func (_c *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call) Run(run func(ctx context.Context, req *entities.CreateUserSessionTurnBySessionIDReq)) *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateUserSessionTurnBySessionIDReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call) Return(_a0 error) *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call) RunAndReturn(run func(context.Context, *entities.CreateUserSessionTurnBySessionIDReq) error) *MockInterviewSessionService_CreateUserSessionTurnBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserInterviewSessionByID provides a mock function with given fields: ctx, sessionIDReq
func (_m *MockInterviewSessionService) DeleteUserInterviewSessionByID(ctx context.Context, sessionIDReq string) error {
	ret := _m.Called(ctx, sessionIDReq)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterviewSessionByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionIDReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_DeleteUserInterviewSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterviewSessionByID'
type MockInterviewSessionService_DeleteUserInterviewSessionByID_Call struct {
	*mock.Call
}

// DeleteUserInterviewSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDReq string
func (_e *MockInterviewSessionService_Expecter) DeleteUserInterviewSessionByID(ctx interface{}, sessionIDReq interface{}) *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call {
	return &MockInterviewSessionService_DeleteUserInterviewSessionByID_Call{Call: _e.mock.On("DeleteUserInterviewSessionByID", ctx, sessionIDReq)}
}

func (_c *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call) Run(run func(ctx context.Context, sessionIDReq string)) *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call) Return(_a0 error) *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call) RunAndReturn(run func(context.Context, string) error) *MockInterviewSessionService_DeleteUserInterviewSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// EndInterviewSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) EndInterviewSession(ctx context.Context, req *entities.EndInterviewSessionReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EndInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.EndInterviewSessionReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_EndInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndInterviewSession'
type MockInterviewSessionService_EndInterviewSession_Call struct {
	*mock.Call
}

// EndInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.EndInterviewSessionReq
func (_e *MockInterviewSessionService_Expecter) EndInterviewSession(ctx interface{}, req interface{}) *MockInterviewSessionService_EndInterviewSession_Call {
	return &MockInterviewSessionService_EndInterviewSession_Call{Call: _e.mock.On("EndInterviewSession", ctx, req)}
}

func (_c *MockInterviewSessionService_EndInterviewSession_Call) Run(run func(ctx context.Context, req *entities.EndInterviewSessionReq)) *MockInterviewSessionService_EndInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.EndInterviewSessionReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_EndInterviewSession_Call) Return(_a0 error) *MockInterviewSessionService_EndInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_EndInterviewSession_Call) RunAndReturn(run func(context.Context, *entities.EndInterviewSessionReq) error) *MockInterviewSessionService_EndInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistoryBySessionIDWithEvaluation provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) GetChatHistoryBySessionIDWithEvaluation(ctx context.Context, req *entities.GetChatHistoryBySessionIDWithEvaluationReq) (*entities.GetChatHistoryBySessionIDWithEvaluationResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistoryBySessionIDWithEvaluation")
	}

	var r0 *entities.GetChatHistoryBySessionIDWithEvaluationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetChatHistoryBySessionIDWithEvaluationReq) (*entities.GetChatHistoryBySessionIDWithEvaluationResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetChatHistoryBySessionIDWithEvaluationReq) *entities.GetChatHistoryBySessionIDWithEvaluationResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GetChatHistoryBySessionIDWithEvaluationResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.GetChatHistoryBySessionIDWithEvaluationReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistoryBySessionIDWithEvaluation'
type MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call struct {
	*mock.Call
}

// GetChatHistoryBySessionIDWithEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.GetChatHistoryBySessionIDWithEvaluationReq
func (_e *MockInterviewSessionService_Expecter) GetChatHistoryBySessionIDWithEvaluation(ctx interface{}, req interface{}) *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call {
	return &MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call{Call: _e.mock.On("GetChatHistoryBySessionIDWithEvaluation", ctx, req)}
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call) Run(run func(ctx context.Context, req *entities.GetChatHistoryBySessionIDWithEvaluationReq)) *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.GetChatHistoryBySessionIDWithEvaluationReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call) Return(_a0 *entities.GetChatHistoryBySessionIDWithEvaluationResp, _a1 error) *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call) RunAndReturn(run func(context.Context, *entities.GetChatHistoryBySessionIDWithEvaluationReq) (*entities.GetChatHistoryBySessionIDWithEvaluationResp, error)) *MockInterviewSessionService_GetChatHistoryBySessionIDWithEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistoryBySessionToken provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) GetChatHistoryBySessionToken(ctx context.Context, req *entities.GetChatHistoryBySessionTokenReq) (*entities.GetChatHistoryBySessionTokenResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistoryBySessionToken")
	}

	var r0 *entities.GetChatHistoryBySessionTokenResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetChatHistoryBySessionTokenReq) (*entities.GetChatHistoryBySessionTokenResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetChatHistoryBySessionTokenReq) *entities.GetChatHistoryBySessionTokenResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GetChatHistoryBySessionTokenResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.GetChatHistoryBySessionTokenReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetChatHistoryBySessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistoryBySessionToken'
type MockInterviewSessionService_GetChatHistoryBySessionToken_Call struct {
	*mock.Call
}

// GetChatHistoryBySessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.GetChatHistoryBySessionTokenReq
func (_e *MockInterviewSessionService_Expecter) GetChatHistoryBySessionToken(ctx interface{}, req interface{}) *MockInterviewSessionService_GetChatHistoryBySessionToken_Call {
	return &MockInterviewSessionService_GetChatHistoryBySessionToken_Call{Call: _e.mock.On("GetChatHistoryBySessionToken", ctx, req)}
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionToken_Call) Run(run func(ctx context.Context, req *entities.GetChatHistoryBySessionTokenReq)) *MockInterviewSessionService_GetChatHistoryBySessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.GetChatHistoryBySessionTokenReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionToken_Call) Return(_a0 *entities.GetChatHistoryBySessionTokenResp, _a1 error) *MockInterviewSessionService_GetChatHistoryBySessionToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetChatHistoryBySessionToken_Call) RunAndReturn(run func(context.Context, *entities.GetChatHistoryBySessionTokenReq) (*entities.GetChatHistoryBySessionTokenResp, error)) *MockInterviewSessionService_GetChatHistoryBySessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewSessionInformationByID provides a mock function with given fields: ctx, sessionIDReq
func (_m *MockInterviewSessionService) GetInterviewSessionInformationByID(ctx context.Context, sessionIDReq string) (*entities.GetInterviewSessionInformationResp, error) {
	ret := _m.Called(ctx, sessionIDReq)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewSessionInformationByID")
	}

	var r0 *entities.GetInterviewSessionInformationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.GetInterviewSessionInformationResp, error)); ok {
		return rf(ctx, sessionIDReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.GetInterviewSessionInformationResp); ok {
		r0 = rf(ctx, sessionIDReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GetInterviewSessionInformationResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionIDReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetInterviewSessionInformationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewSessionInformationByID'
type MockInterviewSessionService_GetInterviewSessionInformationByID_Call struct {
	*mock.Call
}

// GetInterviewSessionInformationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDReq string
func (_e *MockInterviewSessionService_Expecter) GetInterviewSessionInformationByID(ctx interface{}, sessionIDReq interface{}) *MockInterviewSessionService_GetInterviewSessionInformationByID_Call {
	return &MockInterviewSessionService_GetInterviewSessionInformationByID_Call{Call: _e.mock.On("GetInterviewSessionInformationByID", ctx, sessionIDReq)}
}

func (_c *MockInterviewSessionService_GetInterviewSessionInformationByID_Call) Run(run func(ctx context.Context, sessionIDReq string)) *MockInterviewSessionService_GetInterviewSessionInformationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionInformationByID_Call) Return(_a0 *entities.GetInterviewSessionInformationResp, _a1 error) *MockInterviewSessionService_GetInterviewSessionInformationByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionInformationByID_Call) RunAndReturn(run func(context.Context, string) (*entities.GetInterviewSessionInformationResp, error)) *MockInterviewSessionService_GetInterviewSessionInformationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewSessionState provides a mock function with given fields: ctx, sessionId
func (_m *MockInterviewSessionService) GetInterviewSessionState(ctx context.Context, sessionId string) (*entities.GetInterviewSessionStateResp, error) {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewSessionState")
	}

	var r0 *entities.GetInterviewSessionStateResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.GetInterviewSessionStateResp, error)); ok {
		return rf(ctx, sessionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.GetInterviewSessionStateResp); ok {
		r0 = rf(ctx, sessionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GetInterviewSessionStateResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetInterviewSessionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewSessionState'
type MockInterviewSessionService_GetInterviewSessionState_Call struct {
	*mock.Call
}

// GetInterviewSessionState is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionId string
func (_e *MockInterviewSessionService_Expecter) GetInterviewSessionState(ctx interface{}, sessionId interface{}) *MockInterviewSessionService_GetInterviewSessionState_Call {
	return &MockInterviewSessionService_GetInterviewSessionState_Call{Call: _e.mock.On("GetInterviewSessionState", ctx, sessionId)}
}

func (_c *MockInterviewSessionService_GetInterviewSessionState_Call) Run(run func(ctx context.Context, sessionId string)) *MockInterviewSessionService_GetInterviewSessionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionState_Call) Return(_a0 *entities.GetInterviewSessionStateResp, _a1 error) *MockInterviewSessionService_GetInterviewSessionState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionState_Call) RunAndReturn(run func(context.Context, string) (*entities.GetInterviewSessionStateResp, error)) *MockInterviewSessionService_GetInterviewSessionState_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewSessionStatusByID provides a mock function with given fields: ctx, sessionIDReq
func (_m *MockInterviewSessionService) GetInterviewSessionStatusByID(ctx context.Context, sessionIDReq string) (string, error) {
	ret := _m.Called(ctx, sessionIDReq)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewSessionStatusByID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sessionIDReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionIDReq)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionIDReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetInterviewSessionStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewSessionStatusByID'
type MockInterviewSessionService_GetInterviewSessionStatusByID_Call struct {
	*mock.Call
}

// GetInterviewSessionStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDReq string
func (_e *MockInterviewSessionService_Expecter) GetInterviewSessionStatusByID(ctx interface{}, sessionIDReq interface{}) *MockInterviewSessionService_GetInterviewSessionStatusByID_Call {
	return &MockInterviewSessionService_GetInterviewSessionStatusByID_Call{Call: _e.mock.On("GetInterviewSessionStatusByID", ctx, sessionIDReq)}
}

func (_c *MockInterviewSessionService_GetInterviewSessionStatusByID_Call) Run(run func(ctx context.Context, sessionIDReq string)) *MockInterviewSessionService_GetInterviewSessionStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionStatusByID_Call) Return(_a0 string, _a1 error) *MockInterviewSessionService_GetInterviewSessionStatusByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewSessionStatusByID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockInterviewSessionService_GetInterviewSessionStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterviewerLastMessage provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) GetInterviewerLastMessage(ctx context.Context, req *entities.GetInterviewerLastMessageReq) (*entities.GetInterviewerLastMessageResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewerLastMessage")
	}

	var r0 *entities.GetInterviewerLastMessageResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetInterviewerLastMessageReq) (*entities.GetInterviewerLastMessageResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetInterviewerLastMessageReq) *entities.GetInterviewerLastMessageResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GetInterviewerLastMessageResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.GetInterviewerLastMessageReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetInterviewerLastMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewerLastMessage'
type MockInterviewSessionService_GetInterviewerLastMessage_Call struct {
	*mock.Call
}

// GetInterviewerLastMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.GetInterviewerLastMessageReq
func (_e *MockInterviewSessionService_Expecter) GetInterviewerLastMessage(ctx interface{}, req interface{}) *MockInterviewSessionService_GetInterviewerLastMessage_Call {
	return &MockInterviewSessionService_GetInterviewerLastMessage_Call{Call: _e.mock.On("GetInterviewerLastMessage", ctx, req)}
}

func (_c *MockInterviewSessionService_GetInterviewerLastMessage_Call) Run(run func(ctx context.Context, req *entities.GetInterviewerLastMessageReq)) *MockInterviewSessionService_GetInterviewerLastMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.GetInterviewerLastMessageReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewerLastMessage_Call) Return(_a0 *entities.GetInterviewerLastMessageResp, _a1 error) *MockInterviewSessionService_GetInterviewerLastMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetInterviewerLastMessage_Call) RunAndReturn(run func(context.Context, *entities.GetInterviewerLastMessageReq) (*entities.GetInterviewerLastMessageResp, error)) *MockInterviewSessionService_GetInterviewerLastMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastUserTurnIDBySessionIDAndCurrentState provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) GetLastUserTurnIDBySessionIDAndCurrentState(ctx context.Context, req *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLastUserTurnIDBySessionIDAndCurrentState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastUserTurnIDBySessionIDAndCurrentState'
type MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call struct {
	*mock.Call
}

// GetLastUserTurnIDBySessionIDAndCurrentState is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq
func (_e *MockInterviewSessionService_Expecter) GetLastUserTurnIDBySessionIDAndCurrentState(ctx interface{}, req interface{}) *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call {
	return &MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call{Call: _e.mock.On("GetLastUserTurnIDBySessionIDAndCurrentState", ctx, req)}
}

func (_c *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call) Run(run func(ctx context.Context, req *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq)) *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call) Return(_a0 string, _a1 error) *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call) RunAndReturn(run func(context.Context, *entities.GetLastUserTurnIDBySessionIDAndCurrentStateReq) (string, error)) *MockInterviewSessionService_GetLastUserTurnIDBySessionIDAndCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionStartedAtAndEndedAt provides a mock function with given fields: ctx, sessionID
func (_m *MockInterviewSessionService) GetSessionStartedAtAndEndedAt(ctx context.Context, sessionID string) (map[string]string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionStartedAtAndEndedAt")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionStartedAtAndEndedAt'
type MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call struct {
	*mock.Call
}

// GetSessionStartedAtAndEndedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockInterviewSessionService_Expecter) GetSessionStartedAtAndEndedAt(ctx interface{}, sessionID interface{}) *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call {
	return &MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call{Call: _e.mock.On("GetSessionStartedAtAndEndedAt", ctx, sessionID)}
}

func (_c *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call) Run(run func(ctx context.Context, sessionID string)) *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call) Return(_a0 map[string]string, _a1 error) *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *MockInterviewSessionService_GetSessionStartedAtAndEndedAt_Call {
	_c.Call.Return(run)
	return _c
}

// InitialFirstCurrentStateSession provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) InitialFirstCurrentStateSession(ctx context.Context, req *entities.InitialFirstCurrentStateSessionReq) (*entities.InitialFirstCurrentStateSessionResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitialFirstCurrentStateSession")
	}

	var r0 *entities.InitialFirstCurrentStateSessionResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.InitialFirstCurrentStateSessionReq) (*entities.InitialFirstCurrentStateSessionResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.InitialFirstCurrentStateSessionReq) *entities.InitialFirstCurrentStateSessionResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.InitialFirstCurrentStateSessionResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.InitialFirstCurrentStateSessionReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_InitialFirstCurrentStateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitialFirstCurrentStateSession'
type MockInterviewSessionService_InitialFirstCurrentStateSession_Call struct {
	*mock.Call
}

// InitialFirstCurrentStateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.InitialFirstCurrentStateSessionReq
func (_e *MockInterviewSessionService_Expecter) InitialFirstCurrentStateSession(ctx interface{}, req interface{}) *MockInterviewSessionService_InitialFirstCurrentStateSession_Call {
	return &MockInterviewSessionService_InitialFirstCurrentStateSession_Call{Call: _e.mock.On("InitialFirstCurrentStateSession", ctx, req)}
}

func (_c *MockInterviewSessionService_InitialFirstCurrentStateSession_Call) Run(run func(ctx context.Context, req *entities.InitialFirstCurrentStateSessionReq)) *MockInterviewSessionService_InitialFirstCurrentStateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.InitialFirstCurrentStateSessionReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_InitialFirstCurrentStateSession_Call) Return(_a0 *entities.InitialFirstCurrentStateSessionResp, _a1 error) *MockInterviewSessionService_InitialFirstCurrentStateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_InitialFirstCurrentStateSession_Call) RunAndReturn(run func(context.Context, *entities.InitialFirstCurrentStateSessionReq) (*entities.InitialFirstCurrentStateSessionResp, error)) *MockInterviewSessionService_InitialFirstCurrentStateSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsSessionValid provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) IsSessionValid(ctx context.Context, req *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IsSessionValid")
	}

	var r0 *entities.IsSessionValidResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.IsSessionValidReq) *entities.IsSessionValidResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IsSessionValidResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.IsSessionValidReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_IsSessionValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSessionValid'
type MockInterviewSessionService_IsSessionValid_Call struct {
	*mock.Call
}

// IsSessionValid is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.IsSessionValidReq
func (_e *MockInterviewSessionService_Expecter) IsSessionValid(ctx interface{}, req interface{}) *MockInterviewSessionService_IsSessionValid_Call {
	return &MockInterviewSessionService_IsSessionValid_Call{Call: _e.mock.On("IsSessionValid", ctx, req)}
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) Run(run func(ctx context.Context, req *entities.IsSessionValidReq)) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.IsSessionValidReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) Return(_a0 *entities.IsSessionValidResp, _a1 error) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_IsSessionValid_Call) RunAndReturn(run func(context.Context, *entities.IsSessionValidReq) (*entities.IsSessionValidResp, error)) *MockInterviewSessionService_IsSessionValid_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewSessionsByUserIDWithCursor provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) ListInterviewSessionsByUserIDWithCursor(ctx context.Context, req *entities.ListInterviewSessionsByUserIDWithCursorReq) (*entities.ListInterviewSessionsByUserIDResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewSessionsByUserIDWithCursor")
	}

	var r0 *entities.ListInterviewSessionsByUserIDResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithCursorReq) (*entities.ListInterviewSessionsByUserIDResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithCursorReq) *entities.ListInterviewSessionsByUserIDResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ListInterviewSessionsByUserIDResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithCursorReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewSessionsByUserIDWithCursor'
type MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call struct {
	*mock.Call
}

// ListInterviewSessionsByUserIDWithCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.ListInterviewSessionsByUserIDWithCursorReq
func (_e *MockInterviewSessionService_Expecter) ListInterviewSessionsByUserIDWithCursor(ctx interface{}, req interface{}) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call {
	return &MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call{Call: _e.mock.On("ListInterviewSessionsByUserIDWithCursor", ctx, req)}
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call) Run(run func(ctx context.Context, req *entities.ListInterviewSessionsByUserIDWithCursorReq)) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.ListInterviewSessionsByUserIDWithCursorReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call) Return(_a0 *entities.ListInterviewSessionsByUserIDResp, _a1 error) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call) RunAndReturn(run func(context.Context, *entities.ListInterviewSessionsByUserIDWithCursorReq) (*entities.ListInterviewSessionsByUserIDResp, error)) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithCursor_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewSessionsByUserIDWithJumpPagination provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) ListInterviewSessionsByUserIDWithJumpPagination(ctx context.Context, req *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq) (*entities.ListInterviewSessionsByUserIDResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewSessionsByUserIDWithJumpPagination")
	}

	var r0 *entities.ListInterviewSessionsByUserIDResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq) (*entities.ListInterviewSessionsByUserIDResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq) *entities.ListInterviewSessionsByUserIDResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ListInterviewSessionsByUserIDResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewSessionsByUserIDWithJumpPagination'
type MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call struct {
	*mock.Call
}

// ListInterviewSessionsByUserIDWithJumpPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq
func (_e *MockInterviewSessionService_Expecter) ListInterviewSessionsByUserIDWithJumpPagination(ctx interface{}, req interface{}) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	return &MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call{Call: _e.mock.On("ListInterviewSessionsByUserIDWithJumpPagination", ctx, req)}
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call) Run(run func(ctx context.Context, req *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq)) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.ListInterviewSessionsByUserIDWithJumpPaginationReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call) Return(_a0 *entities.ListInterviewSessionsByUserIDResp, _a1 error) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call) RunAndReturn(run func(context.Context, *entities.ListInterviewSessionsByUserIDWithJumpPaginationReq) (*entities.ListInterviewSessionsByUserIDResp, error)) *MockInterviewSessionService_ListInterviewSessionsByUserIDWithJumpPagination_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionEndTime provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) SetSessionEndTime(ctx context.Context, req *entities.SetSessionEndTimeReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetSessionEndTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SetSessionEndTimeReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_SetSessionEndTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionEndTime'
type MockInterviewSessionService_SetSessionEndTime_Call struct {
	*mock.Call
}

// SetSessionEndTime is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.SetSessionEndTimeReq
func (_e *MockInterviewSessionService_Expecter) SetSessionEndTime(ctx interface{}, req interface{}) *MockInterviewSessionService_SetSessionEndTime_Call {
	return &MockInterviewSessionService_SetSessionEndTime_Call{Call: _e.mock.On("SetSessionEndTime", ctx, req)}
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) Run(run func(ctx context.Context, req *entities.SetSessionEndTimeReq)) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SetSessionEndTimeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) Return(_a0 error) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_SetSessionEndTime_Call) RunAndReturn(run func(context.Context, *entities.SetSessionEndTimeReq) error) *MockInterviewSessionService_SetSessionEndTime_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionStartTime provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) SetSessionStartTime(ctx context.Context, req *entities.SetSessionStartTimeReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetSessionStartTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SetSessionStartTimeReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_SetSessionStartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionStartTime'
type MockInterviewSessionService_SetSessionStartTime_Call struct {
	*mock.Call
}

// SetSessionStartTime is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.SetSessionStartTimeReq
func (_e *MockInterviewSessionService_Expecter) SetSessionStartTime(ctx interface{}, req interface{}) *MockInterviewSessionService_SetSessionStartTime_Call {
	return &MockInterviewSessionService_SetSessionStartTime_Call{Call: _e.mock.On("SetSessionStartTime", ctx, req)}
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) Run(run func(ctx context.Context, req *entities.SetSessionStartTimeReq)) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SetSessionStartTimeReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) Return(_a0 error) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_SetSessionStartTime_Call) RunAndReturn(run func(context.Context, *entities.SetSessionStartTimeReq) error) *MockInterviewSessionService_SetSessionStartTime_Call {
	_c.Call.Return(run)
	return _c
}

// StartConversationBySessionID provides a mock function with given fields: ctx, sessionId
func (_m *MockInterviewSessionService) StartConversationBySessionID(ctx context.Context, sessionId string) error {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for StartConversationBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_StartConversationBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartConversationBySessionID'
type MockInterviewSessionService_StartConversationBySessionID_Call struct {
	*mock.Call
}

// StartConversationBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionId string
func (_e *MockInterviewSessionService_Expecter) StartConversationBySessionID(ctx interface{}, sessionId interface{}) *MockInterviewSessionService_StartConversationBySessionID_Call {
	return &MockInterviewSessionService_StartConversationBySessionID_Call{Call: _e.mock.On("StartConversationBySessionID", ctx, sessionId)}
}

func (_c *MockInterviewSessionService_StartConversationBySessionID_Call) Run(run func(ctx context.Context, sessionId string)) *MockInterviewSessionService_StartConversationBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_StartConversationBySessionID_Call) Return(_a0 error) *MockInterviewSessionService_StartConversationBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_StartConversationBySessionID_Call) RunAndReturn(run func(context.Context, string) error) *MockInterviewSessionService_StartConversationBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCurrentStateSessionAndLastTurnID provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) UpdateCurrentStateSessionAndLastTurnID(ctx context.Context, req *entities.UpdateCurrentStateSessionAndLastTurnIDReq) (*entities.UpdateCurrentStateSessionResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurrentStateSessionAndLastTurnID")
	}

	var r0 *entities.UpdateCurrentStateSessionResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UpdateCurrentStateSessionAndLastTurnIDReq) (*entities.UpdateCurrentStateSessionResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UpdateCurrentStateSessionAndLastTurnIDReq) *entities.UpdateCurrentStateSessionResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UpdateCurrentStateSessionResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.UpdateCurrentStateSessionAndLastTurnIDReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCurrentStateSessionAndLastTurnID'
type MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call struct {
	*mock.Call
}

// UpdateCurrentStateSessionAndLastTurnID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.UpdateCurrentStateSessionAndLastTurnIDReq
func (_e *MockInterviewSessionService_Expecter) UpdateCurrentStateSessionAndLastTurnID(ctx interface{}, req interface{}) *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call {
	return &MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call{Call: _e.mock.On("UpdateCurrentStateSessionAndLastTurnID", ctx, req)}
}

func (_c *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call) Run(run func(ctx context.Context, req *entities.UpdateCurrentStateSessionAndLastTurnIDReq)) *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.UpdateCurrentStateSessionAndLastTurnIDReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call) Return(_a0 *entities.UpdateCurrentStateSessionResp, _a1 error) *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call) RunAndReturn(run func(context.Context, *entities.UpdateCurrentStateSessionAndLastTurnIDReq) (*entities.UpdateCurrentStateSessionResp, error)) *MockInterviewSessionService_UpdateCurrentStateSessionAndLastTurnID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterviewSessionStatus provides a mock function with given fields: ctx, req
func (_m *MockInterviewSessionService) UpdateInterviewSessionStatus(ctx context.Context, req *entities.UpdateInterviewSessionStatusReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterviewSessionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UpdateInterviewSessionStatusReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_UpdateInterviewSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterviewSessionStatus'
type MockInterviewSessionService_UpdateInterviewSessionStatus_Call struct {
	*mock.Call
}

// UpdateInterviewSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.UpdateInterviewSessionStatusReq
func (_e *MockInterviewSessionService_Expecter) UpdateInterviewSessionStatus(ctx interface{}, req interface{}) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	return &MockInterviewSessionService_UpdateInterviewSessionStatus_Call{Call: _e.mock.On("UpdateInterviewSessionStatus", ctx, req)}
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) Run(run func(ctx context.Context, req *entities.UpdateInterviewSessionStatusReq)) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.UpdateInterviewSessionStatusReq))
	})
	return _c
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) Return(_a0 error) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_UpdateInterviewSessionStatus_Call) RunAndReturn(run func(context.Context, *entities.UpdateInterviewSessionStatusReq) error) *MockInterviewSessionService_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionStatus provides a mock function with given fields: ctx, sessionIDReq, status
func (_m *MockInterviewSessionService) UpdateSessionStatus(ctx context.Context, sessionIDReq string, status string) error {
	ret := _m.Called(ctx, sessionIDReq, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionIDReq, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterviewSessionService_UpdateSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionStatus'
type MockInterviewSessionService_UpdateSessionStatus_Call struct {
	*mock.Call
}

// UpdateSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDReq string
//   - status string
func (_e *MockInterviewSessionService_Expecter) UpdateSessionStatus(ctx interface{}, sessionIDReq interface{}, status interface{}) *MockInterviewSessionService_UpdateSessionStatus_Call {
	return &MockInterviewSessionService_UpdateSessionStatus_Call{Call: _e.mock.On("UpdateSessionStatus", ctx, sessionIDReq, status)}
}

func (_c *MockInterviewSessionService_UpdateSessionStatus_Call) Run(run func(ctx context.Context, sessionIDReq string, status string)) *MockInterviewSessionService_UpdateSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInterviewSessionService_UpdateSessionStatus_Call) Return(_a0 error) *MockInterviewSessionService_UpdateSessionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterviewSessionService_UpdateSessionStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInterviewSessionService_UpdateSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterviewSessionService creates a new instance of MockInterviewSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterviewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterviewSessionService {
	mock := &MockInterviewSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
