// Code generated by mockery v2.53.3. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/interview-simulation/interview-backend-server/internal/entities"
)

// MockReviewCommentService is an autogenerated mock type for the ReviewCommentService type
type MockReviewCommentService struct {
	mock.Mock
}

type MockReviewCommentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewCommentService) EXPECT() *MockReviewCommentService_Expecter {
	return &MockReviewCommentService_Expecter{mock: &_m.Mock}
}

// CreateReviewComment provides a mock function with given fields: ctx, req
func (_m *MockReviewCommentService) CreateReviewComment(ctx context.Context, req *entities.CreateReviewCommentReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReviewComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CreateReviewCommentReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewCommentService_CreateReviewComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReviewComment'
type MockReviewCommentService_CreateReviewComment_Call struct {
	*mock.Call
}

// CreateReviewComment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.CreateReviewCommentReq
func (_e *MockReviewCommentService_Expecter) CreateReviewComment(ctx interface{}, req interface{}) *MockReviewCommentService_CreateReviewComment_Call {
	return &MockReviewCommentService_CreateReviewComment_Call{Call: _e.mock.On("CreateReviewComment", ctx, req)}
}

func (_c *MockReviewCommentService_CreateReviewComment_Call) Run(run func(ctx context.Context, req *entities.CreateReviewCommentReq)) *MockReviewCommentService_CreateReviewComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CreateReviewCommentReq))
	})
	return _c
}

func (_c *MockReviewCommentService_CreateReviewComment_Call) Return(_a0 error) *MockReviewCommentService_CreateReviewComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewCommentService_CreateReviewComment_Call) RunAndReturn(run func(context.Context, *entities.CreateReviewCommentReq) error) *MockReviewCommentService_CreateReviewComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewCommentService creates a new instance of MockReviewCommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewCommentService {
	mock := &MockReviewCommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
