// Code generated by mockery v2.53.3. DO NOT EDIT.

package services

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	websocket "gitlab.com/interview-simulation/interview-backend-server/internal/infras/websocket"
)

// MockWebSocketService is an autogenerated mock type for the WebSocketService type
type MockWebSocketService struct {
	mock.Mock
}

type MockWebSocketService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebSocketService) EXPECT() *MockWebSocketService_Expecter {
	return &MockWebSocketService_Expecter{mock: &_m.Mock}
}

// HandleWebSocket provides a mock function with given fields: ctx, c
func (_m *MockWebSocketService) HandleWebSocket(ctx context.Context, c *gin.Context) (*websocket.WebSocketServer, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebSocket")
	}

	var r0 *websocket.WebSocketServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gin.Context) (*websocket.WebSocketServer, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gin.Context) *websocket.WebSocketServer); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.WebSocketServer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gin.Context) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebSocketService_HandleWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebSocket'
type MockWebSocketService_HandleWebSocket_Call struct {
	*mock.Call
}

// HandleWebSocket is a helper method to define mock.On call
//   - ctx context.Context
//   - c *gin.Context
func (_e *MockWebSocketService_Expecter) HandleWebSocket(ctx interface{}, c interface{}) *MockWebSocketService_HandleWebSocket_Call {
	return &MockWebSocketService_HandleWebSocket_Call{Call: _e.mock.On("HandleWebSocket", ctx, c)}
}

func (_c *MockWebSocketService_HandleWebSocket_Call) Run(run func(ctx context.Context, c *gin.Context)) *MockWebSocketService_HandleWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gin.Context))
	})
	return _c
}

func (_c *MockWebSocketService_HandleWebSocket_Call) Return(_a0 *websocket.WebSocketServer, _a1 error) *MockWebSocketService_HandleWebSocket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebSocketService_HandleWebSocket_Call) RunAndReturn(run func(context.Context, *gin.Context) (*websocket.WebSocketServer, error)) *MockWebSocketService_HandleWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebSocketService creates a new instance of MockWebSocketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebSocketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebSocketService {
	mock := &MockWebSocketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
