// Code generated by mockery v2.53.3. DO NOT EDIT.

package sqlc

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/interview-simulation/interview-backend-server/internal/db/sqlc"

	uuid "github.com/google/uuid"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CheckInterviewSessionExists provides a mock function with given fields: ctx, id
func (_m *MockStore) CheckInterviewSessionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckInterviewSessionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CheckInterviewSessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInterviewSessionExists'
type MockStore_CheckInterviewSessionExists_Call struct {
	*mock.Call
}

// CheckInterviewSessionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) CheckInterviewSessionExists(ctx interface{}, id interface{}) *MockStore_CheckInterviewSessionExists_Call {
	return &MockStore_CheckInterviewSessionExists_Call{Call: _e.mock.On("CheckInterviewSessionExists", ctx, id)}
}

func (_c *MockStore_CheckInterviewSessionExists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_CheckInterviewSessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_CheckInterviewSessionExists_Call) Return(_a0 bool, _a1 error) *MockStore_CheckInterviewSessionExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CheckInterviewSessionExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockStore_CheckInterviewSessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIsDefaultResumeExistsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockStore) CheckIsDefaultResumeExistsByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckIsDefaultResumeExistsByUserID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CheckIsDefaultResumeExistsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIsDefaultResumeExistsByUserID'
type MockStore_CheckIsDefaultResumeExistsByUserID_Call struct {
	*mock.Call
}

// CheckIsDefaultResumeExistsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) CheckIsDefaultResumeExistsByUserID(ctx interface{}, userID interface{}) *MockStore_CheckIsDefaultResumeExistsByUserID_Call {
	return &MockStore_CheckIsDefaultResumeExistsByUserID_Call{Call: _e.mock.On("CheckIsDefaultResumeExistsByUserID", ctx, userID)}
}

func (_c *MockStore_CheckIsDefaultResumeExistsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_CheckIsDefaultResumeExistsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_CheckIsDefaultResumeExistsByUserID_Call) Return(_a0 bool, _a1 error) *MockStore_CheckIsDefaultResumeExistsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CheckIsDefaultResumeExistsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockStore_CheckIsDefaultResumeExistsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIsEmailExists provides a mock function with given fields: ctx, email
func (_m *MockStore) CheckIsEmailExists(ctx context.Context, email string) (db.Users, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckIsEmailExists")
	}

	var r0 db.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Users, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Users); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(db.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CheckIsEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIsEmailExists'
type MockStore_CheckIsEmailExists_Call struct {
	*mock.Call
}

// CheckIsEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStore_Expecter) CheckIsEmailExists(ctx interface{}, email interface{}) *MockStore_CheckIsEmailExists_Call {
	return &MockStore_CheckIsEmailExists_Call{Call: _e.mock.On("CheckIsEmailExists", ctx, email)}
}

func (_c *MockStore_CheckIsEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockStore_CheckIsEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_CheckIsEmailExists_Call) Return(_a0 db.Users, _a1 error) *MockStore_CheckIsEmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CheckIsEmailExists_Call) RunAndReturn(run func(context.Context, string) (db.Users, error)) *MockStore_CheckIsEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIsUserExistsByID provides a mock function with given fields: ctx, id
func (_m *MockStore) CheckIsUserExistsByID(ctx context.Context, id uuid.UUID) (db.Users, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckIsUserExistsByID")
	}

	var r0 db.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Users, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Users); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CheckIsUserExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIsUserExistsByID'
type MockStore_CheckIsUserExistsByID_Call struct {
	*mock.Call
}

// CheckIsUserExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) CheckIsUserExistsByID(ctx interface{}, id interface{}) *MockStore_CheckIsUserExistsByID_Call {
	return &MockStore_CheckIsUserExistsByID_Call{Call: _e.mock.On("CheckIsUserExistsByID", ctx, id)}
}

func (_c *MockStore_CheckIsUserExistsByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_CheckIsUserExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_CheckIsUserExistsByID_Call) Return(_a0 db.Users, _a1 error) *MockStore_CheckIsUserExistsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CheckIsUserExistsByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Users, error)) *MockStore_CheckIsUserExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvaluationCriterion provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateEvaluationCriterion(ctx context.Context, arg db.CreateEvaluationCriterionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvaluationCriterion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEvaluationCriterionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateEvaluationCriterion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvaluationCriterion'
type MockStore_CreateEvaluationCriterion_Call struct {
	*mock.Call
}

// CreateEvaluationCriterion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateEvaluationCriterionParams
func (_e *MockStore_Expecter) CreateEvaluationCriterion(ctx interface{}, arg interface{}) *MockStore_CreateEvaluationCriterion_Call {
	return &MockStore_CreateEvaluationCriterion_Call{Call: _e.mock.On("CreateEvaluationCriterion", ctx, arg)}
}

func (_c *MockStore_CreateEvaluationCriterion_Call) Run(run func(ctx context.Context, arg db.CreateEvaluationCriterionParams)) *MockStore_CreateEvaluationCriterion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateEvaluationCriterionParams))
	})
	return _c
}

func (_c *MockStore_CreateEvaluationCriterion_Call) Return(_a0 error) *MockStore_CreateEvaluationCriterion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateEvaluationCriterion_Call) RunAndReturn(run func(context.Context, db.CreateEvaluationCriterionParams) error) *MockStore_CreateEvaluationCriterion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvaluationRubric provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateEvaluationRubric(ctx context.Context, arg db.CreateEvaluationRubricParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvaluationRubric")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEvaluationRubricParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateEvaluationRubric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvaluationRubric'
type MockStore_CreateEvaluationRubric_Call struct {
	*mock.Call
}

// CreateEvaluationRubric is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateEvaluationRubricParams
func (_e *MockStore_Expecter) CreateEvaluationRubric(ctx interface{}, arg interface{}) *MockStore_CreateEvaluationRubric_Call {
	return &MockStore_CreateEvaluationRubric_Call{Call: _e.mock.On("CreateEvaluationRubric", ctx, arg)}
}

func (_c *MockStore_CreateEvaluationRubric_Call) Run(run func(ctx context.Context, arg db.CreateEvaluationRubricParams)) *MockStore_CreateEvaluationRubric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateEvaluationRubricParams))
	})
	return _c
}

func (_c *MockStore_CreateEvaluationRubric_Call) Return(_a0 error) *MockStore_CreateEvaluationRubric_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateEvaluationRubric_Call) RunAndReturn(run func(context.Context, db.CreateEvaluationRubricParams) error) *MockStore_CreateEvaluationRubric_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewSession provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateInterviewSession(ctx context.Context, arg db.CreateInterviewSessionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateInterviewSessionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewSession'
type MockStore_CreateInterviewSession_Call struct {
	*mock.Call
}

// CreateInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateInterviewSessionParams
func (_e *MockStore_Expecter) CreateInterviewSession(ctx interface{}, arg interface{}) *MockStore_CreateInterviewSession_Call {
	return &MockStore_CreateInterviewSession_Call{Call: _e.mock.On("CreateInterviewSession", ctx, arg)}
}

func (_c *MockStore_CreateInterviewSession_Call) Run(run func(ctx context.Context, arg db.CreateInterviewSessionParams)) *MockStore_CreateInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateInterviewSessionParams))
	})
	return _c
}

func (_c *MockStore_CreateInterviewSession_Call) Return(_a0 error) *MockStore_CreateInterviewSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateInterviewSession_Call) RunAndReturn(run func(context.Context, db.CreateInterviewSessionParams) error) *MockStore_CreateInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterviewTurn provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateInterviewTurn(ctx context.Context, arg db.CreateInterviewTurnParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterviewTurn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateInterviewTurnParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateInterviewTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterviewTurn'
type MockStore_CreateInterviewTurn_Call struct {
	*mock.Call
}

// CreateInterviewTurn is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateInterviewTurnParams
func (_e *MockStore_Expecter) CreateInterviewTurn(ctx interface{}, arg interface{}) *MockStore_CreateInterviewTurn_Call {
	return &MockStore_CreateInterviewTurn_Call{Call: _e.mock.On("CreateInterviewTurn", ctx, arg)}
}

func (_c *MockStore_CreateInterviewTurn_Call) Run(run func(ctx context.Context, arg db.CreateInterviewTurnParams)) *MockStore_CreateInterviewTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateInterviewTurnParams))
	})
	return _c
}

func (_c *MockStore_CreateInterviewTurn_Call) Return(_a0 error) *MockStore_CreateInterviewTurn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateInterviewTurn_Call) RunAndReturn(run func(context.Context, db.CreateInterviewTurnParams) error) *MockStore_CreateInterviewTurn_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJobRequirement provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateJobRequirement(ctx context.Context, arg db.CreateJobRequirementParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobRequirement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateJobRequirementParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateJobRequirement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobRequirement'
type MockStore_CreateJobRequirement_Call struct {
	*mock.Call
}

// CreateJobRequirement is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateJobRequirementParams
func (_e *MockStore_Expecter) CreateJobRequirement(ctx interface{}, arg interface{}) *MockStore_CreateJobRequirement_Call {
	return &MockStore_CreateJobRequirement_Call{Call: _e.mock.On("CreateJobRequirement", ctx, arg)}
}

func (_c *MockStore_CreateJobRequirement_Call) Run(run func(ctx context.Context, arg db.CreateJobRequirementParams)) *MockStore_CreateJobRequirement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateJobRequirementParams))
	})
	return _c
}

func (_c *MockStore_CreateJobRequirement_Call) Return(_a0 error) *MockStore_CreateJobRequirement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateJobRequirement_Call) RunAndReturn(run func(context.Context, db.CreateJobRequirementParams) error) *MockStore_CreateJobRequirement_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResetToken provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateResetToken(ctx context.Context, arg db.CreateResetTokenParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateResetTokenParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResetToken'
type MockStore_CreateResetToken_Call struct {
	*mock.Call
}

// CreateResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateResetTokenParams
func (_e *MockStore_Expecter) CreateResetToken(ctx interface{}, arg interface{}) *MockStore_CreateResetToken_Call {
	return &MockStore_CreateResetToken_Call{Call: _e.mock.On("CreateResetToken", ctx, arg)}
}

func (_c *MockStore_CreateResetToken_Call) Run(run func(ctx context.Context, arg db.CreateResetTokenParams)) *MockStore_CreateResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateResetTokenParams))
	})
	return _c
}

func (_c *MockStore_CreateResetToken_Call) Return(_a0 error) *MockStore_CreateResetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateResetToken_Call) RunAndReturn(run func(context.Context, db.CreateResetTokenParams) error) *MockStore_CreateResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResume provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateResume(ctx context.Context, arg db.CreateResumeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateResume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateResumeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResume'
type MockStore_CreateResume_Call struct {
	*mock.Call
}

// CreateResume is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateResumeParams
func (_e *MockStore_Expecter) CreateResume(ctx interface{}, arg interface{}) *MockStore_CreateResume_Call {
	return &MockStore_CreateResume_Call{Call: _e.mock.On("CreateResume", ctx, arg)}
}

func (_c *MockStore_CreateResume_Call) Run(run func(ctx context.Context, arg db.CreateResumeParams)) *MockStore_CreateResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateResumeParams))
	})
	return _c
}

func (_c *MockStore_CreateResume_Call) Return(_a0 error) *MockStore_CreateResume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateResume_Call) RunAndReturn(run func(context.Context, db.CreateResumeParams) error) *MockStore_CreateResume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateSession(ctx context.Context, arg db.CreateSessionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateSessionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateSessionParams
func (_e *MockStore_Expecter) CreateSession(ctx interface{}, arg interface{}) *MockStore_CreateSession_Call {
	return &MockStore_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, arg)}
}

func (_c *MockStore_CreateSession_Call) Run(run func(ctx context.Context, arg db.CreateSessionParams)) *MockStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateSessionParams))
	})
	return _c
}

func (_c *MockStore_CreateSession_Call) Return(_a0 error) *MockStore_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateSession_Call) RunAndReturn(run func(context.Context, db.CreateSessionParams) error) *MockStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.Users, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.Users, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.Users); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *MockStore_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockStore_CreateUser_Call {
	return &MockStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockStore_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockStore_CreateUser_Call) Return(_a0 db.Users, _a1 error) *MockStore_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.Users, error)) *MockStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobRequirement provides a mock function with given fields: ctx, id
func (_m *MockStore) DeleteJobRequirement(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobRequirement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeleteJobRequirement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobRequirement'
type MockStore_DeleteJobRequirement_Call struct {
	*mock.Call
}

// DeleteJobRequirement is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) DeleteJobRequirement(ctx interface{}, id interface{}) *MockStore_DeleteJobRequirement_Call {
	return &MockStore_DeleteJobRequirement_Call{Call: _e.mock.On("DeleteJobRequirement", ctx, id)}
}

func (_c *MockStore_DeleteJobRequirement_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_DeleteJobRequirement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_DeleteJobRequirement_Call) Return(_a0 error) *MockStore_DeleteJobRequirement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeleteJobRequirement_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_DeleteJobRequirement_Call {
	_c.Call.Return(run)
	return _c
}

// EndInterviewSession provides a mock function with given fields: ctx, arg
func (_m *MockStore) EndInterviewSession(ctx context.Context, arg db.EndInterviewSessionParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EndInterviewSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.EndInterviewSessionParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.EndInterviewSessionParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.EndInterviewSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_EndInterviewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndInterviewSession'
type MockStore_EndInterviewSession_Call struct {
	*mock.Call
}

// EndInterviewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.EndInterviewSessionParams
func (_e *MockStore_Expecter) EndInterviewSession(ctx interface{}, arg interface{}) *MockStore_EndInterviewSession_Call {
	return &MockStore_EndInterviewSession_Call{Call: _e.mock.On("EndInterviewSession", ctx, arg)}
}

func (_c *MockStore_EndInterviewSession_Call) Run(run func(ctx context.Context, arg db.EndInterviewSessionParams)) *MockStore_EndInterviewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.EndInterviewSessionParams))
	})
	return _c
}

func (_c *MockStore_EndInterviewSession_Call) Return(_a0 int64, _a1 error) *MockStore_EndInterviewSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_EndInterviewSession_Call) RunAndReturn(run func(context.Context, db.EndInterviewSessionParams) (int64, error)) *MockStore_EndInterviewSession_Call {
	_c.Call.Return(run)
	return _c
}

// ExecTx provides a mock function with given fields: ctx, fn
func (_m *MockStore) ExecTx(ctx context.Context, fn func(*db.Queries) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*db.Queries) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_ExecTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecTx'
type MockStore_ExecTx_Call struct {
	*mock.Call
}

// ExecTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(*db.Queries) error
func (_e *MockStore_Expecter) ExecTx(ctx interface{}, fn interface{}) *MockStore_ExecTx_Call {
	return &MockStore_ExecTx_Call{Call: _e.mock.On("ExecTx", ctx, fn)}
}

func (_c *MockStore_ExecTx_Call) Run(run func(ctx context.Context, fn func(*db.Queries) error)) *MockStore_ExecTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(*db.Queries) error))
	})
	return _c
}

func (_c *MockStore_ExecTx_Call) Return(_a0 error) *MockStore_ExecTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_ExecTx_Call) RunAndReturn(run func(context.Context, func(*db.Queries) error) error) *MockStore_ExecTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultResumeByUserID provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetDefaultResumeByUserID(ctx context.Context, userID uuid.UUID) (db.Resumes, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultResumeByUserID")
	}

	var r0 db.Resumes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Resumes, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Resumes); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(db.Resumes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetDefaultResumeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultResumeByUserID'
type MockStore_GetDefaultResumeByUserID_Call struct {
	*mock.Call
}

// GetDefaultResumeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) GetDefaultResumeByUserID(ctx interface{}, userID interface{}) *MockStore_GetDefaultResumeByUserID_Call {
	return &MockStore_GetDefaultResumeByUserID_Call{Call: _e.mock.On("GetDefaultResumeByUserID", ctx, userID)}
}

func (_c *MockStore_GetDefaultResumeByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_GetDefaultResumeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetDefaultResumeByUserID_Call) Return(_a0 db.Resumes, _a1 error) *MockStore_GetDefaultResumeByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetDefaultResumeByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Resumes, error)) *MockStore_GetDefaultResumeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxTurnNoBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockStore) GetMaxTurnNoBySessionID(ctx context.Context, sessionID uuid.UUID) (interface{}, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxTurnNoBySessionID")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (interface{}, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) interface{}); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetMaxTurnNoBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxTurnNoBySessionID'
type MockStore_GetMaxTurnNoBySessionID_Call struct {
	*mock.Call
}

// GetMaxTurnNoBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockStore_Expecter) GetMaxTurnNoBySessionID(ctx interface{}, sessionID interface{}) *MockStore_GetMaxTurnNoBySessionID_Call {
	return &MockStore_GetMaxTurnNoBySessionID_Call{Call: _e.mock.On("GetMaxTurnNoBySessionID", ctx, sessionID)}
}

func (_c *MockStore_GetMaxTurnNoBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockStore_GetMaxTurnNoBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetMaxTurnNoBySessionID_Call) Return(_a0 interface{}, _a1 error) *MockStore_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetMaxTurnNoBySessionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (interface{}, error)) *MockStore_GetMaxTurnNoBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResetToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockStore) GetResetToken(ctx context.Context, tokenHash string) (db.ResetTokens, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetResetToken")
	}

	var r0 db.ResetTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.ResetTokens, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.ResetTokens); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(db.ResetTokens)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResetToken'
type MockStore_GetResetToken_Call struct {
	*mock.Call
}

// GetResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockStore_Expecter) GetResetToken(ctx interface{}, tokenHash interface{}) *MockStore_GetResetToken_Call {
	return &MockStore_GetResetToken_Call{Call: _e.mock.On("GetResetToken", ctx, tokenHash)}
}

func (_c *MockStore_GetResetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockStore_GetResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetResetToken_Call) Return(_a0 db.ResetTokens, _a1 error) *MockStore_GetResetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetResetToken_Call) RunAndReturn(run func(context.Context, string) (db.ResetTokens, error)) *MockStore_GetResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetResumeByID provides a mock function with given fields: ctx, id
func (_m *MockStore) GetResumeByID(ctx context.Context, id uuid.UUID) (db.Resumes, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResumeByID")
	}

	var r0 db.Resumes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Resumes, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Resumes); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Resumes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetResumeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResumeByID'
type MockStore_GetResumeByID_Call struct {
	*mock.Call
}

// GetResumeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) GetResumeByID(ctx interface{}, id interface{}) *MockStore_GetResumeByID_Call {
	return &MockStore_GetResumeByID_Call{Call: _e.mock.On("GetResumeByID", ctx, id)}
}

func (_c *MockStore_GetResumeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetResumeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetResumeByID_Call) Return(_a0 db.Resumes, _a1 error) *MockStore_GetResumeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetResumeByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Resumes, error)) *MockStore_GetResumeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function with given fields: ctx, id
func (_m *MockStore) GetSessionByID(ctx context.Context, id uuid.UUID) (db.Sessions, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 db.Sessions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Sessions, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Sessions); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Sessions)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type MockStore_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) GetSessionByID(ctx interface{}, id interface{}) *MockStore_GetSessionByID_Call {
	return &MockStore_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, id)}
}

func (_c *MockStore_GetSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetSessionByID_Call) Return(_a0 db.Sessions, _a1 error) *MockStore_GetSessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetSessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Sessions, error)) *MockStore_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListResumeByUserIDFirstPage provides a mock function with given fields: ctx, userID
func (_m *MockStore) ListResumeByUserIDFirstPage(ctx context.Context, userID uuid.UUID) ([]db.Resumes, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListResumeByUserIDFirstPage")
	}

	var r0 []db.Resumes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.Resumes, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.Resumes); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Resumes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListResumeByUserIDFirstPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResumeByUserIDFirstPage'
type MockStore_ListResumeByUserIDFirstPage_Call struct {
	*mock.Call
}

// ListResumeByUserIDFirstPage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) ListResumeByUserIDFirstPage(ctx interface{}, userID interface{}) *MockStore_ListResumeByUserIDFirstPage_Call {
	return &MockStore_ListResumeByUserIDFirstPage_Call{Call: _e.mock.On("ListResumeByUserIDFirstPage", ctx, userID)}
}

func (_c *MockStore_ListResumeByUserIDFirstPage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_ListResumeByUserIDFirstPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_ListResumeByUserIDFirstPage_Call) Return(_a0 []db.Resumes, _a1 error) *MockStore_ListResumeByUserIDFirstPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListResumeByUserIDFirstPage_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.Resumes, error)) *MockStore_ListResumeByUserIDFirstPage_Call {
	_c.Call.Return(run)
	return _c
}

// ListResumeByUserIDPaginated provides a mock function with given fields: ctx, arg
func (_m *MockStore) ListResumeByUserIDPaginated(ctx context.Context, arg db.ListResumeByUserIDPaginatedParams) ([]db.Resumes, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListResumeByUserIDPaginated")
	}

	var r0 []db.Resumes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListResumeByUserIDPaginatedParams) ([]db.Resumes, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListResumeByUserIDPaginatedParams) []db.Resumes); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Resumes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListResumeByUserIDPaginatedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListResumeByUserIDPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResumeByUserIDPaginated'
type MockStore_ListResumeByUserIDPaginated_Call struct {
	*mock.Call
}

// ListResumeByUserIDPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListResumeByUserIDPaginatedParams
func (_e *MockStore_Expecter) ListResumeByUserIDPaginated(ctx interface{}, arg interface{}) *MockStore_ListResumeByUserIDPaginated_Call {
	return &MockStore_ListResumeByUserIDPaginated_Call{Call: _e.mock.On("ListResumeByUserIDPaginated", ctx, arg)}
}

func (_c *MockStore_ListResumeByUserIDPaginated_Call) Run(run func(ctx context.Context, arg db.ListResumeByUserIDPaginatedParams)) *MockStore_ListResumeByUserIDPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListResumeByUserIDPaginatedParams))
	})
	return _c
}

func (_c *MockStore_ListResumeByUserIDPaginated_Call) Return(_a0 []db.Resumes, _a1 error) *MockStore_ListResumeByUserIDPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListResumeByUserIDPaginated_Call) RunAndReturn(run func(context.Context, db.ListResumeByUserIDPaginatedParams) ([]db.Resumes, error)) *MockStore_ListResumeByUserIDPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// ResetUserPassword provides a mock function with given fields: ctx, arg
func (_m *MockStore) ResetUserPassword(ctx context.Context, arg db.ResetUserPasswordParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ResetUserPassword")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ResetUserPasswordParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ResetUserPasswordParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ResetUserPasswordParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ResetUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetUserPassword'
type MockStore_ResetUserPassword_Call struct {
	*mock.Call
}

// ResetUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ResetUserPasswordParams
func (_e *MockStore_Expecter) ResetUserPassword(ctx interface{}, arg interface{}) *MockStore_ResetUserPassword_Call {
	return &MockStore_ResetUserPassword_Call{Call: _e.mock.On("ResetUserPassword", ctx, arg)}
}

func (_c *MockStore_ResetUserPassword_Call) Run(run func(ctx context.Context, arg db.ResetUserPasswordParams)) *MockStore_ResetUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ResetUserPasswordParams))
	})
	return _c
}

func (_c *MockStore_ResetUserPassword_Call) Return(_a0 int64, _a1 error) *MockStore_ResetUserPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ResetUserPassword_Call) RunAndReturn(run func(context.Context, db.ResetUserPasswordParams) (int64, error)) *MockStore_ResetUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionByID provides a mock function with given fields: ctx, id
func (_m *MockStore) RevokeSessionByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RevokeSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionByID'
type MockStore_RevokeSessionByID_Call struct {
	*mock.Call
}

// RevokeSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) RevokeSessionByID(ctx interface{}, id interface{}) *MockStore_RevokeSessionByID_Call {
	return &MockStore_RevokeSessionByID_Call{Call: _e.mock.On("RevokeSessionByID", ctx, id)}
}

func (_c *MockStore_RevokeSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_RevokeSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_RevokeSessionByID_Call) Return(_a0 error) *MockStore_RevokeSessionByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RevokeSessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_RevokeSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultResume provides a mock function with given fields: ctx, id
func (_m *MockStore) SetDefaultResume(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultResume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SetDefaultResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultResume'
type MockStore_SetDefaultResume_Call struct {
	*mock.Call
}

// SetDefaultResume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) SetDefaultResume(ctx interface{}, id interface{}) *MockStore_SetDefaultResume_Call {
	return &MockStore_SetDefaultResume_Call{Call: _e.mock.On("SetDefaultResume", ctx, id)}
}

func (_c *MockStore_SetDefaultResume_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_SetDefaultResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_SetDefaultResume_Call) Return(_a0 error) *MockStore_SetDefaultResume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SetDefaultResume_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_SetDefaultResume_Call {
	_c.Call.Return(run)
	return _c
}

// SignInUserByEmailAndPassword provides a mock function with given fields: ctx, arg
func (_m *MockStore) SignInUserByEmailAndPassword(ctx context.Context, arg db.SignInUserByEmailAndPasswordParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SignInUserByEmailAndPassword")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SignInUserByEmailAndPasswordParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SignInUserByEmailAndPasswordParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SignInUserByEmailAndPasswordParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_SignInUserByEmailAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInUserByEmailAndPassword'
type MockStore_SignInUserByEmailAndPassword_Call struct {
	*mock.Call
}

// SignInUserByEmailAndPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.SignInUserByEmailAndPasswordParams
func (_e *MockStore_Expecter) SignInUserByEmailAndPassword(ctx interface{}, arg interface{}) *MockStore_SignInUserByEmailAndPassword_Call {
	return &MockStore_SignInUserByEmailAndPassword_Call{Call: _e.mock.On("SignInUserByEmailAndPassword", ctx, arg)}
}

func (_c *MockStore_SignInUserByEmailAndPassword_Call) Run(run func(ctx context.Context, arg db.SignInUserByEmailAndPasswordParams)) *MockStore_SignInUserByEmailAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SignInUserByEmailAndPasswordParams))
	})
	return _c
}

func (_c *MockStore_SignInUserByEmailAndPassword_Call) Return(_a0 int64, _a1 error) *MockStore_SignInUserByEmailAndPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_SignInUserByEmailAndPassword_Call) RunAndReturn(run func(context.Context, db.SignInUserByEmailAndPasswordParams) (int64, error)) *MockStore_SignInUserByEmailAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetDefaultResume provides a mock function with given fields: ctx, id
func (_m *MockStore) UnsetDefaultResume(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnsetDefaultResume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UnsetDefaultResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetDefaultResume'
type MockStore_UnsetDefaultResume_Call struct {
	*mock.Call
}

// UnsetDefaultResume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) UnsetDefaultResume(ctx interface{}, id interface{}) *MockStore_UnsetDefaultResume_Call {
	return &MockStore_UnsetDefaultResume_Call{Call: _e.mock.On("UnsetDefaultResume", ctx, id)}
}

func (_c *MockStore_UnsetDefaultResume_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_UnsetDefaultResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_UnsetDefaultResume_Call) Return(_a0 error) *MockStore_UnsetDefaultResume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UnsetDefaultResume_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_UnsetDefaultResume_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvaluationCriterion provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateEvaluationCriterion(ctx context.Context, arg db.UpdateEvaluationCriterionParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvaluationCriterion")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateEvaluationCriterionParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateEvaluationCriterionParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateEvaluationCriterionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdateEvaluationCriterion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvaluationCriterion'
type MockStore_UpdateEvaluationCriterion_Call struct {
	*mock.Call
}

// UpdateEvaluationCriterion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateEvaluationCriterionParams
func (_e *MockStore_Expecter) UpdateEvaluationCriterion(ctx interface{}, arg interface{}) *MockStore_UpdateEvaluationCriterion_Call {
	return &MockStore_UpdateEvaluationCriterion_Call{Call: _e.mock.On("UpdateEvaluationCriterion", ctx, arg)}
}

func (_c *MockStore_UpdateEvaluationCriterion_Call) Run(run func(ctx context.Context, arg db.UpdateEvaluationCriterionParams)) *MockStore_UpdateEvaluationCriterion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateEvaluationCriterionParams))
	})
	return _c
}

func (_c *MockStore_UpdateEvaluationCriterion_Call) Return(_a0 int64, _a1 error) *MockStore_UpdateEvaluationCriterion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdateEvaluationCriterion_Call) RunAndReturn(run func(context.Context, db.UpdateEvaluationCriterionParams) (int64, error)) *MockStore_UpdateEvaluationCriterion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterviewSessionStatus provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateInterviewSessionStatus(ctx context.Context, arg db.UpdateInterviewSessionStatusParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterviewSessionStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateInterviewSessionStatusParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateInterviewSessionStatusParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateInterviewSessionStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdateInterviewSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterviewSessionStatus'
type MockStore_UpdateInterviewSessionStatus_Call struct {
	*mock.Call
}

// UpdateInterviewSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateInterviewSessionStatusParams
func (_e *MockStore_Expecter) UpdateInterviewSessionStatus(ctx interface{}, arg interface{}) *MockStore_UpdateInterviewSessionStatus_Call {
	return &MockStore_UpdateInterviewSessionStatus_Call{Call: _e.mock.On("UpdateInterviewSessionStatus", ctx, arg)}
}

func (_c *MockStore_UpdateInterviewSessionStatus_Call) Run(run func(ctx context.Context, arg db.UpdateInterviewSessionStatusParams)) *MockStore_UpdateInterviewSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateInterviewSessionStatusParams))
	})
	return _c
}

func (_c *MockStore_UpdateInterviewSessionStatus_Call) Return(_a0 int64, _a1 error) *MockStore_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdateInterviewSessionStatus_Call) RunAndReturn(run func(context.Context, db.UpdateInterviewSessionStatusParams) (int64, error)) *MockStore_UpdateInterviewSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResetTokenUsed provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateResetTokenUsed(ctx context.Context, arg db.UpdateResetTokenUsedParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResetTokenUsed")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateResetTokenUsedParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateResetTokenUsedParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateResetTokenUsedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdateResetTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResetTokenUsed'
type MockStore_UpdateResetTokenUsed_Call struct {
	*mock.Call
}

// UpdateResetTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateResetTokenUsedParams
func (_e *MockStore_Expecter) UpdateResetTokenUsed(ctx interface{}, arg interface{}) *MockStore_UpdateResetTokenUsed_Call {
	return &MockStore_UpdateResetTokenUsed_Call{Call: _e.mock.On("UpdateResetTokenUsed", ctx, arg)}
}

func (_c *MockStore_UpdateResetTokenUsed_Call) Run(run func(ctx context.Context, arg db.UpdateResetTokenUsedParams)) *MockStore_UpdateResetTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateResetTokenUsedParams))
	})
	return _c
}

func (_c *MockStore_UpdateResetTokenUsed_Call) Return(_a0 int64, _a1 error) *MockStore_UpdateResetTokenUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdateResetTokenUsed_Call) RunAndReturn(run func(context.Context, db.UpdateResetTokenUsedParams) (int64, error)) *MockStore_UpdateResetTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.Users, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 db.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) (db.Users, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) db.Users); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserParams
func (_e *MockStore_Expecter) UpdateUser(ctx interface{}, arg interface{}) *MockStore_UpdateUser_Call {
	return &MockStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *MockStore_UpdateUser_Call) Run(run func(ctx context.Context, arg db.UpdateUserParams)) *MockStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserParams))
	})
	return _c
}

func (_c *MockStore_UpdateUser_Call) Return(_a0 db.Users, _a1 error) *MockStore_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdateUser_Call) RunAndReturn(run func(context.Context, db.UpdateUserParams) (db.Users, error)) *MockStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, id
func (_m *MockStore) VerifyEmail(ctx context.Context, id uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockStore_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) VerifyEmail(ctx interface{}, id interface{}) *MockStore_VerifyEmail_Call {
	return &MockStore_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, id)}
}

func (_c *MockStore_VerifyEmail_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_VerifyEmail_Call) Return(_a0 int64, _a1 error) *MockStore_VerifyEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_VerifyEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockStore_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
