// Code generated by mockery v2.53.3. DO NOT EDIT.

package queue

import (
	context "context"

	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisTaskConsumer is an autogenerated mock type for the RedisTaskConsumer type
type MockRedisTaskConsumer struct {
	mock.Mock
}

type MockRedisTaskConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisTaskConsumer) EXPECT() *MockRedisTaskConsumer_Expecter {
	return &MockRedisTaskConsumer_Expecter{mock: &_m.Mock}
}

// ConsumeTaskDeleteFile provides a mock function with given fields: ctx, task
func (_m *MockRedisTaskConsumer) ConsumeTaskDeleteFile(ctx context.Context, task *asynq.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeTaskDeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *asynq.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeTaskDeleteFile'
type MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call struct {
	*mock.Call
}

// ConsumeTaskDeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - task *asynq.Task
func (_e *MockRedisTaskConsumer_Expecter) ConsumeTaskDeleteFile(ctx interface{}, task interface{}) *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call {
	return &MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call{Call: _e.mock.On("ConsumeTaskDeleteFile", ctx, task)}
}

func (_c *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call) Run(run func(ctx context.Context, task *asynq.Task)) *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*asynq.Task))
	})
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call) Return(_a0 error) *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call) RunAndReturn(run func(context.Context, *asynq.Task) error) *MockRedisTaskConsumer_ConsumeTaskDeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeTaskSendResetPasswordEmail provides a mock function with given fields: ctx, task
func (_m *MockRedisTaskConsumer) ConsumeTaskSendResetPasswordEmail(ctx context.Context, task *asynq.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeTaskSendResetPasswordEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *asynq.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeTaskSendResetPasswordEmail'
type MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call struct {
	*mock.Call
}

// ConsumeTaskSendResetPasswordEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - task *asynq.Task
func (_e *MockRedisTaskConsumer_Expecter) ConsumeTaskSendResetPasswordEmail(ctx interface{}, task interface{}) *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call {
	return &MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call{Call: _e.mock.On("ConsumeTaskSendResetPasswordEmail", ctx, task)}
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call) Run(run func(ctx context.Context, task *asynq.Task)) *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*asynq.Task))
	})
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call) Return(_a0 error) *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call) RunAndReturn(run func(context.Context, *asynq.Task) error) *MockRedisTaskConsumer_ConsumeTaskSendResetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeTaskSendVerifyEmail provides a mock function with given fields: ctx, task
func (_m *MockRedisTaskConsumer) ConsumeTaskSendVerifyEmail(ctx context.Context, task *asynq.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeTaskSendVerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *asynq.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeTaskSendVerifyEmail'
type MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call struct {
	*mock.Call
}

// ConsumeTaskSendVerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - task *asynq.Task
func (_e *MockRedisTaskConsumer_Expecter) ConsumeTaskSendVerifyEmail(ctx interface{}, task interface{}) *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call {
	return &MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call{Call: _e.mock.On("ConsumeTaskSendVerifyEmail", ctx, task)}
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call) Run(run func(ctx context.Context, task *asynq.Task)) *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*asynq.Task))
	})
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call) Return(_a0 error) *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call) RunAndReturn(run func(context.Context, *asynq.Task) error) *MockRedisTaskConsumer_ConsumeTaskSendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockRedisTaskConsumer) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisTaskConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRedisTaskConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisTaskConsumer_Expecter) Start(ctx interface{}) *MockRedisTaskConsumer_Start_Call {
	return &MockRedisTaskConsumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockRedisTaskConsumer_Start_Call) Run(run func(ctx context.Context)) *MockRedisTaskConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRedisTaskConsumer_Start_Call) Return(_a0 error) *MockRedisTaskConsumer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisTaskConsumer_Start_Call) RunAndReturn(run func(context.Context) error) *MockRedisTaskConsumer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisTaskConsumer creates a new instance of MockRedisTaskConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisTaskConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisTaskConsumer {
	mock := &MockRedisTaskConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
