// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth

import (
	context "context"

	auth "gitlab.com/interview-simulation/interview-backend-server/internal/infras/auth"

	mock "github.com/stretchr/testify/mock"

	oauth2 "golang.org/x/oauth2"
)

// MockFacebookClient is an autogenerated mock type for the FacebookClient type
type MockFacebookClient struct {
	mock.Mock
}

type MockFacebookClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacebookClient) EXPECT() *MockFacebookClient_Expecter {
	return &MockFacebookClient_Expecter{mock: &_m.Mock}
}

// ExchangeCodeForToken provides a mock function with given fields: ctx, code
func (_m *MockFacebookClient) ExchangeCodeForToken(ctx context.Context, code string) (*oauth2.Token, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth2.Token, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth2.Token); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFacebookClient_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type MockFacebookClient_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockFacebookClient_Expecter) ExchangeCodeForToken(ctx interface{}, code interface{}) *MockFacebookClient_ExchangeCodeForToken_Call {
	return &MockFacebookClient_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", ctx, code)}
}

func (_c *MockFacebookClient_ExchangeCodeForToken_Call) Run(run func(ctx context.Context, code string)) *MockFacebookClient_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFacebookClient_ExchangeCodeForToken_Call) Return(_a0 *oauth2.Token, _a1 error) *MockFacebookClient_ExchangeCodeForToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFacebookClient_ExchangeCodeForToken_Call) RunAndReturn(run func(context.Context, string) (*oauth2.Token, error)) *MockFacebookClient_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthURL provides a mock function with given fields: state
func (_m *MockFacebookClient) GetAuthURL(state string) string {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFacebookClient_GetAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURL'
type MockFacebookClient_GetAuthURL_Call struct {
	*mock.Call
}

// GetAuthURL is a helper method to define mock.On call
//   - state string
func (_e *MockFacebookClient_Expecter) GetAuthURL(state interface{}) *MockFacebookClient_GetAuthURL_Call {
	return &MockFacebookClient_GetAuthURL_Call{Call: _e.mock.On("GetAuthURL", state)}
}

func (_c *MockFacebookClient_GetAuthURL_Call) Run(run func(state string)) *MockFacebookClient_GetAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFacebookClient_GetAuthURL_Call) Return(_a0 string) *MockFacebookClient_GetAuthURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFacebookClient_GetAuthURL_Call) RunAndReturn(run func(string) string) *MockFacebookClient_GetAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function with given fields: ctx, token
func (_m *MockFacebookClient) GetUserInfo(ctx context.Context, token *oauth2.Token) (*auth.FacebookUserInfo, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *auth.FacebookUserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) (*auth.FacebookUserInfo, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) *auth.FacebookUserInfo); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.FacebookUserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oauth2.Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFacebookClient_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockFacebookClient_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - token *oauth2.Token
func (_e *MockFacebookClient_Expecter) GetUserInfo(ctx interface{}, token interface{}) *MockFacebookClient_GetUserInfo_Call {
	return &MockFacebookClient_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, token)}
}

func (_c *MockFacebookClient_GetUserInfo_Call) Run(run func(ctx context.Context, token *oauth2.Token)) *MockFacebookClient_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*oauth2.Token))
	})
	return _c
}

func (_c *MockFacebookClient_GetUserInfo_Call) Return(_a0 *auth.FacebookUserInfo, _a1 error) *MockFacebookClient_GetUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFacebookClient_GetUserInfo_Call) RunAndReturn(run func(context.Context, *oauth2.Token) (*auth.FacebookUserInfo, error)) *MockFacebookClient_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFacebookClient creates a new instance of MockFacebookClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacebookClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacebookClient {
	mock := &MockFacebookClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
